### ISSUE TITLE
On viewing an expense link of the new recorded expense shows up the previous expense that was viewed 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#102]
Steps: 
1. Record an expense. 
2. Link is provided to view it. Click on that. 
3. Go back to Whats app
4. Record one more expense. 
5. Link is provided to view. Click on that

Expected - Previously added expense is viewed on clicking the link of newly added expense.  

Actual - Newly added expense should be viewed on click the link

**Comment by dattaprasad-ekavade** [comment]
The issue seemed to be iOS (Safari Browser) specific. On it, the page URL is reloaded rather than a new tab is being created when the URL is clicked.
