### ISSUE TITLE
'Planning to by 100 new chairs" description is capturing 100 as the amount 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#109]
Link- https://ajency-qa.toppeq.com/cashflow/outflow/planned#/db_1037

![image](https://user-images.githubusercontent.com/45193277/74731482-11fe9a80-526e-11ea-87b8-8f12aadc64d6.png)

**Comment by dattaprasad-ekavade** [comment]
Currently, we aren't supporting quantity in description
