### ISSUE TITLE
For Purchase statement, user is still asked the description when statement is provided with all the necessary attributes

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#126]
![image](https://user-images.githubusercontent.com/45193277/74810016-7aa05280-5314-11ea-8957-5577f942be05.png)

**Comment by dattaprasad-ekavade** [comment]
@nutank Could we assume that the user will always start the transaction in the format specified in the welcome message, and not starting from the amount or date?
Format = (To record an expense, simply try typing "Bought office stationery for $20K. I will automatically categorize and notify the respective users once you have added your expense.)

If so, we can close the issue.

**Comment by TejalBandekar** [comment]
Fixed.
