### ISSUE TITLE
For some accounts amount is negative in quickbooks where as in our system it is positive and vice versa

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#131]
Cashflow Dashboard 
![image](https://user-images.githubusercontent.com/45193277/74820409-f9eb5180-5327-11ea-869f-87e40987a579.png)

Quickbooks- 
![image](https://user-images.githubusercontent.com/45193277/74820464-12f40280-5328-11ea-96e9-a5575075ccbd.png)

**Comment by TejalBandekar** [comment]
@nutank 
Need to know why the amount  is negative in the api and positive in the Chart of Accounts

![image](https://user-images.githubusercontent.com/45193277/75651643-ff795d80-5c7e-11ea-8741-d8e21958125e.png)

![image](https://user-images.githubusercontent.com/45193277/75651672-15871e00-5c7f-11ea-9f2d-0a46a4c00723.png)

**Comment by georgioajency** [comment]
@nutank I believe, this issue can be closed

**Comment by nutank** [comment]
yes we can close this.
