### ISSUE TITLE
Deactivating of an account is not handled. 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#133]
Steps: 
1. Go to Quickbooks => Accounting => Chart of Accounts 
2. Action Column - click on the arrow and select 'Make Inactive' for the account that has to be deactivated. 
3. The count of accounts is changed from 93 to 92. 
4. Go to Incurred Outflow and click on sync
5. Refresh cashflow dashboard. 

Expected: Account which is deactivated should has been disabled from our system 

Actual: Account still shows up when it is deactivated.

**Comment by nutank** [comment]
Fix in #338
