### ISSUE TITLE
Purchase Transaction- Change of payment type in quickbooks is not reflecting in kibana 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#154]
Quickbook link- https://c50.sandbox.qbo.intuit.com/app/expense?txnId=147

![image](https://user-images.githubusercontent.com/45193277/75678787-6402df80-5cb4-11ea-954d-bf1b4a37d52d.png)

![image](https://user-images.githubusercontent.com/45193277/75678644-1ab29000-5cb4-11ea-8dac-cd27fbc83b30.png)

**Comment by TejalBandekar** [comment]
In payment api explorer for purchase type of transaction payment method is showing as cash irrespective of the method selected

https://c50.sandbox.qbo.intuit.com/app/expense?txnId=544

![image](https://user-images.githubusercontent.com/45193277/75751879-8f85d880-5d4d-11ea-8d9c-8ef454724a73.png)

**Comment by legred21** [comment]
No modification are made to api response from quickbook. Response is dumped to elastic as it is without any modification
