### ISSUE TITLE
Date of an expense got recorded as a amount for such kind of a description

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#174]
![image](https://user-images.githubusercontent.com/45193277/76422012-8e4a5080-63ca-11ea-9b6e-78248c2eea5b.png)

**Comment by dattaprasad-ekavade** [comment]
@nutank should this condition be handled in Code?

**Comment by dattaprasad-ekavade** [comment]
In code, the phrase ' 400 two'  is converted to 402, as the logic is written to convert two number phrases to be combined together as one number.

**Comment by nutank** [comment]
No need to handle this now. Closing this ticket.
