### ISSUE TITLE
Records are not getting displayed in the list view on selection of date range filter when the data exists

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#181]
![image](https://user-images.githubusercontent.com/45193277/76597690-1a718a80-6527-11ea-8749-b7edcfcea037.png)

![image](https://user-images.githubusercontent.com/45193277/76597806-56a4eb00-6527-11ea-958e-7a730ee2e187.png)

**Comment by legred21** [comment]
Date filter is now based on transaction date for Incurred outflows.
And for planned outflows filter is based on create date.

**Comment by TejalBandekar** [comment]
Fixed.
