### ISSUE TITLE
Error while adding recurring expense and saving it for Planned outflow 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#182]
type:java message:2020-03-13 13:14:06,651 ERROR graphql.servlet.DefaultGraphQLErrorHandler [http-nio-8080-exec-8] Error executing query! graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'recurringError' that is not defined for input object type 'ExpenseRecurrenceInput' at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:177) at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:162) at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:183) attype:java message:2020-03-13 13:14:06,651 ERROR graphql.servlet.DefaultGraphQLErrorHandler [http-nio-8080-exec-8] 

Error executing query! graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'recurringError' that is not defined for input object type 'ExpenseRecurrenceInput' at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:177) at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:162) at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:183) at

**Comment by legred21** [comment]
Server Side is fixed. Need a fix from front end. request contains invalid attributes
Need to remove following attributes
"recurringError":false,
    "forcastErrorMessage":"",
    "endsOnErrorMessage":"",
    "forcastError":false,
    "endsOnError":false

**Comment by legred21** [comment]
When adding recurring data, nullified checks were not done. Also null check for occurrance count was not handled due to which API was failing. Issue is now fixed by handling null checks for all parameters. Also front end issue is being fixed by removing invalid fields from request

**Comment by TejalBandekar** [comment]
Fixed.
