### ISSUE TITLE
Getting an error when trying to hit an api to add expense to quickbooks 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#188]
Account- viraj@ajency.in

![image](https://user-images.githubusercontent.com/45193277/76935366-ffcc5680-6916-11ea-8841-a3d9932dfb99.png)

**Comment by jessica-cardozo1** [comment]
In the db quickbook_account_categories table needs to be updated with the payment accounts and ids. This mapping has not been done for the account viraj@ajency.in
