### ISSUE TITLE
Implementation of formula application on the Totals of the categories

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#198]

**Comment by nutank** [comment]
Before applying need to show popup for confirmation.

![Screenshot 2020-03-30 at 12 29 06 PM](https://user-images.githubusercontent.com/7425622/77898721-3603c180-7299-11ea-96ff-68e3d8a930c6.png)

**Comment by TejalBandekar** [comment]
Done.
