### ISSUE TITLE
On applying of manual formula in the middle of the month range on existing simple growth rule/Increase by fixed value rule, the consecutive cells doesn't calculate basis the manual input range

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#212]
https://docs.google.com/document/d/1P0p4e326XhC9mNW3aG5mF3Ta-9RCbkeN5Mvg4t4tyj0/edit

**Comment by TejalBandekar** [comment]
Rule has been changed for Manual Input as per the discussion @georgioajency. Hence, the expected result will change now.

As per the current rule, when custom value is entered, consecutive cells will have no impact. The values will remain unchanged.

**Expected output:** The values should remain unchanged for consecutive months.

**Example:**
Simple increase rule of 10% is applied.
Principle    May    June     July
100            110     120      130 

Manual Input June - 200

**Output**
Principle May June July
100        110   200  130

**Comment by robiulpro** [comment]
fixed

**Comment by TejalBandekar** [comment]
Fixed.
