### ISSUE TITLE
On applying of manual formula in the middle of the month range on existing compound growth rule, the consecutive cells doesn't calculate basis the manual input range

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#213]
Expected result: The consecutive values should be calculated for compound growth rule basis the manual input value 

Actual result: The manual value entered gets added for all the consecutive value until the compound growth rule is applied

**Comment by TejalBandekar** [comment]
Rule has been changed for Manual Input as per the discussion @georgioajency. Hence, the expected result will change now.

As per the current rule, when custom value is entered, consecutive cells will have no impact. The values will remain unchanged. 

**Expected output:** The values should remain unchanged for consecutive months. 

Example: 
Compounding rule of 10% is applied. 
Principle May      June    July
100         110       121     133.1

Manual Input June - 200

**Output**
Principle   May      June    July
100           110       200     133.1

**Comment by robiulpro** [comment]
fixed

**Comment by TejalBandekar** [comment]
Fixed.
