### ISSUE TITLE
Description is not getting displayed to the users notified 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#220]
![image](https://user-images.githubusercontent.com/45193277/77290282-dbe78700-6d01-11ea-94bc-2d5a69ec056e.png)

**Comment by jessica-cardozo1** [comment]
Description in expense is null and hence not displayed.

**Comment by TejalBandekar** [comment]
It has a description. 

![image](https://user-images.githubusercontent.com/45193277/77291992-65e51f00-6d05-11ea-9cfa-c1e4d39ea19c.png)

**Comment by TejalBandekar** [comment]
Also, the tags should be in the small case letters and # should be prefixed.

**Comment by TejalBandekar** [comment]
Fixed.
