### ISSUE TITLE
Creation of an outflow on chatbot shows up watsapp link preview of the website created outflow

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#224]
![image](https://user-images.githubusercontent.com/45193277/77294142-b6f71200-6d09-11ea-8004-1ef03f147ac8.png)

**Comment by nutank** [comment]
@verlekar-viraj / @Vaibhavarolkar - can you pelase change the react app meta data?

**Comment by nutank** [comment]
@HazelColaco19 is this still valid?

**Comment by legred21** [comment]
Meta data Does not appear in whatsapp message when expense is added on production
