### ISSUE TITLE
Currently when an edit is done, a notification is sent to a user with a message "We have added an expense to Toppeq" with an updated value. Instead should we change the text to "Your expense has been updated" ?

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#229]

**Comment by georgioajency** [comment]
I need more information on this.
Where is the message sent? 
I believe we should update the text to what you mentioned, however we should provide more context as to what transaction was updated. Especially if the notification goes to someone who hasn't done the edit.

**Comment by TejalBandekar** [comment]
Fixed. 

@georgioajency Its a good suggestion. May be we can pick it up later.
