### ISSUE TITLE
Percentage value shouldn't accept more than 100 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#23]
![image](https://user-images.githubusercontent.com/45193277/73636778-b5f01f80-468c-11ea-87d3-1b36a32b4778.png)

**Comment by georgioajency** [comment]
It can actually support more than a hundred. Not sure what is the logical upper limit.

Ex. my sales of goods ay increase 3 fold next year. That is a 300% increase.
