### ISSUE TITLE
When switching from one scenario to other or on creation of new scenario loader is required

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#232]

**Comment by verlekar-viraj** [comment]
Loader already present. Cannot replicate issue

**Comment by TejalBandekar** [comment]
https://www.loom.com/share/da782ac0a9834644a7d7080b2462b120

On switching, screen is getting lighter but there isn't a visible loader.

**Comment by TejalBandekar** [comment]
Fixed.
