### ISSUE TITLE
Past data values should not be fixed. Can select a start month rather than 6 months in the past Future projection values are also be flexible - Maximum is 5 years 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#236]

**Comment by nutank** [comment]
@georgioajency - please let us know what kind of UI needs to be used here if not for a dropdown as done currently.

**Comment by georgioajency** [comment]
Based on the projection type, we need to provide a date picker for the user

Ex. monthly view will have a month to month picker. Max in future is 5 years.
This will work for now



Howvever later, we will need to have a 
date picker for daily view,
Week picker for weekly view
Quarter picker for quarterly view
Year picker for yearly view.

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/78212833-8d3ea780-74ce-11ea-8f9a-67a265fd126f.png)

**Comment by TejalBandekar** [comment]
Done.
