### ISSUE TITLE
Qb category detail type is getting displayed instead of Toppeq category names 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#247]
![image](https://user-images.githubusercontent.com/45193277/77525739-7cc77500-6eaf-11ea-98c3-f110ad480a4d.png)

![image](https://user-images.githubusercontent.com/45193277/77525628-599cc580-6eaf-11ea-87a6-d3a61ac30328.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by TejalBandekar** [comment]
Fixed.
