### ISSUE TITLE
Cash Flow Metrix >UI issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#248]
**Current behaviour with steps, if any**

1. Go to Link : https://ajency-qa.toppeq.com/cashflow/metrics
2. Section: Bank Accounts

a. The scroll does not match as in design. 
- There is no buffer space maintained between the card and the scroll.
- UI looks different as well: Scroll in design has curved edges and that in developed has sharp square/ rectangle edges.
- In design, The scroll touches the lower bottom edge of the grey background box but in developed the scroll is midway and not at the edge of the grey background box 

![image](https://user-images.githubusercontent.com/55691499/77530397-44c43000-6eb7-11ea-964b-e816c2d7744d.png)

b. Bank Name is displayed to the top right of the card, instead of bottom right like in design

![image](https://user-images.githubusercontent.com/55691499/77528703-6a9c0580-6eb4-11ea-85f0-5b85895d5791.png)

c. On desktop - If number of banks are more than 2, the banks are supposed to come on two lines. 
Currently, in design we have 5 banks - all in one line
![image](https://user-images.githubusercontent.com/55691499/77535495-b18ff800-6ec0-11ea-9976-ffaf792e88db.png)

3. Section: Average Days to collect from customers

The design includes dotted lines in the inner circle which is not the case in developed

![image](https://user-images.githubusercontent.com/55691499/77529709-23af0f80-6eb6-11ea-9c18-2c0e402431a9.png)

**Expected Behavior:**

Match the design as shown in illustration/ images

**Device/ Browser:**

Desktop/ Chrome

**Comment by Vaibhavarolkar** [comment]
Point 2 - position of bank is name os proper @HazelColaco19 
![Screen Shot 2020-03-26 at 12 17 36 PM](https://user-images.githubusercontent.com/52398680/77618274-00d73680-6f5c-11ea-8aec-f43003163a6b.png)

**Comment by HazelColaco19** [comment]
a. All here are Fixed
b. Design Updated. #301 #284 
c. Fixed
d. Another open issue to check updated design #302 

Above ticket can be closed.
