### ISSUE TITLE
Projection dashboard> Section: Cashflow & Burnrate: UI Issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#250]
**Current behaviour with steps, if any**

1. Go to Link : https://ajency-qa.toppeq.com/cashflow/dashboard

Section: Cashflow & Burnrate

a. The bar Graph is uniform in developed, but in design it has a darkened bottom edge which portrays the base to be of a darker shade of the color
b. The lines behind the graph on design are hyphenated and not continuous lines. The developed site has continuous lines
c. The graph is missing its Y axis as shown in design
d. Text discrepancy in the x axis legend:

Text on developed site v/s text in design

- Burn Rate - > Burn Amount 
- Forecasted Burn Rate - >  Forecasted Burn Amount
- Closing Cash - > Closing Cash Balance
- Forecasted Closing Cash - > Forecasted Closing Cash Balance

![image](https://user-images.githubusercontent.com/55691499/77541994-865ed600-6ecb-11ea-8f60-61c14cdd3c1f.png)

**Comment by jeromie** [comment]
@HazelColaco19 ui points irrelevant now as UI should follow #303
