### ISSUE TITLE
Projection dashboard > Section: Cash In & Cash-Out: UI Issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#251]
**Current behaviour with steps, if any**

1. Go to Link : https://ajency-qa.toppeq.com/cashflow/dashboard

![image](https://user-images.githubusercontent.com/55691499/77545657-c5435a80-6ed0-11ea-8e23-b5966552efdf.png)

a1. Graph has curved edges in design but sharp in developed
a2.The bar Graph is uniform in developed, but in design it has a darkened bottom edge which portrays the base to be of a darker shade of the color

b. Missing label for current day: " Today " on developed. It is a part of design 

c. The lines behind the graph on design are hyphenated and not continuous lines. The developed site has continuous lines

d. The x axis differs in developed from design.  In design it is a straight line, but developed it has sharp edges at the start of the axis and in between breakpoints

e. The Sequence of the Legend is swapped in developed site and is not the same as on design

**Expected Result:**

Follow design as shown in images above

**Comment by Vaibhavarolkar** [comment]
point b : "Today" label not required @HazelColaco19.

**Comment by jeromie** [comment]
@HazelColaco19 graph styles should match #303 hence these points are no longer valid.
