### ISSUE TITLE
Change of Accounting Category when adding an expense throws an error  

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#257]
Steps:

1. Go to Planned Outflow and click on '+' icon.
2. Add required fields and click on add expense. 
3. Change the accounting head to some other accounting head.
4. Click on Save changes. 
5. Expense gets listed with an updated category name.

Expected: Expense should get added without any error and should be listed in the list view with updated Accounting Category. 

Actual: Error is thrown when clicked on saved changes and expense is listed in the list view with updated Accounting Category. 

![image](https://user-images.githubusercontent.com/45193277/77653301-86c3a380-6f95-11ea-96ec-419f0b7eefce.png)

**Comment by legred21** [comment]
Issue is not with accounting head. No user is not getting notified by default for expense. Forcing user to select one. 
Need to notify by default to some user

**Comment by TejalBandekar** [comment]
@nutank On change of accounting head, users should be populated basis the Accounting Head but that is not happening currently and validation is such atleast 1 user has to be selected when Accounting head is changed and Hence, it throws an error.  Please let us know how to proceed on the same.

**Comment by legred21** [comment]
User mapping for changed accounting head was missing from accounting head user mapping table. Issue is fixed by providing necessary user mapping for each accounting head in  accounting head user mapping table

**Comment by TejalBandekar** [comment]
Fixed.
