### ISSUE TITLE
Creator of an expense also gets notification 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#258]
**Pre-requisite**- 
1. 'x' and 'y' user is mapped to Travel
2. Creator of an expense is 'x'

**Steps:**
1. Create an expense as Travel to Mumbai

**Expected:** Creator of an expense shouldn't get any notification. Only user 'y' should be notified.

**Actual:** Both the user get notified.

**Comment by jessica-cardozo1** [comment]
the creator of the expense is now being saved and omitted from list of users to be notified
