### ISSUE TITLE
Incorrect results are getting displayed on applying search and other filters

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#260]
Steps: 

1. Search "misce" in a search bar and select 'outflow type' as 'Investing'

- Result would be something like this 
![image](https://user-images.githubusercontent.com/45193277/77724369-d5fee800-7018-11ea-93e0-12141ae1f9af.png)

2.  Select the date range 26th to 29th

![image](https://user-images.githubusercontent.com/45193277/77724884-085d1500-701a-11ea-9793-db466b38f203.png)
![image](https://user-images.githubusercontent.com/45193277/77722382-a26d8f00-7013-11ea-9d5f-f022cfb1aa48.png)

Expected: Only 1 entry amounting 2623 should have get displayed

Actual: Both the entries are getting displayed

**Comment by legred21** [comment]
Date filter is applied on creation date of ouflow and not on expense due date. Column shown in list view is expense due date. 
Need clarity on which field filter should be applied.

**Comment by nutank** [comment]
@legred21 - this needs to be implemented keeping in mind the transaction date.

If toppeq expense is having payment status = pending, transaction date = due date
If toppeq expense is having payment status = paid, transaction date = payment date

Make sure the date filter and the date column should be associated to the transaction date just like incurred expenses.

**Comment by legred21** [comment]
Issue is fixed by indexing transaction date to either due date or final payment date based on payment status

**Comment by TejalBandekar** [comment]
Fixed.
