### ISSUE TITLE
Display of Accounts Payable and Accounts Receivable values for Average Days to collect for customers

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#261]

**Comment by TejalBandekar** [comment]
The value matches when start date and end date is same in quickbooks. 

For all dates, the value differs for Accounts Payable

**Comment by nutank** [comment]
As discussed with georgio, this value should always consider the end date which is sent and start date would be basically start date from QB (taken from company_quickbooks table)

@legred21/ @jessica-cardozo1 while updating values to DB, the start date that you send to balance report needs to be start date of QB always.

**Comment by TejalBandekar** [comment]
Done.
