### ISSUE TITLE
Watsapp chatbot- date is not being captured for expenses 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#263]
![image](https://user-images.githubusercontent.com/45193277/77874008-3c7a4500-7269-11ea-926d-d254ccfa1a0f.png)

**Comment by dattaprasad-ekavade** [comment]
Issue related to UI.

Expense on Dashboard:
![image](https://user-images.githubusercontent.com/48904574/77904385-1329db00-72a2-11ea-8fcc-6df7fca6ec4d.png)

Expense on Postgresql DB
![image](https://user-images.githubusercontent.com/48904574/77904591-6bf97380-72a2-11ea-92a5-9d86c1a8707e.png)
Expense is Added with the Payment date picked properly.

**Comment by TejalBandekar** [comment]
@viraj could you please check this issue ?

**Comment by nutank** [comment]
@georgioajency - we dont display payment date in our Expense UI currently. Should it be shown in such cases where there is a payment date?

**Comment by nutank** [comment]
@TejalBandekar - this should get fixed with #260

**Comment by TejalBandekar** [comment]
Fixed. Created expense in Postman and verified. 

![image](https://user-images.githubusercontent.com/45193277/78037816-a8ec6580-7389-11ea-8a0b-60c989ea9dbe.png)

![image](https://user-images.githubusercontent.com/45193277/78037803-a5f17500-7389-11ea-8fb6-218616a65b3d.png)
