### ISSUE TITLE
Incurred Outflow- Payment status- Unpaid is repeating twice in the Payment status dropdown

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#264]
Entries for which payment is not done we have 2 status'es Payment Pending and Unpaid. 

We should keep any one of them.

![image](https://user-images.githubusercontent.com/45193277/77874891-07bbbd00-726c-11ea-98f2-d572a90d6e1e.png)

**Comment by legred21** [comment]
Entry from chatbot marks payment status as "unpaid" instead of "Unpaid". Since fetch from elastic is case sensitive both will be fetched and shown in the list. Need to string  from "unpaid" to "Unpaid" in chatbot source code

**Comment by nutank** [comment]
@TejalBandekar - make sure you test this by emptying and re-indexing all data

**Comment by TejalBandekar** [comment]
Tested by emptying the elastic and re-indexing it.
