### ISSUE TITLE
Incurred Outflow- Accounting Category is not handled in the search

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#265]
**Steps:**
1. Go to Incurred Outflow 
2. List view would look something like this 
![image](https://user-images.githubusercontent.com/45193277/77875412-a3016200-726d-11ea-8faf-641d40d94745.png)
3. Enter'Travel' in the search bar. 

**Expected result:** All the entries with Travel as their category should be displayed

**Actual result:** No entry is being displayed. 

![image](https://user-images.githubusercontent.com/45193277/77875472-d17f3d00-726d-11ea-809c-62e7dd9bfbf3.png)

**Comment by legred21** [comment]
Issue existed in the search (pattern matching) was case sensitive. Pattern is now updated with case insensitive  match

**Comment by TejalBandekar** [comment]
Fixed.
