### ISSUE TITLE
Implementation of 'Added By' on creation of an expense

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#267]

**Comment by georgioajency** [comment]
What is this about?

**Comment by TejalBandekar** [comment]
It is basically about the user who has added an expense. 

![image](https://user-images.githubusercontent.com/45193277/77990576-55552a00-733f-11ea-9110-dbb930894a05.png)

**Comment by georgioajency** [comment]
If there is no user module and there is no way to show who added the expense, I would say hide the column for now. If you can show who added it then show the section.
