### ISSUE TITLE
“Past data to include ” will be dynamically populated based on how much past data we have

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#271]

**Comment by nutank** [comment]
@robiulpro - we need to send the oldest date that we have from cashflow table in projection list API

@verlekar-viraj - you would need to use this date to decide how much past period duration can be chosen by the user while creating a projection

**Comment by nutank** [comment]
@georgioajency to confirm on the UI - #236

**Comment by nutank** [comment]
@jessica-cardozo1 - query the oldest date that is present for that company_id in cashflow table and send it in "list of projections API"

**Comment by georgioajency** [comment]
This will not work since we cannot restrict past data for CSV upload. 
This will be skipped
