### ISSUE TITLE
Fetch cashflow data from "past_cashflow" table in forecast template.

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#272]

**Comment by robiulpro** [comment]
fixed

**Comment by TejalBandekar** [comment]
Data is being fetched as of past cashflow data. 

On modifying the data for category in past cashflow table, it did not reflect in the forecast template.

**Example:** 
Category- 'Accounts Receivable' 
March 2020
Value updated to 75500

**Comment by TejalBandekar** [comment]
Was checking for different projection id. Not an issue.
