### ISSUE TITLE
Planned expenses showing up as zero in forecast template

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#274]

**Comment by nutank** [comment]
@robiulpro - Currently all values are showing zero as they are not being picked from planned expense. This needs to be handled at the time of creating a projection. Whenever projection created, check any planned expense for the given future months and update that value.

**Comment by robiulpro** [comment]
As discussed putting this on hold as there is no one to one relation between qb category and planned expense category.

**Comment by nutank** [comment]
Handled in #327
