### ISSUE TITLE
Update the table colors 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#275]

**Comment by georgioajency** [comment]
Please implement this table
https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=2360%3A0

What you need to change
1. Font color and weight for forecasted data
2. Font color and weight for forecasted data
3. Row colors
4. The Totals usually have a higher weight

![image](https://user-images.githubusercontent.com/43877959/78676231-ca0e0280-7903-11ea-9d85-005783c293a7.png)

**Comment by nutank** [comment]
@Vaibhavarolkar / @jeromie - please let us know how feasible this is and what is the effort for this change.

**Comment by georgioajency** [comment]
@Vaibhavarolkar @nutank 
Please update the colors to this. Nandini just got back and she preferred this color for the table.

![image](https://user-images.githubusercontent.com/43877959/78751934-bceb2500-7990-11ea-9ce6-194e4b69798a.png)

Refer the same Figma link
