### ISSUE TITLE
Remove the word Growth from Simple and Compounding Rule. 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#276]
So now it will be Simple % Increase, Simple % decrease. Compounding % increase, Compounding % decrease

**Comment by TejalBandekar** [comment]
Done.

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/78132679-ca595a00-743a-11ea-8fbc-72663785ea55.png)

Flat Value
Simple Increase
Simple Decrease
Compounding Increase
Compounding Decrease
Increase by a Fixed Value
Decrease by a Fixed Value
Custom Value

**Comment by TejalBandekar** [comment]
Fixed.
