### ISSUE TITLE
TASK - Ability to delete a cell or a row from the projection table

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#277]

**Comment by georgioajency** [comment]
@nutank UI finalized

![image](https://user-images.githubusercontent.com/43877959/78564491-23116400-783a-11ea-9895-38b63cd241a7.png)

**Comment by georgioajency** [comment]
Functionality is working

1. Just increase the internal padding of the button
![image](https://user-images.githubusercontent.com/43877959/79715170-93b38880-82f0-11ea-916f-b12ec6aa6a60.png)
