### ISSUE TITLE
Deletion of projection scenario

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#280]

**Comment by nutank** [comment]
@jessica-cardozo1 - we would need an API to delete a projection

@verlekar-viraj - we would need to integrate delete projection UI using the above API.

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/78101156-42f0f400-7404-11ea-8b35-fa995be684aa.png)

Introduced a button to the extreme right to delete the projection

**NOTE: On click, a confirmation modal window will appear**
Are you sure you want to delete <Forecast template name>?
Cancel  |   Delete

**Comment by jessica-cardozo1** [comment]
Changes for delete projection have been done (projection should be updated with attribute deleted set to true)

**Comment by nutank** [comment]
Tracking this issue in #535
