### ISSUE TITLE
Cashflow Metrics > Header >Should indicate that till when is the data “Showing data as of today” or “01 Jan 2019 to Today”. Not editable

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#282]

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/78100627-e80acd00-7402-11ea-926c-846d8924aa0b.png)

The dropdown will have the following values
This month
Last month
This quarter
Last quarter
This year
Custom

Default value selected is This Year

If you select Custom, you get the option to enter the dates

**Comment by georgioajency** [comment]
@nutank This is a low priority. As they are planning of having this at a graph level rather than at a page level. So I told Aditya that we will keep this on hold until we finalize on what we should be doing.

**Comment by georgioajency** [comment]
Closing this task. Ideally, there will be a date picker at a page level.
