### ISSUE TITLE
Changes to Bank Accounts UI colors/design

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#284]
Figma link - https://www.figma.com/file/JeAhkkTzx51VpKaJbaYD3E/Cashflow_Toppeq-(1)?node-id=0%3A1

Color order is as below:

![2020-03-30](https://user-images.githubusercontent.com/7425622/77907795-e8428580-72a7-11ea-8fe5-8a7128f57e95.png)
![2020-03-30 (1)](https://user-images.githubusercontent.com/7425622/77907801-e973b280-72a7-11ea-8221-1205135a898a.png)

After 6, the pattern repeats again.

Scrolling/Placements logic is as below:

if 2 accounts, it's placed side by side
1      2

if more than 2 then placed i below the other
1      3       6      8
2      4       7

**Comment by jeromie** [comment]
@Vaibhavarolkar design changes also to be done apart from color changes.
