### ISSUE TITLE
Quickbooks has 2 accounts of type = Bank, however Toppeq shows only 1 (company Flipmo)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#285]
![Screenshot 2020-03-30 at 5 11 10 PM](https://user-images.githubusercontent.com/7425622/77908667-90a51980-72a9-11ea-906e-a62c8dceb67e.png)

![Screenshot 2020-03-30 at 5 12 17 PM](https://user-images.githubusercontent.com/7425622/77908713-a1558f80-72a9-11ea-82fa-c84b4ffb55c0.png)

**Comment by legred21** [comment]
one company accounts were getting overwritten by some other company accounts due to same account id. Issue is fixed by changing id to have comapny id along with accounts id
