### ISSUE TITLE
The lines should match as per the design. I.e flat and the percentage value should be above the line

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#286]
![image (5)](https://user-images.githubusercontent.com/7425622/77911353-512cfc00-72ae-11ea-892b-01eec9aa1164.png)

**Comment by nutank** [comment]
@jeromie is this possible?

**Comment by jeromie** [comment]
@nutank i'll check if it can be done.

**Comment by jeromie** [comment]
Ignoring this as UI will now be as per #303
