### ISSUE TITLE
Recurring end date is incorrect 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#29]
![image](https://user-images.githubusercontent.com/45193277/73723195-7ab62500-474e-11ea-9805-9f43cecaa023.png)

**Comment by legred21** [comment]
Fixed

**Comment by legred21** [comment]
Recurring end date was wrongly calculated for weekly, quarterly, monthly and yearly data. Issue is now fixed by calculating date based on formula for weekly, quarterly, monthly and yearly.

**Comment by TejalBandekar** [comment]
Fixed.
