### ISSUE TITLE
Projection Dashboard | Graphs - Should the bar lines be curved?

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#290]

**Comment by georgioajency** [comment]
Give me the graphs working well without the curves for now. We can work on the curves of the graph later, once we have completed the remaining graphs

**Comment by georgioajency** [comment]
@nutank No this does not need to be curved. Follow the same graph styling as used by them.

**Comment by nutank** [comment]
Closing as the graph needs to look like investor dashboard #303
