### ISSUE TITLE
How does quarterly/half yearly/yearly filter for view type, differentiate future from past when a particular period has mixture of past and future data

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#293]
Consider an example projection scenario configured of type = monthly where,
_Past = last 3 months (Jan 2020, Feb 2020, March 2020), [current is March 2020 - as the projection was created in March]
Future = Next 5 months (Apr 2020, May 2020, June 2020, Jul 2020, Aug 2020)._

For above scenario in projection dashboard page where graphs are rendered, 
if **view type = monthly =>** 
_Past = Jan 2020, Feb 2020, March 2020
Current line = will come after March
Future = Apr 2020, May 2020, June 2020, Jul 2020, Aug 2020_

If **view type = yearly =>**
_Past = Year 2020
Current line = will be after 2020
Future = there would be no data shown in future_

In this cases the amount shown for past = sum of all values in the month of Jan 2020 - Aug 2020 which would be a mixture of past and present. **Would this be correct?**
**How would one differentiate in the same year the difference between past and future?**

**Comment by georgioajency** [comment]
May have to look into this post MVP.

@nutank you can close this issue for now.
