### ISSUE TITLE
Implementation of monthly/quarterly/half yearly and yearly view type filter for graphs that are based on projection

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#294]
The following graphs should support the above view type filter:
1. Cash Flow forecast and Burn Rate
2. Cash In, Cash out 
3. Cashflow for Main category - Cash In
4. Cashflow for Main category - Cash Out

**Comment by nutank** [comment]
Need confirmation on this point for this use case - #293 from @georgioajency

**Comment by georgioajency** [comment]
Not required for MVP.
@nutank I am closing this.
