### ISSUE TITLE
List view for expenses in Toppeq 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#295]
Following needs clarity for List view of incurred expenses from QB:

1. What all transactions from QB should be shown in the list view for incurred expenses?
2. Clarity on payment status for each such transaction type shown in the list view. 
3. Should “Partially Paid” status be supported?

Following need clarity for List view of planned expenses (expenses recorded in Toppeq): (may be this is not part of milestone 1 and can be moved to milestone 2?)
1. Should paid expenses be allowed to be captured in Planned Expenses in toppeq's add expense form?. Currently they are getting captured via chatbot 
2. If point 1 needs to be done then which all Payment statuses to be handled in planned expenses

**Comment by georgioajency** [comment]
Gave a bunch of changes. We will be discussing this further on ou Weekly Product call.

**Comment by georgioajency** [comment]
This is pushed to Milestone 3. We will need more discussion with them once we take this up.

1. Inflow and outflow should be on same tab arranged date-wise
2. We need to remove Paid, Pending status column and add Opening Balance, Payment/ receipt column along with Accounts Payable & Receivable
3. Payment/ receipt should be hyperlink and show date-wise payment in case of multiple payments or payments done on date other than Transaction date (similar to QB)
4. Opening Balance
- Option 1 – Opening Balance to get adjusted as per the date range chosen
- Option 2-  If above not feasible, Opening Balance is where QB doesn’t have inception to date (ITD) information but has opening balances brought forward.

![image](https://user-images.githubusercontent.com/43877959/79223827-af91d700-7e77-11ea-87ca-e0fbdf708e67.png)

**Comment by nutank** [comment]
Closing this as it was re-done in https://github.com/ajency/cashflow-issue-tracker/issues/554
