### ISSUE TITLE
 Category is not being displayed for a bill whose line item is of type product

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#296]
Quickbook link- https://c73.qbo.intuit.com/app/bill?txnId=62

![image](https://user-images.githubusercontent.com/45193277/77931728-31a3cc80-72ca-11ea-813a-0e689a4e5f00.png)

**Comment by TejalBandekar** [comment]
Category is being shown in the elastic but doesn't seem to be displayed in the UI.

**Comment by legred21** [comment]
category was overwritten by customer reference attribute and therefore was going blank. Issue is now fixed by removing customer reference and setting category basis the item level accounting reference

**Comment by TejalBandekar** [comment]
Fixed.
