### ISSUE TITLE
Projection Dashboard | Implement Cashflow for Main Category - Infow and Outflow graph

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#297]
**Cashflow for Main category - Cash In**

![image (7)](https://user-images.githubusercontent.com/7425622/77948492-1ee9c180-72e3-11ea-8075-43d6a5f9364d.png)

**Cashflow for Main category - Cash Out**

![image (6)](https://user-images.githubusercontent.com/7425622/77948499-21e4b200-72e3-11ea-911a-6f68c70ae709.png)

**Comment by nutank** [comment]
@georgioajency - needed the color combination to be used for the two graphs above

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/78100025-4767dd80-7401-11ea-8cb6-615d0ba5a5cd.png)

Use these colors. Both graphs will have the same colors. 
Operating - Green
Investing - Blue 
Financing - Brown

Place both graphs one below the other.
