### ISSUE TITLE
Upload CSV data in the forecast template

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#298]
Orginal Reference CSV file
[Cash flow CSV.csv.zip](https://github.com/ajency/cashflow-issue-tracker/files/4405020/Cash.flow.CSV.csv.zip)

Finalised CSV file to be imported - https://docs.google.com/spreadsheets/d/1CcsqOT_pP_6toX0_MtUo3engEWcZTWDSbrYeVrKFy3c/edit?usp=sharing

**Comment by nutank** [comment]
@georgioajency - please verify if the sheet that we have decided for import is fine for us to go ahead.

**Comment by nutank** [comment]
@jessica-cardozo1 - dB tables for QB cateogries and toppeq header mapping are as follows:

1. quickbook_account_categories - list of chart of accounts from QB
2. quickbook_category_mapping_config - mapping of QB detail type with Toppeq detail type
3. toppeq_category_detail_type_mapping - mapping of toppeq detail type with activity type and cashflow type

**Comment by georgioajency** [comment]
@nutank UI to be implemented for uploading an CSV. You will need to modify the "Create a scenario" popup
![image](https://user-images.githubusercontent.com/43877959/78565226-383ac280-783b-11ea-9702-b7f686436923.png)

**Comment by georgioajency** [comment]
![image](https://user-image@nutank hubusercontent.com/43877959/78659518-4cd59400-78e9-11ea-9668-15b8dc1440b4.png)

@nutank Please check and let me know if this works for you
