### ISSUE TITLE
On change of the bill payment date, the date is not changing in our system 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#299]
The issue arises when 2 payments are done against a bill. And then one of the bill payments date is changed. The changed bill payment date is not reflecting in our system. 

**Steps:**
1. Create a bill in quickbooks. 
2. Make a payment in such a way where it has to have 2 bill payments. i.e part by part payment. 
3. Sync in our system
4. Now change the payment date of any 1 of the bill payment in quickbook.
5. Sync in our system 

**Expected:** Bill payment date has to be updated as per the update done in quickbooks

**Actual:** Bill payment date does not change

**Comment by TejalBandekar** [comment]
Client reported the case when the payment date is updated for the bill payment in quickbooks, the entry in our system goes missing. 
This issue couldn't be replicated.

**Comment by legred21** [comment]
Last updated time in quickbook is not stored in UTC format. Last sync date in our database  is stored in UTC format. Since there is a mismatch in dates , changes are not reflected in our system.

**Comment by nutank** [comment]
Fix in #338
