### ISSUE TITLE
BUG - CashFlow Metrics > Bank Account section: UI Issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#301]
**Current behaviour with steps, if any**

1. Go to Link : https://ajency-qa.toppeq.com/cashflow/metrics
2. Section: Bank Accounts

![image](https://user-images.githubusercontent.com/55691499/78035434-bc4a0180-7386-11ea-98df-a58a913c2187.png)

a. Change verbiage " Total cash " to " Total Cash "

b. Change verbiage " Bank Accounts Linked " to " Bank accounts Linked ". @georgioajency The verbiage used in developed is better than current design. 

**Expected Behavior:**

Match the design as shown in illustration/ images

**Device/ Browser:**

Desktop/ Chrome

**Comment by georgioajency** [comment]
Point b
Keep it as Bank Accounts Linked

**Comment by HazelColaco19** [comment]
Fixed
