### ISSUE TITLE
All graphs and piecharts should match in UI/UX with the one's on https://client-uat.toppeq.com/fund_of_fund

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#303]
Reference link - https://client-uat.toppeq.com/fund_of_fund

login credentials - demoinvestor/ Toppeq123

![Screenshot 2020-04-01 at 9 45 58 AM](https://user-images.githubusercontent.com/7425622/78098776-9d3a8680-73fd-11ea-8ef6-194673c077e6.png)

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/80059726-4c283900-854a-11ea-920d-bd06308b50c2.png)

On hover, don't make the bar your cursor is currently on lighter.
