### ISSUE TITLE
BUG - Selecting Scenario demo throws me the no scenario state screen

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#309]
![image](https://user-images.githubusercontent.com/43877959/78132297-1eb00a00-743a-11ea-8809-717e170a54cf.png)

![image](https://user-images.githubusercontent.com/43877959/78132363-3c7d6f00-743a-11ea-8fd6-5877501de5f6.png)

**Also on hitting back, my previous scenario is not loaded but it continues to show me this page unless I do a reload of the page.**

**Comment by TejalBandekar** [comment]
Not valid anymore.
