### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#314]
1. Value entry color is disabled. Should be white.

![image](https://user-images.githubusercontent.com/45193277/78133983-042b6000-743d-11ea-94da-2781bf80af9c.png)

2. Sort the list of created projections from A-Z

![image](https://user-images.githubusercontent.com/45193277/78134032-1a392080-743d-11ea-873e-28c14e7d0eb5.png)

3. UI issues for a 3 month past and projected duration

![image](https://user-images.githubusercontent.com/45193277/78134067-26bd7900-743d-11ea-9c9e-568cf31c7e0f.png)

4. Remove placeholder TYPE. Keep it blank

![image](https://user-images.githubusercontent.com/45193277/78134218-68e6ba80-743d-11ea-9bb1-6699d9fb42f9.png)

5. Keep upto 2 decimal places

![image](https://user-images.githubusercontent.com/45193277/78134199-5f5d5280-743d-11ea-89dc-32ce48b5ed84.png)

6. Keep the $ input field blank for Increase/Decrease by a fixed amount. Also update the text

![image](https://user-images.githubusercontent.com/45193277/78134913-8d8f6200-743e-11ea-8849-43db2feea991.png)

7. The input field size should increase if more than 4 characters are entered

![image](https://user-images.githubusercontent.com/45193277/78134946-9bdd7e00-743e-11ea-8f9b-27bd152b8f55.png)

**Comment by jeromie** [comment]
1. Done
2. Not a ui fix. 
3. Unable to replicate with current projections
4. Done
5. Can't be controlled at html input level. JS approach not working.
6. Done
7. Can't increase the size based on input value. Have increased the input size for now to fit 5 digits properly.

**Comment by TejalBandekar** [comment]
1, 3, 4, 5, 7 has been verified at my end. 

```
7. The input field size should increase if more than 4 characters are entered

![image](https://user-images.githubusercontent.com/45193277/78134946-9bdd7e00-743e-11ea-8f9b-27bd152b8f55.png)
```

> Can't increase the size based on input value. Have increased the input size for now to fit 5 digits properly.

@georgioajency Please let us know your thoughts on this.

Below issues/improvements  cannot be handled at UI end and has to be handled at react end. 
@verlekar-viraj / @robiulpro 

1. 2. Sort the list of created projections from A-Z

![image](https://user-images.githubusercontent.com/45193277/78134032-1a392080-743d-11ea-873e-28c14e7d0eb5.png)

2. 5. Keep upto 2 decimal places

![image](https://user-images.githubusercontent.com/45193277/78134199-5f5d5280-743d-11ea-89dc-32ce48b5ed84.png)
