### ISSUE TITLE
BUG - Keep the $ input field blank for Increase/Decrease by a fixed amount. Also update the text

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#315]
![image](https://user-images.githubusercontent.com/43877959/78134115-3d63d000-743d-11ea-9ccc-c683a1db4b94.png)

As per issue https://github.com/ajency/cashflow-issue-tracker/issues/276, need to update the text also to

**Fixed Increase in Value** by $ **1000** till **Jul 2020**

**Comment by TejalBandekar** [comment]
#314
