### ISSUE TITLE
BUG - Update rule text to be displayed in the pop up box

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#318]
![image](https://user-images.githubusercontent.com/43877959/78142527-a736a680-744a-11ea-9535-b8c3b00cba31.png)

Simple Increase @10% from Mar 2020
Simple Decrease @10% from Mar 2020
Compounding Increase @10% from Mar 2020
Compounding Decrease @10% from Mar 2020
Flat Value at $2500 from Mar 2020
Fixed Increase in Value by $1000 from Mar 2020
Fixed Decrease in Value by $1000 from Mar 2020

Don't need to show text for custom value

**Comment by jeromie** [comment]
For "Flat Value at $2500 from Mar 2020",  the amount isnt being passed currently. Text change is done, but need to get the value. @verlekar-viraj to check?

**Comment by TejalBandekar** [comment]
#324

**Comment by TejalBandekar** [comment]
As per the month, the month will change here
which means here it should have been May month in this case

![image](https://user-images.githubusercontent.com/45193277/78326137-3355e480-7597-11ea-9b41-ea2ddb1fdc1b.png)

@viraj please check this

**Comment by georgioajency** [comment]
@jeromie @nutank 
Really sorry for asking another change on this, but can you replace the text "from" to "since"

Simple Increase @10% since Mar 2020
Simple Decrease @10% since Mar 2020
Compounding Increase @10% since Mar 2020
Compounding Decrease @10% since Mar 2020
Flat Value at $2500 since Mar 2020
Fixed Increase in Value by $1000 since Mar 2020
Fixed Decrease in Value by $1000 since Mar 2020

**Comment by nutank** [comment]
API changes:
1. top level projection scenario changes API
2. Global Include expense to have 3 values - yes/no/custom

**Comment by robiulpro** [comment]
Fixed except Nutan comments (Viraj will implement that part as discussed)

**Comment by TejalBandekar** [comment]
Rule has been updated as per the text.

**Comment by TejalBandekar** [comment]
Done.
