### ISSUE TITLE
BUG - Cannot see large values for totals

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#319]
Ideally, it should revert to a 3 column layout as it is hard to read.

Or 

Either on hover show, a tooltip for totals

**Comment by jeromie** [comment]
cell width increased

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/78236653-ea9b1e80-74f7-11ea-80ed-a615976ac48e.png)

Example of the issue. Happens when I open the side panel

**Comment by TejalBandekar** [comment]
Not breaking for me. 

@georgioajency Please verify and let us know if it still breaks for you ?

**Comment by georgioajency** [comment]
Works for me now. Thanks
