### ISSUE TITLE
Forecast Template: Column header and text breaking

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#320]
**Describe the issue with Steps:**

_Current behavior:_

1. In Forecast Template: 
a. Principal Amount text is breaking in two lines
b. The future months column as well is breaking. Numbers as well as headers are not readable 

![image](https://user-images.githubusercontent.com/55691499/78215114-65524280-74d4-11ea-9cda-cf876e977618.png)

**Expected Result:**

a. Principal Amount should always remain on one line.
b. Have only three future shown in the template instead of six at a time ( for such a resolution )

**Screen Resolution:**

1366x768

**Comment by jeromie** [comment]
@HazelColaco19 browser in screenshot is zoomed as can be seen in the url bar. Please reset zoom level and check.

**Comment by HazelColaco19** [comment]
Reset works. Closing the issue.
