### ISSUE TITLE
BUG - Values in Forecast Template and the chart are not matching for " account receivable "  and "Sale of goods "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#323]
**Current behavior with steps:**

1. The Values when added together under " Account Receivable "   and "Sale of goods " do not sum up to match the value shown in graph2. 
3. Link To Sheet:  https://docs.google.com/spreadsheets/d/1t0L-wH2V7KYx4dU1Cn5inBZDFCxT5QnpTgDMJJSRLxI/edit?usp=sharing. Check Column " SUM "
3b. Link to Table; https://ajency-qa.toppeq.com/cashflow/projection/4897/edit
4. For Account receivable: Total in SUM from visible forecast template = 558,100. Total on Graph = 586600
5. For Sale of Goods: Total in SUM from visible forecast template = 686800. Total on Graph = 736866

**Expected**

The sum values should match for the percentage as well to match

**Comment by legred21** [comment]
April 2019 data was not consider in calculation.
