### ISSUE TITLE
For "Flat Value at $2500 from Mar 2020",  the amount isnt being passed currently. Text change is done, but need to get the value. @verlekar-viraj to check?

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#324]
For "Flat Value at $2500 from Mar 2020",  the amount isnt being passed currently. Text change is done, but need to get the value. @verlekar-viraj to check?

_Originally posted by @jeromie in https://github.com/ajency/cashflow-issue-tracker/issues/318#issuecomment-607643981_

**Comment by robiulpro** [comment]
Fixed

**Comment by TejalBandekar** [comment]
Fixed.
