### ISSUE TITLE
BUG - Total cash In > " Sale Of Goods " March 2020 value on Forecast Template does not match the values in DB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#326]
**Current Behavior**

1. Under Cash In, in the forecast template The value for March 2020 is **5566**
![image](https://user-images.githubusercontent.com/55691499/78242042-fb02c780-74fe-11ea-9234-0ff6359032e2.png)

2. In the DB, for cash in the the value  for March 2020 is **85566**
![image](https://user-images.githubusercontent.com/55691499/78242074-06ee8980-74ff-11ea-8850-66709863ef6d.png)

**Expected**

1. Entries in forecast template should match with DB.
2. The sum should reflect on the graph.

**Comment by nutank** [comment]
@HazelColaco19 - this is not an issue. There were 2 records for the month of march. Ideally there should only be one value for the month of march if period type is "monthly"

**Comment by HazelColaco19** [comment]
Post deletion entries now seem correct and match the graph. Will close the issue
