### ISSUE TITLE
Update of planned expense in forecast template

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#327]
Planned expenses are picked from Toppeq and are mapped against toppeq categories as against quickbook categories.

We would need a way to have planned expenses against quickbook categories

**Comment by georgioajency** [comment]
While creating a planned expense, we should now automatically select the QB category. This will be also shown to the user while creating an expense. User can change this value.

**Comment by nutank** [comment]
API Changes:

1. Add expense API to include QB category ID
2. API that gives a dropdown of QB categories basis toppeq category detail type

**Comment by legred21** [comment]
- [x] Add expense API to include QB category ID
- [x]  Update index to elastic to index qbCategoryId for planned expenses in elastic
- [x]  API that gives a dropdown of QB categories basis toppeq category detail type

**Comment by legred21** [comment]
Add expense API to include QB category ID
API that gives a dropdown of QB categories basis accounting head id
