### ISSUE TITLE
BUG - Too much gap on scrolling under the category navigation panel

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#328]
![image](https://user-images.githubusercontent.com/43877959/78245991-06a5bc80-7506-11ea-8792-dcc95d19c2ba.png)

**Comment by jeromie** [comment]
We have to maintain this column width otherwise the background color doesnt extend till the end of the column. If width is reduced, longer category names break the ui.

**Comment by Vaibhavarolkar** [comment]
Have reduced the spacing, if we reduce it more UI will break.
@georgioajency

**Comment by georgioajency** [comment]
Ok. This works for now.
Checked
