### ISSUE TITLE
BUG - Total cash out > " Marketing & Sales " Jan 2020 value on Forecast Template does not match the values in DB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#329]
**Current Behavior**

1. Under Cash In, in the forecast template The value for Jan 2020 is 350
2. Under Cash In, in the DB The value for Jan 2020 is 700

![image](https://user-images.githubusercontent.com/55691499/78246583-02c66a00-7507-11ea-9da0-bd469137b1e5.png)

**Expected**

Entries in forecast template should match with DB.
The sum should reflect on the graph.

**Comment by legred21** [comment]
same as #333

**Comment by georgioajency** [comment]
@HazelColaco19 Please re-check this and see it this is working

**Comment by HazelColaco19** [comment]
Fixed
