### ISSUE TITLE
BUG - Total cash out > " Operating Outflow - Others " Jan 2020, March 2020 value on Forecast Template does not match the values in DB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#330]
**Current Behavior**

1. Under Cash In, in the forecast template The value for Jan, March 2020 is 180, 679 resp
2. Under Cash In, in the DB The value for Jan 2020, March  is 360, 428000.33 resp

![image](https://user-images.githubusercontent.com/55691499/78249133-78343980-750b-11ea-97d0-7dc1355d2409.png)

**Expected**

Entries in forecast template should match with DB.
The sum should reflect on the graph.

**Comment by legred21** [comment]
same as #333

**Comment by HazelColaco19** [comment]
Fixed
