### ISSUE TITLE
BUG - Total cash out > " Interest Paid " Jan 2020 value on Forecast Template does not match the values in DB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#331]
**Current Behavior**

1. Under Cash In, in the forecast template The value for March 2020 is 90800
2. Under Cash In, in the DB The value for March 2020 is 181600

![image](https://user-images.githubusercontent.com/55691499/78249593-3788f000-750c-11ea-88fb-07fdb241f690.png)

**Expected**

Entries in forecast template should match with DB.
The sum should reflect on the graph.

**Comment by legred21** [comment]
same as #333

**Comment by HazelColaco19** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/55691499/79337092-8722df00-7f42-11ea-8b5d-a6f42d8185d9.png)
