### ISSUE TITLE
BUG - Total cash out > " Accounting & Legal " March 2020 value on Forecast Template does not match the values in DB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#332]
**Current Behavior**

Under Cash In, in the forecast template The value for March 2020 is 10000
Under Cash In, in the DB The value for March 2020 is 20000

![image](https://user-images.githubusercontent.com/55691499/78251061-66a06100-750e-11ea-82cd-cd6eb060bdcd.png)

**Expected**

Entries in forecast template should match with DB.
The sum should reflect on the graph.

**Comment by georgioajency** [comment]
@HazelColaco19 @nutank Can you please verify this?

**Comment by HazelColaco19** [comment]
@georgioajency The value doesn't exist anymore for March ( it is empty ), but I verified for another past value which is January and it is accurate. 

![image](https://user-images.githubusercontent.com/55691499/79858634-584ab400-83ed-11ea-9910-6207a942594a.png)

**Comment by georgioajency** [comment]
Ah. Closing this.
