### ISSUE TITLE
BUG - Total cash out > " Admin Expenses " Jan 2020 value on Forecast Template does not match the values in DB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#333]
**Current Behavior**

1. Under Cash In, in the forecast template The value for Jan 2020 is 6000
2. Under Cash In, in the DB The value for Jan 2020 is 2700

![image](https://user-images.githubusercontent.com/55691499/78251556-28577180-750f-11ea-8047-5dffef1f9bb9.png)

**Expected**

Entries in forecast template should match with DB.
The sum should reflect on the graph.

**Comment by legred21** [comment]
Database contains duplicate entries for certain months which impacts the aggregation of values. and therefore graph is not matching with forecast template.

**Comment by HazelColaco19** [comment]
fixed


![image](https://user-images.githubusercontent.com/55691499/79336250-06171800-7f41-11ea-8f1e-b6f40c48fc3e.png)
