### ISSUE TITLE
When there's a manual entry, all consecutive values should not recalculate basis the manual input value. Should be calculated basis the previous rule. 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#341]
If you have applied formula from 
**Steps**
1. May to July 
2. Simple increase 10% and Principal amount is Average 
3. Now you make a manual input for June 
4. Now you change the principle amount from Average to Last month

**Expected:** The consecutive values should be recalculated basis the Previously applied rule and not on manual input. 

**Actual:** The consecutive values recalculates basis the manual input.

**Comment by robiulpro** [comment]
fixed

**Comment by TejalBandekar** [comment]
Fixed.
