### ISSUE TITLE
Cashflow type and outflow type is not showing up in elastic for few quickbook categories 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#342]
1. Finance Costs
2. Other Current Liabilities 
3. Rent or Lease
4. Machinery and Equipment

**Comment by legred21** [comment]
qb account subtype stored in elastic was not matching with value stored in qb_category_detail_type column of quickbook_category_mapping_config table

**Comment by TejalBandekar** [comment]
Fix.ed
