### ISSUE TITLE
BUG - Records do not showing up in cashflow forecast template for the month of March even when there are records. DB shows only 1 record synced

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#345]
Expense record, of Category "Shipping" shows up in QB and elastic but not present in cashflow table. Happens for multiple such records.

![Screenshot 2020-04-06 at 2 28 55 PM](https://user-images.githubusercontent.com/7425622/78541571-77551d80-7813-11ea-87cc-43808bc38a51.png)

![Screenshot 2020-04-06 at 2 32 53 PM](https://user-images.githubusercontent.com/7425622/78541608-85a33980-7813-11ea-8dbd-8b6d7f732689.png)

FYI, all mappings exist. Verified by checking following queries:

SELECT * from public.quickbook_account_categories
WHERE company_id = 8
AND qb_category_name = 'Shipping' 

SELECT * FROM public.quickbook_category_mapping_config
WHERE qb_category_detail_type = 'Shipping Freight Delivery Cos'

SELECT * FROM public.toppeq_category_detail_type_mapping
WHERE toppeq_category_detail_type = 'Cost of Goods Sold'
and
company_id = 8

**Comment by nutank** [comment]
Similar record, of Category "Shipping" shows up in QB and elastic but not present in cashflow table

![Screenshot 2020-04-06 at 2 28 55 PM](https://user-images.githubusercontent.com/7425622/78541571-77551d80-7813-11ea-87cc-43808bc38a51.png)

![Screenshot 2020-04-06 at 2 32 53 PM](https://user-images.githubusercontent.com/7425622/78541608-85a33980-7813-11ea-8dbd-8b6d7f732689.png)

FYI, all mappings exist. Verified by checking following queries:

SELECT * from public.quickbook_account_categories
WHERE company_id = 8
AND qb_category_name = 'Shipping' 

SELECT * FROM public.quickbook_category_mapping_config
WHERE qb_category_detail_type = 'Shipping Freight Delivery Cos'


SELECT * FROM public.toppeq_category_detail_type_mapping
WHERE toppeq_category_detail_type = 'Cost of Goods Sold'
and
company_id = 8

**Comment by TejalBandekar** [comment]
For the month of Jan, records for Category "Shipping"  'Telephone charges' and 'Taxes and Licences' shows up in QB, elastic but not present in forecast template. 

In db, it has values for daily but doesn't have aggregate amount for Monthly period type. 

![image](https://user-images.githubusercontent.com/45193277/78552531-4da4f200-7825-11ea-98f3-8090e0734e5a.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by TejalBandekar** [comment]
Fixed.
