### ISSUE TITLE
Average Days Section: Should the hyphen be displayed in this section at anytime?

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#346]
![image](https://user-images.githubusercontent.com/55691499/78553131-66fa6e00-7826-11ea-9758-63feaf554aac.png)

**Comment by georgioajency** [comment]
This is a bug. Should not show -

There has to be a value for this.

@nutank this is still showing blank

**Comment by nutank** [comment]
Looks related to #292

**Comment by georgioajency** [comment]
Yes, however, for an extreme scenario it should not be showing a - but a 0

**Comment by georgioajency** [comment]
@nutank Not sure how to go about testing for this case

@HazelColaco19 Please look into this
