### ISSUE TITLE
Closing Cash balance not getting updated as per QB Cashflow report

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#347]
URL hit for a period of 1st April 2019 - 6th April 2020
https://ajency-qa.api.toppeq.com/rest/api/updateCompanyCashData?company_id=8&start_date=2019-04-01&end_date=2020-04-06

Closing cash balance for April 31, 2019 as per QB is 

![Screenshot 2020-04-06 at 6 00 44 PM](https://user-images.githubusercontent.com/7425622/78558622-901ffc00-7830-11ea-83e1-7dcd4dcb6c0e.png)

In DB it shows 
![Screenshot 2020-04-06 at 6 02 02 PM](https://user-images.githubusercontent.com/7425622/78558777-d5442e00-7830-11ea-8213-2c617519e9b9.png)

Refer projection template - https://ajency-qa.toppeq.com/cashflow/projection/7786/edit
![Screenshot 2020-04-06 at 6 03 40 PM](https://user-images.githubusercontent.com/7425622/78558864-f9077400-7830-11ea-8581-2720d343b946.png)

**Comment by nutank** [comment]
Accounts payable = $34,450.00 and Accounts receivable = $140,150.00  as on 30th April is also differing

![Screenshot 2020-04-06 at 6 09 21 PM](https://user-images.githubusercontent.com/7425622/78559316-ce69eb00-7831-11ea-8bfc-92ad24d88555.png)

**Comment by jessica-cardozo1** [comment]
Accounts Payable, Receivable was differing because the qb_start_date column in company_quickbook_accounts table was set to 01-01-2020. I've changed the start date to 01-01-2019. The values now match the quickbook values.

**Comment by TejalBandekar** [comment]
Accounts Payable and Accounts Receivable data fetches correctly in db. Closing cash balance is not correctly updating in the forecast template. #370
