### ISSUE TITLE
Projection Dashboard > Cash In Cash Out graph : There is an offset of appearance of the tooltip as we progress from first bar to the last in the graph

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#348]
**Current behavior:**

1. Hover on the first graph as shown on the left, you notice the tooltip appears where the mouse pointer is placed at.

2. Now keep doing this and you will notice the tooltip slowly offsets and is not placed on the bar graph being hovered upon.
The dot in red is the placement of the mouse pointer

![image](https://user-images.githubusercontent.com/55691499/78561572-982e6a80-7835-11ea-9fdf-847371b44358.png)

**Expected:**

The tooltip behavior should not change. Should be the same for all the bars in the graph.

**Comment by Vaibhavarolkar** [comment]
This is not issue, there is no offset. The edge of the tooltip always is on the first bar for a pair of bars. it may be on left or right, but its always aligned to the first bar for a pair of bars
@HazelColaco19

**Comment by HazelColaco19** [comment]
Alright, if that is how it is. Can be closed.
