### ISSUE TITLE
Projection dashboard > Cash In & Cash-Out graph > the data for cash out does not match in March 2020 bar graph

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#349]
Projection ID: 7794

![image](https://user-images.githubusercontent.com/55691499/78562197-9f09ad00-7836-11ea-8ac6-5594d9a34b35.png)

Same goes with the Values for **April 2020.**

On forecast template Cashout is 1897
and on graph is 2794

**Comment by nutank** [comment]
@HazelColaco19 - this was an older projection scenario which has incorrect data.

Please refer to projection scenario 5150 (for older imported data) or any other newer projection (for data from Quickbooks)

**Comment by HazelColaco19** [comment]
Matches now. Fixed
