### ISSUE TITLE
Projection dashboard > Cash In & Cash-Out graph : The legends are visible even if the data is not available ( or graph does not include these values ) 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#350]
**Current Behavior:** 

The Legends for bar graph whose data is null or cannot be visually seen in the graph are seen below.

![image](https://user-images.githubusercontent.com/55691499/78563307-64087900-7838-11ea-9216-bb5d74481a67.png)

**Expected** 

The Legends for bar graph whose data is null or cannot be visually seen in the graph should also be hidden

**Comment by georgioajency** [comment]
Checked
