### ISSUE TITLE
Projection dashboard > Cash In & Cash-Out graph > the dollar value in tooltip is too close to the  Cashout label

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#351]
![image](https://user-images.githubusercontent.com/55691499/78564011-7636e700-7839-11ea-8d73-0814af41cb68.png)

**Comment by georgioajency** [comment]
@Vaibhavarolkar I hope this fix is implemented on all the graphs

**Comment by georgioajency** [comment]
Fixed.
