### ISSUE TITLE
Projection dashboard >Cashflow & Burnrate : The Burnrate values on graph do not match the " Operating Cash Out " values 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#352]
**Current Behavior:**

 The Burn Rate values on graph do not match the " Operating Cash Out " values 

_Scenario with  months_

June 2019

![image](https://user-images.githubusercontent.com/55691499/78574477-ab4a3600-7847-11ea-9432-cc90cc3c7faa.png)

March 2020

![image](https://user-images.githubusercontent.com/55691499/78574638-e64c6980-7847-11ea-8dfe-73727323f367.png)

April 2020

![image](https://user-images.githubusercontent.com/55691499/78574803-2875ab00-7848-11ea-929a-b9242038a469.png)

**Expected:**

Bunrate = Operating cash out of the month

**Comment by nutank** [comment]
Cash in hand values also do not match as per the forecast template:

![2020-04-07](https://user-images.githubusercontent.com/7425622/78640417-57823000-78cd-11ea-8368-babccab975f3.png)

![2020-04-07 (1)](https://user-images.githubusercontent.com/7425622/78640425-594bf380-78cd-11ea-936d-63b6ac01c9d1.png)

**Comment by legred21** [comment]
Database contains duplicate entries for certain months which impacts the aggregation of values. and therefore graph is not matching with forecast template.
Closing cash graph showing zero value for months is now fixed by replacing "inner join" with "full outer join"

**Comment by HazelColaco19** [comment]
Matches now. Fixed
