### ISSUE TITLE
Bill Payments are not synced to elastic and hence, doesn't show up in the Forecast template

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#353]
**March**
- https://c43.qbo.intuit.com/app/billpayment?txnId=267
- https://c43.qbo.intuit.com/app/billpayment?txnId=268

**April**
- https://c43.qbo.intuit.com/app/billpayment?txnId=281

**May**
- https://c43.qbo.intuit.com/app/billpayment?txnId=275
- https://c43.qbo.intuit.com/app/billpayment?txnId=276

**June**
- https://c43.qbo.intuit.com/app/billpayment?txnId=279

**July**
- https://c43.qbo.intuit.com/app/billpayment?txnId=280

**Comment by TejalBandekar** [comment]
Company id = 8

**Comment by nutank** [comment]
Tried syncing today. Bill payments dont seem to be sent to elastic:

![Screenshot 2020-04-15 at 3 38 41 PM](https://user-images.githubusercontent.com/7425622/79325668-35bd2480-7f2f-11ea-9f79-a08ae32d1600.png)

**Comment by georgioajency** [comment]
Bill payments showing up.
However, there is a mismatch of COGS data. Have created a separate issue for it. 

Closing this as this is done
