### ISSUE TITLE
Runway and Upcoming Expenses/Income

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#355]
Ex: Projection period = Aug 2019 to  Mar 2021
   Past data - Aug 2019 to Mar 2020
   Forecasted data - Apr 2020 to Mar 2021

**Gross Runway**
Average gross operating expense = Sum of all gross operating expenses for projected months (i.e  Apr 2020 to Mar 2021 ) / no. of projected months (i.e  12)
Gross Runway = Current Cash balance /  Average gross operating expense 

Same for Net. It will be for projected months.

**Net Runway**
Average net operating expense = sum of all net operating expenses for projected months (i.e  Apr 2020 to Mar 2021 ) / no. of projected months (i.e  12)
*Net is Cash Out - Cash In
Net Runway = Current Cash balance /  Average net operating expense

**Please note** - _Here "Current Cash balance" = Closing cash balance of the prior month of the first future projected month. This value should not be picked from Quickbook's current cash in hand._

**Top expenses** - This is "Top <3> projected expenses for May 2020" - where May 2020 is the immediate next month
**Top Income** - Top <3> projected income for May 2020

**Scenarios to handle:**

- If current cash on hand is negative - Runway value is 0
- If there is no operating data -  We consider the last 12 months past data and calculate operating expenses from it. if less than 12 past months exist, then use those many months
- Data only included for 1 month projection - the no. of projected months will be 1. We need to find the last month there is data under operating expenses and accordingly calculate this value

![image (11)](https://user-images.githubusercontent.com/7425622/78633472-5e09ab00-78bf-11ea-9fa1-80518413d544.png)

**Comment by nutank** [comment]
@georgioajency - current month would be part of past months mostly right? unless if we are looking at older projections in which case current month could be in the future in order to display projected amounts

**Comment by georgioajency** [comment]
I did not understand your point. 
The current month is the current month. I want to know the top upcoming expenses this month.

**Comment by nutank** [comment]
As discussed with @georgioajency , since current month has past data and is considered as a past month, Top expenses and Top Income will be picked up for the immediate next month

**Comment by nutank** [comment]
As discussed,

2 maxrunay days defaults to be maintained against the company:
maxrunway days default for net runway =  6 months
maxrunway days default for gross runway = 8 months
