### ISSUE TITLE
Working Capital Ratio & Quick Ratio

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#356]
Working Capital
WC = Current Assets/Current Liabilities

Quick Ratio
QR = (Current Assets - Inventory Assets)/Current Liabilities

![image (10)](https://user-images.githubusercontent.com/7425622/78627949-67d7e200-78b0-11ea-8037-66e6801b927f.png)

**Comment by nutank** [comment]
@georgioajency - how is the ideal range for WCR and QR decided? Is it a configurable value for companies?

**Comment by georgioajency** [comment]
@nutank 
Quick ratio is 1.0 to 1.4
WCT is 1.5 to 2.0

These values can be configurable. 

Aditya was saying if we could show an arrow on the graph to depict the current value.
Or we could just show different colors for the graph sections and based on the range it falls the number will accordingly reflect the same.

**Comment by nutank** [comment]
@jessica-cardozo1 - please add these values to auto sync code along with account receivable and payable from balance sheet

**Comment by nutank** [comment]
![2020-04-08](https://user-images.githubusercontent.com/7425622/78864030-74973a00-7a58-11ea-9795-d766121b0cda.png)

**Comment by georgioajency** [comment]
@nutank 
Values are showing blank

![image](https://user-images.githubusercontent.com/43877959/79155516-dce67280-7dee-11ea-932d-38f1cbbf3f20.png)

**Comment by georgioajency** [comment]
Values are correct. My only concern is that this appears blank at times.
