### ISSUE TITLE
BUG - 2 out of 10-15 times outflow doesn't gets added - throws error

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#357]
![image](https://user-images.githubusercontent.com/43877959/78628062-bbe2c680-78b0-11ea-9852-84508f83be3d.png)

It looks like a server error. Tested on our end. Works fine.

@nutank : Awaiting response from Aditya's side.

**Comment by dattaprasad-ekavade** [comment]
Flow of Message from Whatsapp to DB

`Whatsapp ==> Twilio ==> Twilio Webhook ==> Dialogflow ==> Dialogflow Webhook ==> addExpense API ==> Dialogflow Webhook ==> Twilio Webhook  ==> Whatsapp`

Time Limit for Webhook:
Twilio Webhook = 30 seconds
Dialogflow Webhook = 5 Seconds

On Ajency-qa Server, The average time taken by the complete transaction ~= 4.5 s. 

On the Staging server, The average time taken by the complete transaction ~= 6.0 s.  
So, the Webhook timeout causes the default message to be sent. 

Possible ways to reduce the time:
1. Reduce time taken by the addExpense API call or Detecting  Category & Tags API
2. DB query time to be reduced. Currently, on average it takes 5-6 DB Calls.

**Comment by georgioajency** [comment]
@nutank should we be optimizing this further? 4 sec is also quite a large time to complete a transaction. And if it takes longer than 5s to timeout I feel it's cutting it quite close and there will be a high possibility of this failing.

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/79142920-eaddc880-7dd9-11ea-8237-57771c9f9ad0.png)

I got this issue on our sandbox. I think it was because my internet was bad.

**Comment by georgioajency** [comment]
@nutank @dattaprasad-ekavade 

Aditya used the app and only found one issue
![image](https://user-images.githubusercontent.com/43877959/79379940-52804900-7f7d-11ea-81f2-24e7261f8a75.png)

Could you let me know what could have caused this to happen?

**Also, for repeat expenses, we should have an option to mark it as once/onetime payment**

**Comment by legred21** [comment]
repeat expense once is not supported

**Comment by nutank** [comment]
Handled with "Never" option.
