### ISSUE TITLE
BUG - Expense added doesn’t gets added to planned outflow

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#358]
Sometimes it does not get added. Whichever is added, it shows up. 
Noticed usually happens if the due date for the expense is in the past.

Expense id references
7204 7200

![image](https://user-images.githubusercontent.com/43877959/78628262-41ff0d00-78b1-11ea-8208-1ce4e1f20261.png)

**Comment by nutank** [comment]
Is this same as issue #366 ?

@georgioajency

**Comment by georgioajency** [comment]
@nutank yes I think both the issues are related.
