### ISSUE TITLE
BUG - Rents showed tags as Taxi. There are many such examples which are getting incorrectly tagged

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#359]
Usually happens if you are adding rent as an expense

![image](https://user-images.githubusercontent.com/43877959/78628449-c6ea2680-78b1-11ea-81d7-1c9496c0fcd1.png)

**Comment by dattaprasad-ekavade** [comment]
Changed the Tags Agent for Dialogflow Keys, So the issue is solved.

**Comment by nutank** [comment]
@dattaprasad-ekavade - Which dialogflow agent was it pointed to earlier in that case? How was it different in terms of training data.

**Comment by nutank** [comment]
@dattaprasad-ekavade  - please list all the tags that we are providing support for and which are the most well trained tags?

**Comment by georgioajency** [comment]
@nutank Tested. Works.

**Comment by HazelColaco19** [comment]
Tested for category rent, tax, Purchase of Assets. Tags found fixed:

![image](https://user-images.githubusercontent.com/55691499/79827829-fe31fa80-83bc-11ea-84ca-2981fb4624f3.png)



![image](https://user-images.githubusercontent.com/55691499/79826869-7d71ff00-83ba-11ea-8e22-66e93a69a353.png)
