### ISSUE TITLE
BUG - Category not correctly getting picked

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#361]
Most of the time the Category selected is the default. Happens mostly for Rent type.

![image](https://user-images.githubusercontent.com/43877959/78628814-fbaaad80-78b2-11ea-8728-bc110823a676.png)

**Comment by dattaprasad-ekavade** [comment]
Similar to #359

**Comment by nutank** [comment]
Category "Others" is coming from the server end not from the bot's end.

Bot gives the category as "Rent"

![Screenshot 2020-04-09 at 4 33 41 PM](https://user-images.githubusercontent.com/7425622/78888749-e46ceb00-7a7f-11ea-8289-47cdda024e5c.png)


Accounting Head Table doesnt seem to have this value in the slug:

![Screenshot 2020-04-09 at 4 32 25 PM](https://user-images.githubusercontent.com/7425622/78888775-f2bb0700-7a7f-11ea-8bb8-ee46e05fad14.png)

**Comment by nutank** [comment]
@dattaprasad-ekavade  please let us know which is the most well trained category and tag. So we can get a sign off on that.

@georgioajency - training all the other categories  and tags with more data is a separate task that needs to be picked up later to fine tune this auto allocation logic.

**Comment by georgioajency** [comment]
@nutank ok. It will have to be done. Please take it up accordingly. Cause for me it will continue to remain as a bug as there was a clear category for this expense but it was assigned to Others.

**Comment by HazelColaco19** [comment]
Tested for category rent, tax, Purchase of Assets. Category found fixed:

![image](https://user-images.githubusercontent.com/55691499/79828064-8fa16c80-83bd-11ea-91cb-66d76d60c5a9.png)


Closing the issue

**Comment by nutank** [comment]
Well trained category  - "Taxes", "Travel"

Well trained tags -

"Travel" - 
#travel", "#flight", "#taxi", "#fuel" etc.

"Taxes" - 
"#"

Sample sentences for above - 




@HazelColaco19 please confirm.

**Comment by HazelColaco19** [comment]
Well trained category - "Taxes", "Travel"

Well trained tags -

"Travel" -
#travel", "#flight", "#taxi", "#fuel" etc.
_Added by Hazel:_ "#Fare",  "#Trip", "hotel_booking", "#One_way_trip", "round_trip"

Sample sentences for above -

1. Travel

_Added by Hazel:_
a. cab fare 2000 OR paid 2000 for cab fare OR will pay 2000 for cab fare
b. trip cost 100000 OR paid 100000 for Bangkok trip Or will pay 100000 for bangkok trip 
c. Hotel pre booking of 2K INR OR will book hotel for 3000k next month
d. One way trip cost 1K OR paid 1k for India to China one way trip OR will pay 1k to the upcoming india to china one way trip
e. Round trip cost 1K OR paid 1k for India to China round trip OR will pay 1k to the upcoming india to china round trip


"Taxes" -
Added by Hazel: "#assessment",  "revenue", "return", "audit", "deduction"

Sample sentences for above -

1. Travel

_Added by Hazel:_
a. tax assessment for year 2019-2020 is 10k INR OR  tax assessed will be 10k for the year 2019-2020
b. To claim 2000INR through IT returns 
c. Tax generated on current revenue will be 20k OR Tax to be generated on past revenue is 20k
d. a total deduction of 1lakh INR on revenue generated last year

**Comment by HazelColaco19** [comment]
**TRAVEL:** 

1. For the sample sentence, the tag of "Fare" doesn't apply
> a. cab fare 2000 OR paid 2000 for cab fare OR will pay 2000 for cab fare


2. For the sample sentence, the tag of "Trip" doesn't apply
> b. trip cost 100000 OR paid 100000 for Bangkok trip Or will pay 100000 for bangkok trip


3. For the sample sentence, the tag of "hotel_booking" doesn't apply
> c. Hotel pre booking of 2K INR OR will book hotel for 3000k next month


4. For the sample sentence, the tag of "One_way_trip", "flight", "travel" doesn't apply
Also, category gets populated to Others. It should be " Travel "
> d. One way business trip cost 1K OR paid 1k for India to China one way business trip OR will pay 1k to the upcoming india to china one way business trip


5. For the sample sentence, the tag of "round_trip", "flight", "travel" doesn't apply
Also, category gets populated to Others. It should be " Travel "
> e. Round trip cost 1K OR paid 1k for India to China round trip OR will pay 1k to the upcoming india to china round trip

-------
**TAXES**

1. For the sample sentence, the tag of "assessment" doesn't apply
> a. tax assessment for year 2019-2020 is 10k INR OR tax assessed will be 10k for the year 2019-2020


2. For the sample sentence, the tag of "return" doesn't apply
> b. To claim 2000INR through IT returns


3. For the sample sentence, the tag of "revenue" doesn't apply
> c. Tax generated on current revenue will be 20k OR Tax to be generated on past revenue is 20k


4. For the sample sentence, the tag of "deduction" doesn't apply
Also, category gets populated to Others. It should be " Taxes "

> d. a total deduction of 1lakh INR on revenue generated last year

**Comment by legred21** [comment]
added expense  with title as "Flight trip to banglore" :  Tags recognized are #flight, #travel 
added expense  with title as "tax paid of 20000" :  Tags recognized are #miscellaneous, #taxes
