### ISSUE TITLE
BUG - Users notified should not show mobile numbers

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#362]
Others should receive notifications and in that, it should also mention who else has been notified about this.

If there was a manual entry of phone number then that should show up.
Else if the number already exists in the db then it should show the name directly.

**Comment by nutank** [comment]
@georgioajency - we only allow numbers that are part of company to be notified. So even if a number was tagged we should always have a name against that user. Should the name only shown in that case?

**Comment by nutank** [comment]
@dattaprasad-ekavade / @jessica-cardozo1 - please do this change.

**Comment by nutank** [comment]
@jessica-cardozo1 can you handle your part here?

**Comment by jessica-cardozo1** [comment]
@nutank I will make changes to display the names of the users in the list of users notified.

**Comment by HazelColaco19** [comment]
When entered a manual phone number entry ( number that is in the company DB ), the notified users can see the name associated to that number. 

![image](https://user-images.githubusercontent.com/55691499/79972468-a0cca500-84b3-11ea-8c43-73fa1e223ca1.png)
