### ISSUE TITLE
BUG - Payment status sometimes is Paid and sometime Unpaid

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#364]
Not an issue. Probably if the text is unclear we can ask if it is Paid or Unpaid.
Ex. Rent of 2000. This is not defined if this is paid or unpaid.

**Comment by dattaprasad-ekavade** [comment]
Currently, Payment status is determined by the tense of the statement. 

Ex. 
```
"Rented a car" ==> The Tense is Past ==> Payment Status = Paid

"Rent a car" ==> The Tense is not Past ==> Payment Status = Unpaid
```

**Comment by nutank** [comment]
No need to handle for now as discussed
