### ISSUE TITLE
BUG - There are some expenses that are present but without a date

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#365]
This could be expenses that are showing as added but not being added. 
Some of the expenses that do not ask for the due date automatically assigns today as the default date. For such expenses, the question "When is this due" is not asked.
7204 7200

![image](https://user-images.githubusercontent.com/43877959/78628374-999d7880-78b1-11ea-91b8-0387b5846393.png)

I did not come across such scenarios in our table. But it existed on the client's end.
![image](https://user-images.githubusercontent.com/43877959/78630339-1a12a800-78b7-11ea-96de-bd09471f5fe5.png)

**Comment by dattaprasad-ekavade** [comment]
![image](https://user-images.githubusercontent.com/48904574/78747806-f2d7db80-7987-11ea-8e85-f5a5f8b16c74.png)
The amount is picked up as Year of the Date, so the Date prompt doesn't come up

**Comment by dattaprasad-ekavade** [comment]
@nutank is this issue fixed on #263?
As this seems to be a similar case. 
`Expenses with Due Date are displaying Dates, but not with Payment Date.`

**Comment by nutank** [comment]
Yes #263 should display the dates in the list view. Not happening on our server since that fix is only on our server.

With regards to 4 digit number being picked up as year (ideally for 4 digit number dialogflow detects it as the year, hence it does not ask for date) - Should we handle this?

**Comment by nutank** [comment]
@dattaprasad-ekavade - handle this by checking word before the number. Check only when you have one number identified. And the same number has been allocated to amount and date year.

word before number is "in" => it is a year and you nullify amount
else => it is an amount and you nullify date.

**Comment by nutank** [comment]
Seems fixed. Will let you know once on client server.
