### ISSUE TITLE
BUG - Expense getting created in client server when I add expense to my Sandbox

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#366]
Some of the expenses are being added to the client-server. These are the expenses that are not getting added to our server at the time of creation.

Noticed that mostly it was entries that had a due date in the past
In the below example
![image](https://user-images.githubusercontent.com/43877959/78630473-707fe680-78b7-11ea-9108-96788db0eb4f.png)

7918 was added to client-server (however, on click of the entry, it was showing a blank screen)
![image](https://user-images.githubusercontent.com/43877959/78630579-bccb2680-78b7-11ea-8f5a-eaf4b5ae2db1.png)

7922 was added to our server
![image](https://user-images.githubusercontent.com/43877959/78630523-91483c00-78b7-11ea-8690-68465f7adda2.png)

**Comment by dattaprasad-ekavade** [comment]
Got Both the Entries in the database
![image](https://user-images.githubusercontent.com/48904574/78777859-ee2b1b80-79b7-11ea-9d86-192890b4d97b.png)
And they both have identical values in them, except the date.

Both are Paid Expenses, but 7918 have a future date for Expense paid date. 

that's why the UI fails to show the entry.

**Comment by nutank** [comment]
@georgioajency - the payment status is decided from the tense of the sentence.

Above. sentence is paid hence date assumed to be payment date. However payment date cannot be future date in our UI hence the issue. Should we decide the payment status basis the tense or basis the date.

**Comment by georgioajency** [comment]
@nutank Payment status should be on the tense.

Unpaid or Paid. I should be able to add both in the past and future. This was the requirement from Aditya.

**Comment by dattaprasad-ekavade** [comment]
Tested the expenses now. 
Both the cases worked properly.

**Comment by HazelColaco19** [comment]
Created expenses in both cases,  none appeared on the Client URL. However some created expense were not shown in the UI of our QA side ( Ajency URL ) of the website. A separate issue is logged to track the same. #531   Will close this issue. @georgioajency
