### ISSUE TITLE
BUG - Due date not matching entry date in QB

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#367]
Due date in WA shows as 31st but in the list it showed as 1st
![image](https://user-images.githubusercontent.com/43877959/78630799-3f53e600-78b8-11ea-9d07-51295493800e.png)

ID: 7916

![image](https://user-images.githubusercontent.com/43877959/78630842-5b578780-78b8-11ea-90aa-67d8673ef4bb.png)

**Comment by dattaprasad-ekavade** [comment]
Entry in Database from Whatsapp Chatbot:
![image](https://user-images.githubusercontent.com/48904574/78672447-456cb580-78fe-11ea-94a9-9ca5a0619903.png)

How Whatsapp bot handles "Last Year" case (Current Date = 07-04-2020):
```
Dialogflow returns Time-Period of 1st Jan 2019 00:00:00 to 31st Dec 2019 23:59:59
Whatsapp bot picks End date of the same. 
So, date =  31st Dec 2019 23:59:59

WA Shows 31st Dec 2019.

Once it goes in DB, Possibly:

1. the QB adds +5.30 to it (Adjusting to Timezone) 

OR 

2. Interprets the date as 1st January 2020.

```

**Comment by nutank** [comment]
@dattaprasad-ekavade after receiving the date from dialogflow please convert to UTC before sending to API.

**Comment by georgioajency** [comment]
@dattaprasad-ekavade @nutank 

I have been struggling to create an expense. Keeps on throwing me this error.

Are we blocking users from creating unpaid expenses in the past?

![image](https://user-images.githubusercontent.com/43877959/79149307-94c25280-7de4-11ea-9da5-bc502778f963.png)

**Comment by dattaprasad-ekavade** [comment]
Removed the code blocking the users from creating unpaid expenses in the past. Now the expense is created properly, it is still not shown in UI. 
![image](https://user-images.githubusercontent.com/48904574/79305524-2e871e00-7f11-11ea-9fa9-908e60731908.png)
The entries were there in DB at the time of checking, but the value was not being shown on UI.
One difference noticed was that the expense created didn't have was qb_category_id.

Could this be the reason for it to not show up on UI?

**Comment by HazelColaco19** [comment]
Works fine when the due date is in the same year. Can be verified.

However when the due date/ purchase date was last year - the expense is not shown in the UI.

Example: db_64742

**Comment by HazelColaco19** [comment]
Tested with db_65554. looks fixed. Closing the issue.


![image](https://user-images.githubusercontent.com/55691499/80102525-7ac90280-8590-11ea-9277-b68379640c2b.png)
