### ISSUE TITLE
BUG - 1 month ago directly puts the last date of the previous month

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#368]
It should take exact date, one month back. Ex today is 7 Apr so 1 month ago would be 7 Mar

![image](https://user-images.githubusercontent.com/43877959/78630941-95c12480-78b8-11ea-977d-1fbcbb3e9e60.png)

**Comment by nutank** [comment]
@dattaprasad-ekavade let me know what response is sent by dialogflow for:
1. 1 week ago
2. 1 month ago
3. 1 day ago

Lets decide what needs to be done post that

**Comment by HazelColaco19** [comment]
Tested for three scenarios mentioned by @nutank above. Looks fixed.

- 1 week ago
- 1 month ago
- 1 day ago

![image](https://user-images.githubusercontent.com/55691499/79746794-34716a80-8328-11ea-928f-5be2396c4c7e.png)
