### ISSUE TITLE
BUG - Category should be Sentence case. Start with capital

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#369]
ID 7930

It should have been Office Expenses

![image](https://user-images.githubusercontent.com/43877959/78631038-d9b42980-78b8-11ea-8834-1f10bbbef43d.png)

**Comment by dattaprasad-ekavade** [comment]
Fixed with solution from #359

**Comment by nutank** [comment]
@dattaprasad-ekavade - before displaying, pass it through a method that converts that category string to came case.

**Comment by georgioajency** [comment]
@nutank Tested. No issues.

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/79221591-b7e81300-7e73-11ea-9406-1fc27ce9526c.png)

Here others is small
