### ISSUE TITLE
Closing data is not updating in db for company 2 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#371]
Quickbook - company 2
![image](https://user-images.githubusercontent.com/45193277/78641226-8a78f380-78ce-11ea-928b-82b47c9fbfc0.png)

DB 

![image](https://user-images.githubusercontent.com/45193277/78641447-e04d9b80-78ce-11ea-9e27-e598b2c1ffaf.png)

**Comment by nutank** [comment]
This is not updating for company 8 as well.

**Comment by TejalBandekar** [comment]
Fixed.
