### ISSUE TITLE
Multiple records for the same category is being generated when creating a csv basis the projection id is 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#372]
Steps: 
1. Hit the below endpoint 
https://ajency-qa.api.toppeq.com/createCsv?projectionId=6577

**Expected Result:** A csv should be generated with all the categories basis the projection id a company belongs to.

**Actual Result:** Multiple records are generated for the same category 

![image](https://user-images.githubusercontent.com/45193277/78658763-3b3fbc80-78e8-11ea-9ee5-30a9aeecd674.png)

**Comment by nutank** [comment]
@jessica-cardozo1 - This should be the category's fully qualified name

**Comment by TejalBandekar** [comment]
Fixed.
