### ISSUE TITLE
Incurred expenses/Planned expenses (Issues & Suggestions):  Accounting Category Filter is not working properly - Accounts Payable shows items categorized under salary payable

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#375]
**Links to test the issue**

a. https://ajency-qa.toppeq.com/cashflow/outflow/incurred
b. https://client-uat.toppeq.com/cashflow/outflow/incurred

**Steps to Test:**

1. Choose ' Accounts Payable ' as the category
2. Current behavior on client UAT link: The filter result is accounting category " Accounts Payable "

![image](https://user-images.githubusercontent.com/55691499/78667155-12262880-78f6-11ea-85ce-20edb886c3c8.png)

3. Current behavior on Ajency link: The filter result is null

![image](https://user-images.githubusercontent.com/55691499/78667315-5b767800-78f6-11ea-9108-79b95ea7b9ab.png)

**Findings:**

In both cases, there were no entries that showed up with " salary payable " category

**Comment by georgioajency** [comment]
Checked. No issue
