### ISSUE TITLE
Incurred expenses/Planned expenses (Issues & Suggestions): Payment status not working properly - No filter for items with transactions marked as -

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#376]
**Links to test the issue**

a. https://ajency-qa.toppeq.com/cashflow/outflow/incurred
b. https://client-uat.toppeq.com/cashflow/outflow/incurred

**Steps to Test:**

1. Go to the link and check the list of filter " Payment Status "
2. Now keep applying the three items in the filter and see the results that populate in the column.

_Current Behavior:_
3. You will notice that the record with PAYMENT STATUS as " - " do not show up during the application of PAYMENT STATUS filter.

![image](https://user-images.githubusercontent.com/55691499/78668509-6e8a4780-78f8-11ea-89af-6f67eca235dd.png)

![image](https://user-images.githubusercontent.com/55691499/78668486-68946680-78f8-11ea-91dc-179d62fd96ae.png)

**Expected Behavior:**

Have an ability to filter the records which do not have a " Paid ", " Pending ", " Unpaid " status.

**Comment by georgioajency** [comment]
Will be kept on hold until further clarification.
