### ISSUE TITLE
Incurred expenses/Planned expenses (Issues & Suggestions): Accounting drop down - Filters are missing - Filter for Human Resources was not available under Account Categories

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#377]
**Links to test the issue**

a. https://ajency-qa.toppeq.com/cashflow/outflow/incurred
b. https://client-uat.toppeq.com/cashflow/outflow/incurred

**Steps to Test:**

1. List all the Accounting Category.
2. Compare the distinctive items from this list with the values in the dropdown ( Filter )

**Actual Result**

The distinctive values in the ACCOUNTING CATEGORY columns are all present in the filter dropdown

**Additional check on UAT server:**

Test for statement - Filter for Human Resources was not available under Account Categories
There is no category currently available with the name " Human Resources ". So no point checking it in the filter as well.

**Comment by georgioajency** [comment]
Checked.
