### ISSUE TITLE
Incurred expenses/Planned expenses (Issues & Suggestions): Custom value. Should not be able to support adding a Higher to lower amount. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#381]
**Links to test the issue**

a. https://ajency-qa.toppeq.com/cashflow/outflow/incurred
b. https://client-uat.toppeq.com/cashflow/outflow/incurred

**Steps to Test:**

1.  Under Filters for Amount, click on CUSTOM
_2. Current Behavior:_

Add From Value = 5000
Add To Value = 100

The values are taken in and no error is thrown for entering a range of Higher to lower amount.

![image](https://user-images.githubusercontent.com/55691499/78679453-dc8a3b00-7907-11ea-8c0f-d267e7d7039a.png)

**Expected Result:**

Should not be able to support adding a Higher to lower amount. 

_Suggestion:_  @georgioajency Please decide

1. When an amount is entered in the fields have an error message in place which says something on the lines of " Higher amount to lower amount values not accepted "
OR
2. Have a button with text " Apply ", and the range will be applied only on click of this button
- Also add a validation check on click of Apply which throws same error as above if the values entered in the " TO " field are lesser than those in " From " field

**Comment by georgioajency** [comment]
Since it is dynamic, I would not change the implementation.
We can show the text "Max Amount cannot be less than Min Amount"

![image](https://user-images.githubusercontent.com/43877959/78708341-9a74ef80-792f-11ea-8c0c-dee694d84aa5.png)

Also, change the labels to "Min Amount" & "Max Amount"
