### ISSUE TITLE
Incurred expenses/Planned expenses (Issues & Suggestions): Certain planned expenses that were added are not showing a date.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#382]
**Links to test the issue**

a. https://ajency-qa.toppeq.com/cashflow/outflow/planned
b. https://client-uat.toppeq.com/cashflow/outflow/planned

**Steps to Test:**

1. Under " Planned Expense" click on " ALL " in the bottom left, and view if any records have no dates attached to them
2. _Current Behavior:_  Some records do not have dates associated with them.

**Expected Behavior:**
All the records should have dates attached to them

**Current Behavior:**
On Ajency server, there was no issue
On Client-server, there were records with no dates

_Client UAT server:_ 
![image](https://user-images.githubusercontent.com/43877959/78708613-09524880-7930-11ea-9062-e9295245f732.png)

**Comment by georgioajency** [comment]
Noticed that some of these records were created when I created an expense on WhatsApp bot. 
The expense was created on Ajency sandbox however the record appeared on the client-server.
Most of these records were created with a due date set in the past.
