### ISSUE TITLE
New sub categories created in quickbook for company 2 doesn't show in the forecast template when it is present in quickbook account category table

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#387]
Projection id - 13021

**Quickbook** 

![image](https://user-images.githubusercontent.com/45193277/78744338-eb600480-797e-11ea-9144-bef52088728e.png)

**DB** 

![image](https://user-images.githubusercontent.com/45193277/78744295-d6837100-797e-11ea-83e0-3bc83aff6cca.png)

**Expected Result:** Newly added sub categories created in quickbook should show up in the forecast template as per the tree structure.

**Comment by robiulpro** [comment]
@TejalBandekar 
make sure there is records for the category in past cashflow table

**Comment by TejalBandekar** [comment]
@legred21 Please make the mapping of the child category to the parents db id and not to qb_category_id as discussed with @robiulpro

**Comment by TejalBandekar** [comment]
Fixed.
