### ISSUE TITLE
Any rule applied in combination with other rules is giving incorrect data exxcept for custom rule

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#389]
![image](https://user-images.githubusercontent.com/45193277/78760708-2eca6b00-799f-11ea-8579-1d9d9a871909.png)

Example: 

May june - it is compounding rule 
and July- dec - Fixed in incease value by 50. 

Ideally, July should have been 
10% of the previous value + Previous Value + 50

**Comment by robiulpro** [comment]
Fixed

**Comment by TejalBandekar** [comment]
Fixed.
