### ISSUE TITLE
On click of back of a confirmation pop up, the value entered previously when applying of a rule doesn't get displayed

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#393]
Steps: 

1. Click on the Total of a category cell and enter simple increase 10% to it 
2. Click on apply. 
3. Next step, confirmation pop up is being displayed. Click on back. 

![image](https://user-images.githubusercontent.com/45193277/78775427-d05bb780-79b3-11ea-9a45-f22989ee8a36.png)

Expected: A value entered previously when applying of a rule should be displayed

Actual: A value entered previously when applying of a rule is not displayed.

**Comment by georgioajency** [comment]
Tested
