### ISSUE TITLE
Opening/Closing Cash balance Value cannot go negative. If it does, it should tell the user to rebalance. 

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#395]
![image](https://user-images.githubusercontent.com/43877959/79305199-90935380-7f10-11ea-929f-2e204c47b8ee.png)

The following things will have to be handled.
1. If the opening cash balance value goes negative, the cell will show an issue.
2. This cell is clickable and will show the message as per the image above. The message will show by how much is the opening cash balance negative
3. The recurring opening cash balance cells will show a red dash. (Not clickable)
4. The same logic will be on the closing cash balance. 

**Ex. if in Apr 2020 the closing cash balance goes negative, then the above logic will be applicable to this cell and the Opening cash balance cell of May 2020.**

Need to confirm if there will be an impact on graphs

Also as discussed with Aditya, if the same happens in the past section then the amount values needs to be shown in red

**Comment by georgioajency** [comment]
There are requirement changes. Please keep this task on hold for now.

**Comment by georgioajency** [comment]
@verlekar-viraj Also we need to handle if the past opening/closing cash values are negative. If that's the case, we show the text in Red.

![image](https://user-images.githubusercontent.com/43877959/79954890-a4543200-849b-11ea-96e1-4f5830937238.png)

https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=2489%3A814

**Comment by HazelColaco19** [comment]
1. Works for past forecasted data values if cash outflow is higher than inflow
Design issues raised in #548

2. Works for past data values if cash outflow is higher than inflow
![image](https://user-images.githubusercontent.com/55691499/80205354-15384d00-8648-11ea-86b6-28d025e4d1fc.png)


Requirement that is not tested for:

3. The recurring opening cash balance cells will show a red dash. (Not clickable)
4. The same logic will be on the closing cash balance.

@georgioajency Please confirm on the requirement from client as mentioned earlier

**Comment by georgioajency** [comment]
Approved by client
