### ISSUE TITLE
BUG - If applying a total level rule over the prexisting rule, the values of the first child get copied to all the remaining child items

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#401]
First I put simple increase of 5% on this forecast at the total level
![image](https://user-images.githubusercontent.com/43877959/78783891-f9834480-79c1-11ea-9cf8-773d86c93cf7.png)

Then I went to the next month and changed the rule at the total level 
![image](https://user-images.githubusercontent.com/43877959/78783999-2d5e6a00-79c2-11ea-9b07-ef7f858ab951.png)

All the values of the first child got repeated
![image](https://user-images.githubusercontent.com/43877959/78784041-42d39400-79c2-11ea-8bab-7a75f36f4e57.png)

**Comment by TejalBandekar** [comment]
Fixed.
