### ISSUE TITLE
BUG - Custom Value forecast rule throws an error 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#404]
https://www.loom.com/share/a7a1972a246145f8b5f11328cb3df258

![image](https://user-images.githubusercontent.com/45193277/78787289-c348c380-79c7-11ea-8ec9-061be0b2f6d3.png)

**Comment by robiulpro** [comment]
fixed

**Comment by TejalBandekar** [comment]
Fixed.
