### ISSUE TITLE
TASK - List of Projections API to return projections in alphabetical order (sort_on, sort_by)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#420]
Optional request parameters for sot_on and sort_by to be accepted. 

When not passed default values to sort_on = "name" , sort_by = "ASC"

**Comment by nutank** [comment]
To be Handled - isSelectedFlag = true/ false for the projections from the list.

This flag would be set basis one of the following:
1. Last selected projection
2. Last Updated 

Need Clarity from @georgioajency

**Comment by georgioajency** [comment]
@nutank Keep it last selected projection

**Comment by georgioajency** [comment]
@nutank The projection selected will get impacted sitewide. 
i.e if I select "Projection xyz" in the forecast template, then when I go to the Projection Dashboard, the projection selected there will be the same "Projection xyz"
The same is vice-versa. A projection selected on the dashboard, the same will be selected when I go to the forecasted template page.

**Comment by nutank** [comment]
@robiulpro / @verlekar-viraj - need to introduce a isSelected attribute against a single projection

@verlekar-viraj - this isSelected flag needs to be updated every time a projection scenario is selected in Forecast template page or in Projection dashboard page. Essentially making the isSelected flag consistent site-wide.

This involves making changes in : https://docs.google.com/document/d/15aF0DNq9KsPCmAbfS0Th-cRnF0XgP8cKpXmmwv0vj_Y/edit?ts=5e61f346#heading=h.rg5lmoihlkt5 

1. list of projections API
2. Update single projection API

**Comment by robiulpro** [comment]
backend part is done.

**Comment by georgioajency** [comment]
Tested. No issues
