### ISSUE TITLE
Qb accounting category field has to be shown up when viewing or editing of  an expense

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#421]
![image](https://user-images.githubusercontent.com/45193277/78982050-e944a400-7b3e-11ea-9853-2ab5fbfda9c4.png)

**Comment by TejalBandekar** [comment]
@georgioajency Your thoughts on this please?

**Comment by georgioajency** [comment]
Yes, if it has a value, it should show up. I should be able to edit it also.

**Comment by robiulpro** [comment]
done

**Comment by georgioajency** [comment]
Does office expenses have QB categories under it? Cause nothing is showing up.
![image](https://user-images.githubusercontent.com/43877959/79823473-8a3e2500-83b1-11ea-802f-aa031fdede27.png)
![image](https://user-images.githubusercontent.com/43877959/79823487-91fdc980-83b1-11ea-8bde-e6c9acd84f0c.png)

**Comment by robiulpro** [comment]
@georgioajency 
all accounting head doesnt have qb category mapping in db. best i can do is hide the dropdown if there is no qb category mapping.

**Comment by nutank** [comment]
@nutank - please check DB mapping for this one.

**Comment by nutank** [comment]
This is not an issue. Occurred since toppeq header mapping table does not have a QB detail type mapping for this. Ideally this should not happen once #574 #557 is done
