### ISSUE TITLE
Projection dashboard > Cashflow & Burnrate graph : The legends are visible even if the data is not available ( or graph does not include these values )

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#425]
**Current Behavior:**

The Legends for bar graph whose data is null or cannot be visually seen in the graph are seen below.

![image](https://user-images.githubusercontent.com/55691499/78986869-ec915d00-7b49-11ea-8e07-1c3d683d3536.png)

**Expected**

The Legends for bar graph whose data is null or cannot be visually seen in the graph should also be hidden

**Comment by HazelColaco19** [comment]
Issue still exists.


![image](https://user-images.githubusercontent.com/55691499/81038093-8981b480-8ec2-11ea-9226-c91720d05714.png)

**Comment by georgioajency** [comment]
I think this is fine, considering we are showing the projection region and the legend kinda indicates that there if you add data, it will show up.

Unless the client specifically brings up this use case, I am closing this issue.
