### ISSUE TITLE
Cashflow Metrics -  if u open the pop up and drag upwards by holding on the pop up the mask drags as well

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#427]
**Current Behavior:**

 if u open the pop up and drag upwards by holding on the pop up the mask drags as well

![image](https://user-images.githubusercontent.com/55691499/78996642-a7c5f000-7b62-11ea-83ef-63120c512ac7.png)

**Expected:**

The overlay should not drag if the click is on the pop up.

**Comment by HazelColaco19** [comment]
Not fixed.

![image](https://user-images.githubusercontent.com/55691499/81041735-29900b80-8ecc-11ea-9992-4ca11a9a982b.png)

**Comment by Vaibhavarolkar** [comment]
Issue caused because of top browser bar as u scroll the bar gets hidden, 
this is default behaviour for mobile browser and cannot be handled.

**Comment by HazelColaco19** [comment]
Closing the ticket if it is the browser behavior and cannot be handled.
