### ISSUE TITLE
Projection Dashboard > The values for closing cash balance in Forecasted template does not match the graph  for future months

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#428]
**Current Behavior:**

The values for closing cash balance in Forecasted template does not match the graph  for future months

![image](https://user-images.githubusercontent.com/55691499/79000278-f32fcc80-7b69-11ea-872d-e2624047d71f.png)

**Expected:**

The values for closing cash balance in Forecasted template should match the graph  for future months

**Comment by georgioajency** [comment]
Seems like the Net cash was not getting calculated.

The issue seems fixed. @HazelColaco19 please verify

**Comment by HazelColaco19** [comment]
Not Fixed. @legred21 @georgioajency 

![image](https://user-images.githubusercontent.com/55691499/79340611-2dbdae80-7f48-11ea-8149-9da8daab21fa.png)

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/79557805-d262fc00-80c0-11ea-9f75-63f115646de3.png)
![image](https://user-images.githubusercontent.com/55079454/79557882-f9213280-80c0-11ea-8737-5a6c8b968f33.png)
![image](https://user-images.githubusercontent.com/55079454/79558001-25d54a00-80c1-11ea-9d05-326c313cd52d.png)

**Comment by legred21** [comment]
26008 | OUTFLOW | OPERATING | Interest on Term Loan | 60 | 0 | 3475849 | MONTHLY | 2020-05-01 0:00:00

**Comment by robiulpro** [comment]
The corresponding past cashflow entry is missing. You should join with past cashflow while making query to make sure the past entry exists.

**Comment by legred21** [comment]
below Entry not considered in forecast template is deleted
26008 | OUTFLOW | OPERATING | Interest on Term Loan | 60 | 0 | 3475849 | MONTHLY | 2020-05-01 0:00:00

**Comment by georgioajency** [comment]
Tested
