### ISSUE TITLE
Projection Dashboard Improvements - UAT

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#429]
1, 3, 4, 5, 7 has been verified at my end. 

```
7. The input field size should increase if more than 4 characters are entered

![image](https://user-images.githubusercontent.com/45193277/78134946-9bdd7e00-743e-11ea-8f9b-27bd152b8f55.png)
```

> Can't increase the size based on input value. Have increased the input size for now to fit 5 digits properly.

@georgioajency Please let us know your thoughts on this.

Below issues/improvements  cannot be handled at UI end and has to be handled at react end. 
@verlekar-viraj / @robiulpro 

1. 2. Sort the list of created projections from A-Z

![image](https://user-images.githubusercontent.com/45193277/78134032-1a392080-743d-11ea-873e-28c14e7d0eb5.png)

2. 5. Keep upto 2 decimal places

![image](https://user-images.githubusercontent.com/45193277/78134199-5f5d5280-743d-11ea-89dc-32ce48b5ed84.png)

_Originally posted by @TejalBandekar in https://github.com/ajency/cashflow-issue-tracker/issues/314#issuecomment-607780078_

**Comment by georgioajency** [comment]
@nutank no decimal needs to be kept

**Comment by nutank** [comment]
@HazelColaco19 is this still valid?

**Comment by HazelColaco19** [comment]
1. The list isnt sorted alphabetically 

![image](https://user-images.githubusercontent.com/55691499/83718897-9295ab00-a653-11ea-9a49-123eaea14339.png)


2. Looks fixed. Tested for the case given in screenshot

![image](https://user-images.githubusercontent.com/55691499/83719051-e607f900-a653-11ea-9b00-5a962483fa5e.png)
