### ISSUE TITLE
TASK - Get the synced values right for each accounting category in Cash in and Cash Out

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#430]

**Comment by georgioajency** [comment]
**Checked for Jan 2020**
https://ajency-qa.toppeq.com/cashflow/projection/38924/edit

Below entries showing up in the projection template. These entries are extra and should not be showing up. Checked KIbana and these entries are not there.
Interest and Term loan - 9000
Salary Payable - 13000
Depreciation - 1272
Plant & Machinery - 1272

Entries not showing up in projection template
Accounts Payable/Cost of goods sold - 9516

**Comment by georgioajency** [comment]
Tested. Working
