### ISSUE TITLE
TASK - Update of past values and corresponding future values in Forecast Template

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#431]

**Comment by nutank** [comment]
@georgioajency - please provide the UI for this flow.

**Comment by georgioajency** [comment]
There are two steps to this
1. Introduce a button to sync the data to the latest QB data
2. On click on the button, a verification pop up will appear. 

Step 1
<UI needs to be verified>

Step 2
In this verification pop up, the user has an option to either update or not the values of the forecast template
![image](https://user-images.githubusercontent.com/43877959/79091291-5b4d0100-7d6a-11ea-907f-1247a4d0cc01.png)

https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=2438%3A308

**Comment by georgioajency** [comment]
Tested. Found bugs and reported them seperately.

Closing the issue as the feature has been built.
