### ISSUE TITLE
TASK - Planned vs Actual graphs 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#432]
Planned vs Actual (3 graphs)
*Note: This will include 2 additional graphs to the list. Cash In, Cash Out & Net (Cash In - Cash Out)

Formula: Planned Cash In vs Planned Cash Out

Graph: Same as Cash In vs Cash-Out graph. 
Also, the graph will only show up if at least one month has both planned and actual expenses.

There will also be a filter to filter the graphs by Operating, Investing, Financing, All. 

**If no. of months are 4 or less than show all graphs in one row**
![image](https://user-images.githubusercontent.com/43877959/79306537-04cef680-7f13-11ea-968e-039abbfb158f.png)

**If no of months is more than 5 than show graphs one below the other**
![image](https://user-images.githubusercontent.com/43877959/79306539-07c9e700-7f13-11ea-8678-a847b467e946.png)

**Comment by nutank** [comment]
Please notes:

- Will appear in Projection Dashboard page
- Assume filter of "all" by default when no filter is explicitly passed.
- For actual data - query the future months of projection from "cashflow" table
- For planned data - query projected_amount for the future months of projection from "future_cashflow" table
-  "plannedActualGraphFilters": {
     activityType: [“operating”, “investing”, “financing”, “all”]
    }

**Comment by nutank** [comment]
- query from cashflow_table and future_cashflow only hose months of the future that are in the  past as compared to date.

**Comment by legred21** [comment]
Query cashflow for actual data and future_cashflow for planned data

**Comment by georgioajency** [comment]
Tested the data. No issues
Graph issues reported seperately
