### ISSUE TITLE
TASK - Cashflow metrics - Introduce a date picker

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#433]
Graphs dependent on date picker will be affected by it.

**Comment by georgioajency** [comment]
Spoke to Aditya. 

They are planning of introducing additional sections which will change how the graphs will look on the site. We should not include the date picker for now and only pick it up once we have more clarity on the page.

**Comment by georgioajency** [comment]
The following graphs on this page will be affected

1. Cash Inflow by Category
2. Cash Outflow by Category
3. Average Days to Collect From Customers
4. Average Days to Pay Vendors

The other remaining graphs in the Cashflow metrics page will move towards the Key Metrics page that will be built.

**Comment by robiulpro** [comment]
Completed

**Comment by georgioajency** [comment]
Date picker implemented. 

Please refer to #524 

Same UI changes there has to be implemented here.

**Comment by georgioajency** [comment]
Tested
