### ISSUE TITLE
TASK - Values under graphs and projections should not display in decimals. 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#435]

**Comment by georgioajency** [comment]
@nutank 
Here the value should not be rounded up but the decimal values should be hidden. This is a UI task

**By legend I mean the info window that comes up on the graph on hover**

![image](https://user-images.githubusercontent.com/43877959/79302382-d993d980-7f09-11ea-9581-d136a0e3c179.png)

![image](https://user-images.githubusercontent.com/43877959/79302721-c6cdd480-7f0a-11ea-9a87-3320783ba32d.png)

![image](https://user-images.githubusercontent.com/43877959/79302843-1a402280-7f0b-11ea-9b07-4b4f41df9b03.png)

**Comment by georgioajency** [comment]
No issues
