### ISSUE TITLE
TASK - Key metrics Dashboard

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#442]
Move graphs/ charts to common metrics page as per the image here - https://ajency-qa.toppeq.com/cashflow/keymetrics

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/79380803-96c01900-7f7e-11ea-9f55-0645d76ee455.png)

For the dropdowns keep it consistent by using what we have used. I do not want to rebuild new UI components.

**Comment by nutank** [comment]
@georgioajency - provide list of ratio analysis predefined date periods.

**Comment by georgioajency** [comment]
This will include the following

This month
Last month
This quarter
Last quarter
This year
Custom

**Comment by robiulpro** [comment]
completed

**Comment by georgioajency** [comment]
Checked. 

UI issues: #524 
Bugs: #533
