### ISSUE TITLE
Cashflow Metrics > Quick Ratio and Working Capital ratio: UI Issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#443]
**Current behavior:**

_For Quick Ratio and Working Capital ratio_

1. The semi circular graph does not start at the same point as shown in design.
2. " Ideal Range " text should be increased by 1 point

![image](https://user-images.githubusercontent.com/55691499/79104946-3ddd5e80-7d8d-11ea-989e-a4d0e9cf1d2b.png)

3. Number does not include decimal place if it is a round figure
![image](https://user-images.githubusercontent.com/55691499/79105457-50a46300-7d8e-11ea-90b4-71f8bd7140f5.png)

**Expected Behavior:**

Follow design

**Comment by georgioajency** [comment]
Ignore point 1
Ignore point 2
It doesn't have to be so accurate. These things will change based on screen size.

Point 3. Include up to one decimal spot for the exact value. To maintain consistency show it as 1.0

**Comment by nutank** [comment]
Closing this issue. Only open task tracked in #582
