### ISSUE TITLE
Cashflow Metrics > Quick Ratio and Working Capital ratio: UI Issues on mobile

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#444]
**Current behavior:**

1. Scroll to Cashflow Metrics ( Analysis ) screen. scroll down to  " Quick Ratio and Working Capital ratio " section.

2. Then click on the menu as highlighted in pic you will notice the semicircles appear over the menu listing.

![image](https://user-images.githubusercontent.com/55691499/79116549-6d4c9500-7da6-11ea-8060-900b863fbb12.png)

**Expected Behavior:**

The menu listing should hide the graphs if it is currently active

**Comment by georgioajency** [comment]
Tested this out. No issues
Assuming these changes are pushed.

@HazelColaco19 Please verify once.
