### ISSUE TITLE
BUG - Update text for the top upcoming expenses/income

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#446]
And the titles of the graph should be
**1. Top 3 upcoming expenses (May 2020)
2. Top 3 upcoming income (May 2020)** 
*Where May 2020 is dynamic as per the month

3. Also if there are no entries, show the below text
**"This projection has no forecast amounts"**

![image](https://user-images.githubusercontent.com/43877959/79153408-6c8a2200-7deb-11ea-84bc-c0b2afbd0c03.png)

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/79352579-abd58180-7f57-11ea-87fa-d57541592034.png)

Empty states not handled.

If there is no data, the month should still show the next month and not ()

Point 3, not handled

**Comment by nutank** [comment]
As discussed, lets hide when no data comes in.

**Comment by nutank** [comment]
@Vaibhavarolkar - to handle the message text styling

@verlekar-viraj - to handle display of immediate next month basis "projectionCurrentDate" sent in the API.

**Comment by legred21** [comment]
projectionCurrentDate is now sent in response

**Comment by georgioajency** [comment]
The text has to be center-aligned in the box

![image](https://user-images.githubusercontent.com/43877959/79572259-43fb7400-80da-11ea-8bdc-440e0a773dc2.png)

**Comment by georgioajency** [comment]
Tested
