### ISSUE TITLE
BUG - Please delete these values from DB/Elastic

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#460]
@nutank these values got created while I was testing. Can you please delete them. I would prefer if these values were not displayed during the demo.

![image](https://user-images.githubusercontent.com/43877959/79331294-90a74980-7f38-11ea-97f4-a630fbc81fbd.png)

**Comment by nutank** [comment]
@georgioajency - i have done this. Please verify and close the ticket.
