### ISSUE TITLE
BUG - Owner's Equity not showing up when CSV generated

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#461]
https://docs.google.com/spreadsheets/d/1zZIZHHztv-KYcn2r1KADM7vE4EuF3q_a/edit#gid=1972149408

Line 73

There is an entry in QB for this, however, in the CSV sample downloaded, this value is not available.

**Comment by jessica-cardozo1** [comment]
Mapping for toppeq_category_detail_type was missing in db. I've added the mapping. The categories mapped to qb category detail type Owners Equity (Owner's Investment, Owner's Pay & Personal Expenses) now appear in the sheet when downloaded.

**Comment by georgioajency** [comment]
Tested
