### ISSUE TITLE
BUG - Graphs are loading blank. Also when you select a projection, some just copy values of another projection

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#463]
Issue 1
On login, went to the cashflow section. The Projection dashboard loaded with blank data
https://ajency-qa.toppeq.com/cashflow/dashboard
Current demo selected **1st demo**
![image](https://user-images.githubusercontent.com/43877959/79377857-f9fb7c80-7f79-11ea-8f3e-00a243c39edd.png)

Issue 2
Now I go and select any other projection (**April 10**). The graphs loads. And now I go and select the **1st demo** projection. The graphs load the same projection as that of April 10
![image](https://user-images.githubusercontent.com/43877959/79378159-768e5b00-7f7a-11ea-9134-0be16e5a339f.png)

![image](https://user-images.githubusercontent.com/43877959/79378199-8ad25800-7f7a-11ea-97ba-5d4ff5519f4c.png)

**Comment by nutank** [comment]
@legred API for charting API giving internal server error.

However no significant exception thrown in Kibana

Please check.

**Comment by legred21** [comment]
Issue existed in fetching data from database. Outflow data was empty for month of april and therefore was causing an exception while fetching data from db

**Comment by georgioajency** [comment]
Tested
