### ISSUE TITLE
BUG - Projection months not matching the months displayed on the graph

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#464]
Projection selected **April 10**

Actual projection period
![image](https://user-images.githubusercontent.com/43877959/79378392-e0a70000-7f7a-11ea-9bc5-860aafe5d6f5.png)

Projection dashboard selection
![image](https://user-images.githubusercontent.com/43877959/79378480-07653680-7f7b-11ea-8a46-e80fd14a59de.png)

**Comment by nutank** [comment]
@georgioajency - should this match projection forecast template duration?

**Comment by georgioajency** [comment]
Yes it should match.

**Comment by nutank** [comment]
@legred21 - pass "projectionStartDate" and "projectionEndDate"

**Comment by georgioajency** [comment]
@verlekar-viraj issue still persists. The graphs are showing an extra month to the projection

**Comment by verlekar-viraj** [comment]
UI showing What months are passed in API
@legred

**Comment by legred21** [comment]
UTC conversion of time fixed the issue

**Comment by georgioajency** [comment]
Tested
