### ISSUE TITLE
BUG - Quickbook closing cash balance for the month of April 2020 is incorrect. Has to be 94,505.68

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#465]
![image](https://user-images.githubusercontent.com/43877959/79378598-3aa7c580-7f7b-11ea-9f29-06f818a548c6.png)

Also, some of the values in between are 0
![image](https://user-images.githubusercontent.com/43877959/79378986-cfaabe80-7f7b-11ea-9c4c-80602b6b7696.png)

These 0 values are causing the closing cash balance to go wrong if the projection had started in the month of Apr 2019 (as Mar 2019 closing balance is 0)

**Comment by nutank** [comment]
@robiulpro - the logic for this should be end of month cash balance or for current months it should be the closing cash balance as of current day. If for whatever reason we dont find current day, probably pick current day - 1.

In the above case, however not sure which value is picked.

The company_cash table doesnt seem to have value for 14th April or 15th April when we tried yesterday. 

Even when i ran the api explicitly for the whole month of april, it did not seem to populate - https://ajency-qa.api.toppeq.com/rest/api/updateCompanyCashData?company_id=8&start_date=2020-04-01&end_date=2020-04-15

Also please note, there was no entry in flat_sync_tracker table for dates after 13th April.

**Comment by robiulpro** [comment]
Fixed

**Comment by georgioajency** [comment]
Issue still persists on the cashflow template

**Comment by robiulpro** [comment]
Fixed

**Comment by georgioajency** [comment]
Tested
