### ISSUE TITLE
BUG - QB Category Name does not reflect for " Investment in Securities "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#471]
**Current behavior:** 

Can view only two QB Category labels for " Investing Cash Outflow " Type. See below for details from DB. Zoom in the picture for clearer view

![image](https://user-images.githubusercontent.com/55691499/79432658-c1938700-7fe9-11ea-853a-9be54e78289c.png)

**Comment by legred21** [comment]
"Other long-term asset" and "Other Long Term Asset" are two different strings in database and hence does not show up in list

**Comment by legred21** [comment]
Please update the db entries

**Comment by georgioajency** [comment]
@nutank should this be tested, closed or is there anything else that needs to be done here.

**Comment by HazelColaco19** [comment]
Associated. Seen fixed, Can be cllosed

![image](https://user-images.githubusercontent.com/55691499/80365269-ef5bb400-88a4-11ea-85df-5d2151e6539b.png)


![image](https://user-images.githubusercontent.com/55691499/80365158-c2a79c80-88a4-11ea-995f-178ca98f56e0.png)
