### ISSUE TITLE
BUG - Client UAT Link : " Something went wrong " message in the pop up for when clicked on " Enable All"

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#473]
**Steps :**

1. Using https://client-uat.toppeq.com/ go to forecast template
2. Then choose an older scenario and click on " Yes " or " No " in planned expense drop down.
3. Then click on " Enable All " button.

**Current Behavior:**

1.  Client UAT Link : " Something went wrong " message in the pop up for when clicked on " Enable All"

![image](https://user-images.githubusercontent.com/55691499/79462870-bbb39b00-8015-11ea-8866-92e62f17b9ef.png)

**Comment by georgioajency** [comment]
This happened to me once I was testing on our end. Told Viraj, he tried it out and it worked. And then when I tried this out on my end it also started working. 

He said API must have failed for some reason.

@HazelColaco19 if you get this issue again, try it out with the console open to see if you can identify the issue

**Comment by nutank** [comment]
@HazelColaco19 can you replicate this issue on uat still?

**Comment by HazelColaco19** [comment]
@nutank @georgioajency Still replicates for me on UAT link

![image](https://user-images.githubusercontent.com/55691499/79533724-39b78680-8096-11ea-8310-4ebdc0418d2b.png)


_Console records:_

![image](https://user-images.githubusercontent.com/55691499/79533760-5358ce00-8096-11ea-8377-c494afef1f29.png)


_Network Responses:_

![image](https://user-images.githubusercontent.com/55691499/79533814-797e6e00-8096-11ea-8aea-9ae4aa695550.png)

{"data":{"updateProjectionScenario":{"success":true,"message":null,"projectionData":null,"__typename":"UpdateProjectionScenarioResponse"}},"errors":[{"message":"Cannot return null for non-nullable type: 'ID' within parent 'ProjectionData' (/updateProjectionScenario/projectionData/projectionId)","path":["updateProjectionScenario","projectionData","projectionId"],"locations":null,"errorType":"DataFetchingException","extensions":null},{"message":"Cannot return null for non-nullable type: 'Int' within parent 'ProjectionData' (/updateProjectionScenario/projectionData/companyId)","path":["updateProjectionScenario","projectionData","companyId"],"locations":null,"errorType":"DataFetchingException","extensions":null},{"message":"Cannot return null for non-nullable type: 'String' within parent 'ProjectionData' (/updateProjectionScenario/projectionData/projectionName)","path":["updateProjectionScenario","projectionData","projectionName"],"locations":null,"errorType":"DataFetchingException","extensions":null},{"message":"Cannot return null for non-nullable type: 'String' within parent 'ProjectionData' (/updateProjectionScenario/projectionData/projectionCreationDate)","path":["updateProjectionScenario","projectionData","projectionCreationDate"],"locations":null,"errorType":"DataFetchingException","extensions":null},{"message":"Cannot return null for non-nullable type: 'String' within parent 'ProjectionData' (/updateProjectionScenario/projectionData/usePlannedExpense)","path":["updateProjectionScenario","projectionData","usePlannedExpense"],"locations":null,"errorType":"DataFetchingException","extensions":null},{"message":"Cannot return null for non-nullable type: 'String' within parent 'ProjectionData' (/updateProjectionScenario/projectionData/projectionStatus)","path":["updateProjectionScenario","projectionData","projectionStatus"],"locations":null,"errorType":"DataFetchingException","extensions":null}]}


_**Network Header Status:**_

![image](https://user-images.githubusercontent.com/55691499/79533845-97e46980-8096-11ea-84e0-91ed8b1e9082.png)
![image](https://user-images.githubusercontent.com/55691499/79533866-a29efe80-8096-11ea-9a05-104849ae37d5.png)
