### ISSUE TITLE
Enhancement - Projection table UI - Client reported

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#475]
1. Include the Average & Last month not filter selector on the total levels
2. Reduce column size for Principal Amount

![image](https://user-images.githubusercontent.com/43877959/79475633-8dd65280-8025-11ea-8e5f-53ef490803a9.png)

**Comment by nutank** [comment]
@georgioajency can you please share the figma screenshot for this change for reference?

Also, needed clarity on the scenario when reload happens - 
- Should the top levels interpret "custom" / "avg" / "lm" basis all the rows ate the bottom? or should they be as per what was explicitly selected.

**Comment by georgioajency** [comment]
Refer this link
https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=2432%3A7025

Yes the top level can reflect what the bottom is.

**If top level is either Avg or LM, then the drop down will have just these two values.**
**If top level is either Custom, then the drop down will show all three values.**
**If user changes from Custom to Avg or LM, a confirmation message will be shown
Average Principal Amount will be applied to each sub category rule under "Sale of Goods". Do you want to proceed?**

![image](https://user-images.githubusercontent.com/43877959/79954544-18420a80-849b-11ea-9640-8b9a7d07bced.png)

**Comment by georgioajency** [comment]
We need to show the values at the total levels. Not being handled currently.
![image](https://user-images.githubusercontent.com/43877959/80367042-fd5f0400-88a7-11ea-9147-ebccd4e253c7.png)

Should've been Avg: xxxx or LM: xxx
If custom then no value needs to be shown

**Comment by HazelColaco19** [comment]
1. Average & Last month labels are mentioned at the total level but not the values.


2. Column size comparatively reduced on the website

![image](https://user-images.githubusercontent.com/55691499/80366098-4f068f00-88a6-11ea-8ea8-defab84be002.png)

3. @georgioajency Please take a call on this. The pop up that is developed matches the other pop ups in the Figma link supplied above ( except a few things marked in red ). You find this better or reverting to the pop up in comments makes more sense?

![image](https://user-images.githubusercontent.com/55691499/80369479-f934e580-88ab-11ea-9a4f-889b5fdf2f6e.png)

4. 
a. If top level is either Avg or LM, then the drop down will have just these two values. ---> Correct

b. If top level is either Custom, then the drop down will show all three values. ---> Correct, however
If we change the drop down from " custom " to " LM " or " AVG " there is no way to revert back to " Custom " @nutank 


c. If user changes from Custom to Avg or LM, a confirmation message will be shown
Average Principal Amount will be applied to each sub category rule under "Sale of Goods". Do you want to proceed?
---> Appears + The above message is shown at cases when Average is switched to LM as well.

**Comment by georgioajency** [comment]
@HazelColaco19 responses below

1. The reported issue above your comment
2. The column width for Principal Amount is still not reduced. @nutank can this be done or is there a reason why it is kept so large?
3. Would've preferred the UI I requested. However, the current one works for me too. The pop up is consistent with what is used currently on the site
4.b Yes there is no way to go back to custom. This is correct.

**Comment by nutank** [comment]
Closing this ticket, by keeping #580  and #581 open
