### ISSUE TITLE
BUG - Global dropdown > Custom value in dropdown  does not work as expected

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#477]
**Current Behavior with Steps:**

Projection ID: 44449
1. Click on the "Include planned expenses" drop down. 
2. Choose value = Custom
3. Now click on a cell with a pre-added Planned expense and check on the check box that appears in the pop up.
4. Now click on any other cell, you will see despite the checkbox selection the value is not populating in the cell. it shows blank

![image](https://user-images.githubusercontent.com/55691499/79542047-92901a80-80a8-11ea-8b58-fe6263c4ee96.png)

**Expected:**
The value should be displayed if the check box is selected and it is the " Custom Selection "

**Comment by georgioajency** [comment]
Tested. Working
