### ISSUE TITLE
Update the UI for Cashflow Projection table

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#481]
You need to change the header of the table

https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=2432%3A7025

There could be a color change to green. Need to verify on that from the client. For now stick to Orange.

![image](https://user-images.githubusercontent.com/43877959/79560394-2cfe5700-80c5-11ea-90ef-9b6926c79d7a.png)

**Comment by georgioajency** [comment]
@Vaibhavarolkar Please do the below fixes

![image](https://user-images.githubusercontent.com/43877959/79851907-90e59000-83e3-11ea-94b6-d73257baa6bd.png)

**Comment by Vaibhavarolkar** [comment]
point 2 - Not possible to do @georgioajency

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/80061439-e7bba880-854e-11ea-817f-d9259e36de81.png)

1. Reduce font size of projection name from 1.5 to 1.3
2. Change color of Update to QB to green
3. Issue - On hover on Update to QB, it was changing the color to black
4. Increase side padding of the Update to QB button
5. Increase size of Delete button as per image

**Comment by georgioajency** [comment]
Checked

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/80074995-a2f03b80-8567-11ea-8f11-0665cb6472fc.png)

The shadow on the left box looks very faint compared to the right. 
Can you please check and see.
I want the left shadow to look similar to the update button as it is too light now. Make it a bit darker if necessary

**Comment by georgioajency** [comment]
Done
