### ISSUE TITLE
BUG - Upcoming expenses

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#484]
Values not matching after updating the projection

![image](https://user-images.githubusercontent.com/43877959/79564514-6f776200-80cc-11ea-9d34-887e0aacf9a4.png)

**Comment by legred21** [comment]
Data which you see now is for the month May and not the Jan. Although projection does not include may data but may data exist in future_cashflow

**Comment by georgioajency** [comment]
@nutank I think when you moved the creation date behind, the May month got hidden

**Comment by georgioajency** [comment]
This issue is similar to #504 
Closing this issue
