### ISSUE TITLE
BUG - In case there is no data at all, the graphs should not show up

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#485]
![image](https://user-images.githubusercontent.com/43877959/79565020-6dfa6980-80cd-11ea-83f3-2b4a05b89e11.png)

https://ajency-qa.toppeq.com/cashflow/projection/42288/edit
1st demo

**Comment by georgioajency** [comment]
Entire section should be hidden and not just the graphs
![image](https://user-images.githubusercontent.com/43877959/79713545-b7c09b00-82eb-11ea-88a7-4b36ac45c0b8.png)

**Comment by verlekar-viraj** [comment]
If there is data for operating but not investing. The moment the user switches from operating to investing, the section will disappear & he won't be able to switch back.

**Comment by georgioajency** [comment]
Oh so you are saying there is data for the other graphs.

My bad. What I meant was if there is no data at all for forecasted months then the section should not show at all. 
Ex. April 10 - FT Test (https://ajency-qa.toppeq.com/cashflow/projection/26008/edit)
This graph has no data i.e there are no months passed since the creation date of the template. So this projection the graphs should not be visible at all.

If there is some data for some sections but not there in others, we should show the section with graphs with the respective message. This will be similar to issue #487 
![image](https://user-images.githubusercontent.com/43877959/79716920-bc8a4c80-82f5-11ea-98c9-f9003ec89196.png)

**Comment by georgioajency** [comment]
Not handled for this case

![image](https://user-images.githubusercontent.com/43877959/79745253-8664c100-8325-11ea-8249-521d0f0d97cc.png)

https://ajency-qa.toppeq.com/cashflow/projection/56341/edit
2test
Investing filter

**Comment by georgioajency** [comment]
If the data is entered as 0, then show the graph. Else show the text.

The above application is correct. Closing this issue.
