### ISSUE TITLE
BUG - In case there is data and a particular filter has no data in it then we should show a message

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#487]
![image](https://user-images.githubusercontent.com/43877959/79565820-10ffb300-80cf-11ea-8bff-398d893ed521.png)

Sample message will be 
This projection has no <filter type> for <graph type>
Ex. This projection has no Investing data for Outflow (for Investing Filter and Outflow graph)
Ex. This projection has no data for Inflow (for All filter and Outflow graph)
Ex. This projection has no Financing data for Net (for Financing Filter and Net graph)

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/79713158-9612e400-82ea-11ea-914f-8e5ebe6043e3.png)

The text is not center aligned

**Comment by verlekar-viraj** [comment]
The y-axis is red as the current month starts at Jan in API response. To keep it consistent with the other graphs, the whole graph will be in red similar to the future data section in other graphs

**Comment by georgioajency** [comment]
Hmm.. good point. Keep this on hold. Will get clarity from the client on this.

**Comment by georgioajency** [comment]
Closing this task. 

Lines, borders & colors to be referred from #532
