### ISSUE TITLE
BUG - Percentage values should be rounded up for Accuracy

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#490]
If it is 25.6 then it should show 26
If it is 25.4 then it should show 25

![image](https://user-images.githubusercontent.com/43877959/79572089-fb43bb00-80d9-11ea-8f1c-4212e0bb6de8.png)

**Comment by legred21** [comment]
Fixed

**Comment by georgioajency** [comment]
Tested
