### ISSUE TITLE
TASK - Update the cron/sync now method to update closing cash balance only for end of each months in the period and for the current day.

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#491]

**Comment by robiulpro** [comment]
Completed

**Comment by HazelColaco19** [comment]
Tested today, verified all values from QB Reports duration Jan 2019 - April 2020

 For April 30 ,  value  of CASH AT END OF PERIOD | $94,872.68

To be verified on Monday, to see if the Cron is running continuosly. Will verify the values

**Comment by HazelColaco19** [comment]
1. For the template created on Friday, the value from QB did not get updated on the forecast template.

![image](https://user-images.githubusercontent.com/55691499/80360160-883a0180-889c-11ea-8409-187e42aeab62.png)

2. For a freshly created template, the past values did get updated but there is a mismatch in exact amount


![image](https://user-images.githubusercontent.com/55691499/80360800-80c72800-889d-11ea-92bb-0e4d9687a545.png)
