### ISSUE TITLE
TASK - Whatsapp notifications async

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#494]
To address - https://github.com/ajency/cashflow-issue-tracker/issues/357

**Comment by nutank** [comment]
https://docs.google.com/document/d/1V46WhlwVIhDGC_e-5OXUgUur5-d1fq2GTLugPiD0GzE/edit#

**Comment by nutank** [comment]
@HazelColaco19 please pick this for testing.

I have raised 2 direct issues that i saw, after Jessica fixes them please test this.
#564 , #563

@jessica-cardozo1 please assign to qa is issues and this task is complete.

**Comment by nutank** [comment]
QA Checklist: @HazelColaco19 
- [ ] Check Template generation - When payment status is paid
- [ ] Check Template generation - When payment status is pending
- [ ] Check Template generation - When expense is non recurring
- [ ] Check Template generation - When expense is recurring
- [ ] Summary should come quick , shouldn't take too long
- [ ] Normal notification messages for tagged users should continue to work

**Comment by nutank** [comment]
To be tested on following sandbox:

- [ ] Ajency QA server sandbox - "horn-everything"
- [ ] UAT server sandbox - "thou-silence"

**Comment by HazelColaco19** [comment]
This was tested and looked fixed on Friday itself. Closing the same.
