### ISSUE TITLE
Getting Data for all graphs right

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#496]

**Comment by HazelColaco19** [comment]
Tested the data and UI for graphs and found correct so far:

**Projection Dashboard**
1. Cash in cash out ---> Done
2. Cash flow and Burn rate ---> Done
3. Top 3 Expenses/ top 3 income -----> Done


**Cashflow Analysis**
1. Cashflow for main category - cashout   -----> Done
2. Cashflow for Main category - Cash In  -----> Done

**Comment by HazelColaco19** [comment]
Need to test the " Top 3 Expenses/ top 3 income " on inclusion of Planned Expenses

**Comment by HazelColaco19** [comment]
This issue can be closed since the above comment will be handled in #722
