### ISSUE TITLE
BUG - "1st Demo" Projection graph not loading. Error in server API. Projection Id = 42288

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#498]
![Screenshot 2020-04-20 at 11 22 42 AM](https://user-images.githubusercontent.com/7425622/79718301-530c3d00-82f9-11ea-9965-809a25d992fd.png)

**Comment by legred21** [comment]
Division by zero exception was taking place in average net and gross calculation. Since there was exception all graphs were going blank. issue is fixed by changing the logic of months calculation.

**Comment by georgioajency** [comment]
@nutank I checked and this seems to be working now. Not sure how to test this further. 

Closing it.
