### ISSUE TITLE
BUG - Graphs are not taking full section width of the page when months are more than 5 (Actual vs Planned)

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#499]
https://ajency-qa.toppeq.com/cashflow/projection/25334/edit
April 10

![image](https://user-images.githubusercontent.com/43877959/79719466-42a99180-82fc-11ea-9adc-7813303f31f0.png)

**Comment by georgioajency** [comment]
UI fixed.

Why is there a line in the middle after December? This shouldn't happen.

**Comment by verlekar-viraj** [comment]
The red line is for current month. Same as issue #487 which is on hold. Can close this

**Comment by georgioajency** [comment]
That is fine, for the above graphs the line starts before Nov. The last graph should have been the same. It cannot start after Dec

**Comment by verlekar-viraj** [comment]
@legred Current month for Net is Jan but rest of the graphs is Nov

**Comment by georgioajency** [comment]
Tested
