### ISSUE TITLE
BUG - Months directly proceed to May. 

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#500]
There should've been months in between even though the value was 0.
Since May is the last month with data, you need not show any months post that. 

![image](https://user-images.githubusercontent.com/43877959/79745584-363a2e80-8326-11ea-9708-03df3cb4cf29.png)

https://ajency-qa.toppeq.com/cashflow/projection/56341/edit

**Comment by legred21** [comment]
From feb 20 to May 20 no data existed in database. For whichever months data is not available in database 0 value is set to month

**Comment by georgioajency** [comment]
Checked. I think this will need to be optimized further
