### ISSUE TITLE
BUG - Values should automatically update once I go to the next month

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#504]
Upcoming Expenses and Upcoming Income section.

If I am in Apr it should show May. And if now for the same projection if I am in the month of August, it should show Sep

**Comment by legred21** [comment]
It is being handle in same way. UI is showing next month basis the projection creation date
![image](https://user-images.githubusercontent.com/55079454/79846868-94c1e400-83dc-11ea-9cde-d92fb48cb83d.png)

**Comment by georgioajency** [comment]
@legred21 The values displayed here should not be based on projection creation date but on current date. In the above example, the projection was created in Dec, however we are not in April, so it should've shown the values of May

**Comment by legred21** [comment]
@verlekar-viraj show upcoming next month from current date instead of showing a month basis the projection create date

**Comment by verlekar-viraj** [comment]
https://github.com/ajency/cashflow-issue-tracker/issues/446#issuecomment-614409707
It was changed to show next month based on creation date. #446

**Comment by georgioajency** [comment]
Tested
