### ISSUE TITLE
BUG - Restrict the size of the bars to a slim profile. Even if there is only one bar in the chart, the width has to be thin.

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#505]
![image](https://user-images.githubusercontent.com/43877959/79831329-d6469500-83c4-11ea-8809-f88f844c7809.png)

**Comment by HazelColaco19** [comment]
The bars look slim enough

![image](https://user-images.githubusercontent.com/55691499/81374966-0f4d6c00-911e-11ea-9385-04d0e508e1ef.png)
