### ISSUE TITLE
BUG - Should show a line on hover for Cash In by Category and Cash our by Category graph

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#506]
![image](https://user-images.githubusercontent.com/43877959/79840128-2298d180-83d3-11ea-8c9a-6adc4be3a359.png)

**Comment by georgioajency** [comment]
Can we disable this line for now? This worked well with the previous package where all 3 values were shown together.

**Comment by HazelColaco19** [comment]
Looks fixed.

![image](https://user-images.githubusercontent.com/55691499/80602404-b2322600-8a4c-11ea-9c84-af0b957ce2b9.png)
