### ISSUE TITLE
BUG - Burn rate graph > My projection duration is from Jan 2019 to Dec 2020 but on the graph we show the x-axis upto Sep 2020

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#508]
**Current behavior:**

Projection duration is from Jan 2019 to Dec 2020 but on the graph we show the x-axis upto Sep 2020

![image](https://user-images.githubusercontent.com/55691499/79864597-51c13a00-83f7-11ea-89aa-696f5a8b0462.png)

After adding a value for Dec 2020, it does show up the value on x axis

![image](https://user-images.githubusercontent.com/55691499/79866095-dd3bca80-83f9-11ea-9bb3-5de10a15d8c3.png)

**Expected behavior:**

The entire projection should be shown on the graph whether or not values are present.

**Comment by legred21** [comment]
same as #514

**Comment by georgioajency** [comment]
Tested
