### ISSUE TITLE
Inflow data not matching for the month of Nov 19 and December 19

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#512]
Projection id = 63869

![inflow](https://user-images.githubusercontent.com/7425622/79871301-c6997180-8401-11ea-8007-a96893f3d4fd.png)

Ideally there should be data for inflow i.e Payment from customer in the month of March worth Rs. 35650 as follows:

![Receive Payment](https://user-images.githubusercontent.com/7425622/79871830-97cfcb00-8402-11ea-8357-6943e6652da6.png)

Reference in QB - https://c43.qbo.intuit.com/app/recvpayment?txnId=284

**Comment by nutank** [comment]
Above fixed. Now proper till month of october. 

Month of november value goes wrong. Shows total cash in = 116, 672. But it ideally should be 118,765

![Screenshot 2020-04-21 at 8 34 32 PM](https://user-images.githubusercontent.com/7425622/79882032-9b1d8380-840f-11ea-802d-e032679a6e75.png)

Following transaction value for one payment seems to be wrong in ES:

![Search](https://user-images.githubusercontent.com/7425622/79882542-6a8a1980-8410-11ea-9530-2f4de8b0fc77.png)

**Comment by nutank** [comment]
December month seems fixed. 

For November month and scenarios where payment value is grater than total invoices sum following proportional distribution logic needs to be applied:

```
Payment = 10,000

Invoice 1 = 
   -L1 = Sale of Product Income = 5000
   -L2 = Uncategorised Income = 500  


Invoice 2 = 
   -L1 = Sale of Product Income = 1500
   -L2 = Uncategorised Income = 1000  



Total Invoice Sum = 8000
Actual Payment value = 10000


if invoice total sum < actual payment value 
	this distribution logic triggers
else
 	do current stuff



distribution logic :

Differnece value = 10000 - 8000 = 2000

   -L11 = Sale of Product Income = 5000 => 62.5% (5000/8000) => 5000 + 62.5*2000 = 5000 + 1250 = 6250
   -L12 = Uncategorised Income = 500 => 6.25% => 625     
   -L21 = Sale of Product Income = 1500 => 18.75% => 1875
   -L22 = Uncategorised Income = 1000 => 12.5 => 1250 
```

**Comment by jessica-cardozo1** [comment]
> Similarly for the month of **December 2019**, value is incorrect for txnId = 228 https://c43.qbo.intuit.com/app/recvpayment?txnId=228
> 
> Actual amount should be of txn 228 = $55,680.00
> Amount of [Kibana](http://13.234.21.219:5601/app/kibana#/discover?_g=()&_a=(columns:!(transactionType,qbParentId,qbAccountingCategoryId,qbAccountingCategoryName,parentPaymentCategoryType,amount,qbCategoryId,qbAccountCategory,toppeqCategory,toppeqActivityType,cashflowType),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:cashflowType.keyword,negate:!f,params:(query:Inflow,type:phrase),type:phrase,value:Inflow),query:(match:(cashflowType.keyword:(query:Inflow,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:companyId,negate:!f,params:(query:8,type:phrase),type:phrase,value:'8'),query:(match:(companyId:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Bill%20Payment',Purchase,'Journal%20Entry%20Credit','Journal%20Entry%20Debit',Deposit,Payment,'Sales%20Receipt',Invoice),type:phrases,value:'Bill%20Payment,%20Purchase,%20Journal%20Entry%20Credit,%20Journal%20Entry%20Debit,%20Deposit,%20Payment,%20Sales%20Receipt,%20Invoice'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Bill%20Payment')),(match_phrase:(transactionType.keyword:Purchase)),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Credit')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Debit')),(match_phrase:(transactionType.keyword:Deposit)),(match_phrase:(transactionType.keyword:Payment)),(match_phrase:(transactionType.keyword:'Sales%20Receipt')),(match_phrase:(transactionType.keyword:Invoice)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:txnDate,negate:!f,params:(gte:1575158400000,lt:1577836799000),type:range,value:'1,575,158,400,000%20to%201,577,836,799,000'),range:(txnDate:(gte:1575158400000,lt:1577836799000)))),index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc))) of txn 228 = 19740
> 
> The balance amount of invoice is indexed to ES instead of the actual payment amount
> ![Screenshot 2020-04-22 at 11 33 03 AM](https://user-images.githubusercontent.com/7425622/79946233-29841a80-848d-11ea-9c7b-954508093aec.png)

This is some re-indexing issue which occurs when one payment was synced. Same thing happens with Bill Payment.

**Comment by jessica-cardozo1** [comment]
For the Month of March 2020 there Purchase id  219 is being considered which has amount of -999 and Deposit id 218 which has amount of 365. Hence the value for Total Cash In is -634.
In quickbooks the value for the month of March is 365.
