### ISSUE TITLE
BUG - Desktop and Mobile the projection dashboard bar graphs look as though they started from below the x axis but the values are all above 0

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#513]
**Current Behavior:**
Desktop and Mobile the projection dashboard bar graphs look as though they started from below the x axis but the values are all above 0

_Graphs:_

- Cashflow & Burnrate
- Cash In & Cash-Out

**Desktop**

![image](https://user-images.githubusercontent.com/55691499/79872230-293f3d00-8403-11ea-86a2-a8198884460b.png)

**Mobile**

![image](https://user-images.githubusercontent.com/55691499/79872444-6b687e80-8403-11ea-9393-4f9da401c7d6.png)

**Expected Behavior:**

All bar graphs should start from the x axis if the values are at or above ' 0 '

**Comment by georgioajency** [comment]
Closing this issue. Creating a separate issue for graphs
