### ISSUE TITLE
Cashflow for Main category - Cash Out : On the template, the past cashflow months are till April 2020, but on the graph it is till March 2020

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#514]
![image](https://user-images.githubusercontent.com/55691499/79873706-13327c00-8405-11ea-9a60-ce87d8e086d2.png)

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/79942356-4405c600-8484-11ea-9111-42642681c015.png)
As there is no projection id is being passed in request, All data is fetched from cashflow table and no data from past_cashflow or future_cashflow table is involved in graph

**Comment by legred21** [comment]
start date and end date comparison was going wrong. comparison is now fixed

**Comment by georgioajency** [comment]
Tested
