### ISSUE TITLE
Fix the calculation for "Accounts Receivable" and "Accounts Payable"

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#517]
**Accounts payable (refer Balance sheet)**
Bills - Bill Payment check

**Accounts Receivable (refer Balance sheet)**
Invoice - Payments

_Originally posted by @georgioajency in https://github.com/ajency/cashflow-issue-tracker/issues/493#issuecomment-616985236_

**Comment by nutank** [comment]
Accounts Payable as of  current date  = all bills - all bill payments
Accounts Payable for 1st Jan 2020 = All bills till 1st of Jan - All BP till 1st of Jan

**Comment by georgioajency** [comment]
Account Receivables value incorrect.
This payment transaction is missing from Kibana
https://c43.qbo.intuit.com/app/recvpayment?txnId=222   

Accounts Payable is incorrect
Value is incorrect in Kibana
https://c43.qbo.intuit.com/app/billpayment?txnId=294  - Showing as 1771 in Kibana. Actual is 
https://c43.qbo.intuit.com/app/billpayment?txnId=295  - Showing as 1518 in Kibana

**Comment by legred21** [comment]
Bill payments are fixed

**Comment by georgioajency** [comment]
Tested. Both values are accurately showing under the graph. Closing this issue
