### ISSUE TITLE
UAT Feedback - Split the Cashflow and Burnrate graph

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#519]
One graph should show burn-amount. Rename the graph to **Burn amount**.

The other graph will be shown below. It will be called **Closing cash balance**
**The line graph should be straight and not curvy**

![image](https://user-images.githubusercontent.com/43877959/79955764-dd40d680-849c-11ea-841d-4bcb36b9af85.png)
Split this graph

**Comment by HazelColaco19** [comment]
1. The title of the graph should be " Burn Amount "

![image](https://user-images.githubusercontent.com/55691499/80601371-5915c280-8a4b-11ea-9784-e3d1fbde743b.png)



2. The line graph should be straight and not curvy

![image](https://user-images.githubusercontent.com/55691499/80601414-6b8ffc00-8a4b-11ea-95b4-93e6720c80d9.png)

**Comment by HazelColaco19** [comment]
1. Burn Amount applied
![image](https://user-images.githubusercontent.com/55691499/80704425-27abfe00-8b02-11ea-904c-9e46ab91132f.png)



2. The line graph is straight and not curvy

![image](https://user-images.githubusercontent.com/55691499/80704473-3e525500-8b02-11ea-869e-5b1ea3b7cd13.png)
