### ISSUE TITLE
UAT Feedback - Have operating, Investing, Financing for Cash in and Cash Out

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#520]
Need to include drop-down for operating, Investing, Financing for Cash in and Cash Out.
![image](https://user-images.githubusercontent.com/43877959/79956339-a3240480-849d-11ea-95e3-793db5015b5a.png)

**Comment by legred21** [comment]
API changes done

**Comment by robiulpro** [comment]
Completed

**Comment by HazelColaco19** [comment]
@nutank 

Issue found when switching between the dropdown values. Values are excluded from " ALL " drop down. This is the view on " ALL ", value in May 2020
![image](https://user-images.githubusercontent.com/55691499/82531780-9b6b8480-9b5d-11ea-8d1a-c1193feb367b.png)

When you individually click " Investing " you see there are values in Jan 19, Nov 19 and March 20.

![image](https://user-images.githubusercontent.com/55691499/82531841-bdfd9d80-9b5d-11ea-9319-cec899471664.png)

Again on selection of " Financing " , you have " Jan 19 ", feb and may 20 values.

![image](https://user-images.githubusercontent.com/55691499/82531915-e2f21080-9b5d-11ea-80d2-dd2597f9a9c5.png)



It looks like values from Operating are picked while displaying ALL, and not a collaboration of the three categories.

**Comment by robiulpro** [comment]
'All' returning less data from server compare to selecting individual filter, @legred21 please check.

**Comment by robiulpro** [comment]
No issue, when you select all, future cash in data is so huge that the scale changed to M (million), the smaller digits graph is not visible for past cash in. But when you select individual the past graph is visible as there are less difference between past and future.

**Comment by HazelColaco19** [comment]
Test on company with more data. Company 32 and it seems fine
