### ISSUE TITLE
Enhancement - All values in the Projection table should match the Graphs. Need to include both Planned & Forecast expenses

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#522]
Graphs only show Forecast expenses. We need to show planned expenses if they are selected in the projection.

**Comment by HazelColaco19** [comment]
1. If the toggle says " Yes " 

a. not all the planned values get displayed on the forecast template. Given the db values of such expenses

![image](https://user-images.githubusercontent.com/55691499/80206506-12d6f280-864a-11ea-87a2-72479e6160c9.png)


b. The values in graph do not match with that in forecast template. Tested cash out values for graph " Cash In Cash out "

![image](https://user-images.githubusercontent.com/55691499/80206676-68130400-864a-11ea-86c9-d4abe657fac7.png)




2. If the toggle says " Custom ", here is the behavior:

a. The value in tested graph looks proper

![image](https://user-images.githubusercontent.com/55691499/80207646-25522b80-864c-11ea-8857-8804339aac75.png)



b. Noticed, not all the planned expenses show up for the month of June 2020, so this leads it to a miscalculation.

c. When clicked on any cell that will have a planned expense, it did not show the pre populated value but only showed a ' 0 ' value.

DB values: db_72930, db_72917, db_72701

**Comment by georgioajency** [comment]
Issue to be retested once #540 is done

**Comment by legred21** [comment]
API changes done. Need forecast template UI changes for graphs to match forecast template

**Comment by nutank** [comment]
Closing this ticket as it will get handled with this - https://github.com/ajency/cashflow-issue-tracker/issues/551
