### ISSUE TITLE
UAT Feedback - If no data for Planned vs Actual accuracy, then we should show No data

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#523]
![image](https://user-images.githubusercontent.com/43877959/79958481-97860d00-84a0-11ea-8066-157d19114166.png)

**Comment by HazelColaco19** [comment]
Not fixed. Two graphs show 0% and one graph shows No data which does not match the design

![image](https://user-images.githubusercontent.com/55691499/80606491-05f33e00-8a52-11ea-8089-6b0a19d0dea5.png)

**Comment by HazelColaco19** [comment]
**Currently on Website:**

![image](https://user-images.githubusercontent.com/55691499/80704979-33e48b00-8b03-11ea-937d-2c536cff9344.png)



**Discrepancy from Design:**

![image](https://user-images.githubusercontent.com/55691499/80704955-2af3b980-8b03-11ea-9191-3a287a127fb7.png)

1. The Text is in init caps in design. Please compare
2. The circle should be bigger compared in proportion to the text. Also there should be buffer space between the circle and the text. Please compare

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/81041674-0c5b3d00-8ecc-11ea-9aa1-50e189e1ffcf.png)
