### ISSUE TITLE
Key Metrics page & Cashflow Analysis Page - Element Alignment does not seem right

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#524]
![Toppeq (1)](https://user-images.githubusercontent.com/7425622/79958995-2f83f680-84a1-11ea-849f-23ef844ce8a6.png)

**Comment by nutank** [comment]
Cashflow Analysis Page 

![Toppeq (2)](https://user-images.githubusercontent.com/7425622/79959231-82f64480-84a1-11ea-82ea-77201e78f03e.png)

**Comment by nutank** [comment]
@Vaibhavarolkar datepicker overlaps

![Screenshot 2020-04-22 at 3 11 46 PM](https://user-images.githubusercontent.com/7425622/79966874-b211b380-84ab-11ea-80de-fb0ddd3c8cda.png)

**Comment by georgioajency** [comment]
Date picker is not aligned

**Comment by georgioajency** [comment]
Should not show within 30 days
![image](https://user-images.githubusercontent.com/43877959/79967452-7b886880-84ac-11ea-8925-860ead37f2a7.png)

**Comment by georgioajency** [comment]
Have the dropdown edges a bit curved
![image](https://user-images.githubusercontent.com/43877959/79967729-d6ba5b00-84ac-11ea-97c6-189d91b98b65.png)

**Comment by georgioajency** [comment]
The drop-down V should not be visible when I select any of the predefined types
Only on custom it should show drop down arrows
![image](https://user-images.githubusercontent.com/43877959/79968079-49c3d180-84ad-11ea-8d40-d033b6bb5b44.png)

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/79968448-bc34b180-84ad-11ea-9a40-812a5b1d3efc.png)

1. Has to be a separator between the first drop down and the others.
2. The entire bar should not be edge to edge
3. Make the background of the drop down white.
4. If I select custom and choose a date then it should show an Apply button

**Comment by georgioajency** [comment]
Make the following changes

1. Button with white background and border (curved edges)
![image](https://user-images.githubusercontent.com/43877959/80060437-2734c580-854c-11ea-8cc6-055554865138.png)

2. Same styling for date picker
![image](https://user-images.githubusercontent.com/43877959/80060487-54817380-854c-11ea-9052-1be87317ddab.png)

3. Date picker is showing some code on hover
![image](https://user-images.githubusercontent.com/43877959/80060541-6fec7e80-854c-11ea-8542-9085a9ad635b.png)

4. Date picker should highlight current date and restrict selection after the current date
![image](https://user-images.githubusercontent.com/43877959/80060674-be018200-854c-11ea-9abe-d30cc0abf226.png)

5. Make the Apply button wider and change the colors to this
![image](https://user-images.githubusercontent.com/43877959/80061003-9fe85180-854d-11ea-98ae-9b4cacff9f03.png)

**Comment by georgioajency** [comment]
Tested
