### ISSUE TITLE
BUG - The tags if consists of two words should be separated by a underscore. Currently it is not, it is separated by " space "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#529]
**Current behavior:**

The tags if consists of two words should be separated by a hyphen. Currently it is not

![image](https://user-images.githubusercontent.com/55691499/79973304-f6558180-84b4-11ea-8ba2-db44bf6fe0a0.png)

**Expected behavior:**

Notified Whatsapp user should see " Office_Expenses " and not " Office Expenses " as a tag.

**Comment by legred21** [comment]
Branch : legred/final-tag-underscore-fix

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/85259648-0672e880-b487-11ea-99e3-6fc0bb060d60.png)
