### ISSUE TITLE
BUG - On click of the expense link in the Whatsapp Bot, it requests to login on the website and upon sign in - does not redirect to the expense in Planned Outflow

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#530]
**Current Behavior:**

On click of the expense link in the Whatsapp Bot, it requests to login on the website and upon sign in - does not redirect to the expense in Planned Outflow

![image](https://user-images.githubusercontent.com/55691499/79975032-f1de9800-84b7-11ea-9f7b-33d7cffff84d.png)

**Expected Behavior:**

On click of the link, if the user is already logged in to the browser, he should be re-directed to the expense instead of the Homepage

**Comment by nutank** [comment]
This is not on datta. This issue is in react app something that they need to handle in react app.
