### ISSUE TITLE
BUG - The created expense cannot be viewed on the UI even if the Category is from Latest Mapping Sheet

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#531]
**Current Behavior:**

Upon creating an expense from the bot, there are few observations as below:

1. The ID cannot be viewed on front end ( expense is not visibly listed in the table )
2. Upon entering the id manually in the URL it returns a blank screen.

![image](https://user-images.githubusercontent.com/55691499/79977431-e3927b00-84bb-11ea-8764-0489ad3ddb2e.png)

_EXAMPLE#1_
DB Value of such an expense: db_64686
Category : Purchase Of Asset
Tags : #miscellaneous, #purchase_of_asset

_EXAMPLE#2_
DB Value of such an expense: db_64386
Category : Office Expenses
Tags : #furniture, #office_expenses

**Expected:**

1. The expense should be listed in the planned outflow table

**Comment by nutank** [comment]
Seems like these are getting indexed in UAT's ES but stored on QA server's DB

cc- @robiulpro , @legred21

**Comment by nutank** [comment]
@HazelColaco19 this issue was due to the same sns topic being shared by uat server and ajency qa server. This should not happen going forward.

**Comment by HazelColaco19** [comment]
I can see the tickets now.  Will close this issue
