### ISSUE TITLE
BUG - Cashflow metrics date picker - For any date value (preset or custom) it is considering one month in past

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#533]
![image](https://user-images.githubusercontent.com/43877959/80000866-4e9f7a00-84db-11ea-9ae9-43970e0824b0.png)

Date is from Jan till today

Value is from Dec till today

![image](https://user-images.githubusercontent.com/43877959/80000897-5eb75980-84db-11ea-959e-386a4580f1c5.png)

**Comment by legred21** [comment]
in UI date is selected as 1st april but in request i can see 31st march

**Comment by robiulpro** [comment]
fixed

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/80083259-0895f500-8573-11ea-84d2-e1caf4041c0b.png)

I selected last year and the graph is showing April twice

**Comment by legred21** [comment]
API is working fine. UI is showing data point twice

**Comment by robiulpro** [comment]
Fixed by @legred21

**Comment by georgioajency** [comment]
Checked.
