### ISSUE TITLE
Enhancement - Delete a projection

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#535]
On the click of the delete button, it should throw a confirmation message asking you if you want to delete the projection.

![image](https://user-images.githubusercontent.com/43877959/80074469-d2eb0f00-8566-11ea-8087-0e4a6e1cab33.png)

![image](https://user-images.githubusercontent.com/43877959/80074707-370dd300-8567-11ea-8956-9d2931f6abdd.png)

**Comment by HazelColaco19** [comment]
A-39 - Unable to create projection with name already deleted from system. 

Client reported issue. Also the above doesn't work. @nutank

**Comment by robiulpro** [comment]
Delete projection implemented in UI.

**Comment by HazelColaco19** [comment]
Created a projection for company=32, pjctn id = 105161. Deleted it from UI and checked in table, the flag was set to deleted = True.


![image](https://user-images.githubusercontent.com/55691499/82632595-55262c00-9c16-11ea-8d8f-dae2d9507383.png)


Later managed to create a new projection of the same name ( May 22 ).

![image](https://user-images.githubusercontent.com/55691499/82632684-8c94d880-9c16-11ea-925e-c072d8b0426e.png)

ticket can be closed
