### ISSUE TITLE
BUG - Fetch other QB categories when toppeq category is "Others"

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#538]

**Comment by HazelColaco19** [comment]
1. While create new expense + edit old expense ( Recurrence = No ):

42 categories are displayed

![image](https://user-images.githubusercontent.com/55691499/82218394-75fe3100-9939-11ea-8bf8-a65dd1885938.png)


In DB we have 42 entries

![image](https://user-images.githubusercontent.com/55691499/82218450-89110100-9939-11ea-84b2-5667a7bf260d.png)

Ticket can be closed
