### ISSUE TITLE
TASK - Update planned expenses in a projection on Update

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#540]
When user updates their projection data by clicking Update Data, the planned expenses will be updated

UI Changes to be done
Change text to **Update Data**. Center align the text.
![image](https://user-images.githubusercontent.com/43877959/80112155-6986f280-859e-11ea-9d44-14781aa1dffc.png)

Update text to 
**Are you sure you want to update the past data and Planned Expenses?**
And button to **Update Data**
![image](https://user-images.githubusercontent.com/43877959/80112694-034e9f80-859f-11ea-8f30-184cecc8a37c.png)

**Comment by nutank** [comment]
https://github.com/ajency/cashflow-issue-tracker/issues/536

**Comment by HazelColaco19** [comment]
Here I had added an Expense in October 2020 ( +5000 Office Rent ) and then on forecast template post selecting " Planned Expenses " synced the QB data. I could not see any data being populated in this template.
Projection ID: 77618

![image](https://user-images.githubusercontent.com/55691499/81141081-24dd5d00-8f89-11ea-9375-94d81aee71f5.png)

Expense added:

![image](https://user-images.githubusercontent.com/55691499/81141126-463e4900-8f89-11ea-9c94-c43c773d215c.png)

**Comment by robiulpro** [comment]
The future expense will only show up if corresponding past entry exists. The is how the projection was designed. No issue.
Try adding a planned expense for a quickbook category where corresponding past entry present. And then click on 'Update data' button.

**Comment by HazelColaco19** [comment]
if you change toggle from No to Yes and update data for categories present as part of past data - it works fine
but then, if you change the toggle from Yes to Custom and then from custom back to " Yes " it gives me this error

![image](https://user-images.githubusercontent.com/55691499/82636415-32007a00-9c20-11ea-8d1e-b74ea6672afe.png)

![image](https://user-images.githubusercontent.com/55691499/82636428-388ef180-9c20-11ea-86ac-f9f54220f17d.png)

**Comment by HazelColaco19** [comment]
Could not replicate. can be closed
