### ISSUE TITLE
BUG - Future data in graphs show extra deleted records from past data

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#544]
Expected behaviour - Future data in graphs should only show the category data basis the past data.

**Comment by legred21** [comment]
Future data in graphs now shows the data basis the categories in past data

**Comment by HazelColaco19** [comment]
Cannot test this since the added planned expenses are not getting reflected on the Forecast template.

**Note:** The expenses were created first and then the template was created. 

![image](https://user-images.githubusercontent.com/55691499/80225221-65270c00-8668-11ea-99af-d18c446b2ce7.png)

@nutank @legred21

**Comment by nutank** [comment]
@HazelColaco19 dont think this is tested correctly. This bug is being confused with this task - https://github.com/ajency/cashflow-issue-tracker/issues/522

**Comment by HazelColaco19** [comment]
Is seen fixed. Can be closed.

Created various planned expenses which do not fall in the category of cash outflow already present.

Past cashflow table for the projection: 100453

![image](https://user-images.githubusercontent.com/55691499/82294369-a8f10500-99cb-11ea-8f02-3a2c99ef4d0c.png)

Future data created:
![image](https://user-images.githubusercontent.com/55691499/82294294-88c14600-99cb-11ea-8cb5-9b0af27e4c17.png)

Does not appear in template nor future cashflow table:

![image](https://user-images.githubusercontent.com/55691499/82294479-da69d080-99cb-11ea-9fde-5640d06f6bf8.png)

![image](https://user-images.githubusercontent.com/55691499/82294519-ea81b000-99cb-11ea-8de3-91f0cc499056.png)
