### ISSUE TITLE
BUG - Opening Cash Balance pop up - Design issues ticket reference #395

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#548]
**Expected Behavior highlighting the error:**

1. The " Issue " title is centre aligned on design. But on developed is left aligned. See in blue
2. check the content box difference and is highlighted in green in the image
3. The header shown in purple line is also bold on design but not in the implementation. See Purple
4. In the pop up, the design shows the " currency " sign followed by the amount ( value ). In implementation it does not show the currency sign. See in yellow

![image](https://user-images.githubusercontent.com/55691499/80191544-7bff3b80-8633-11ea-812f-449350079961.png)

Reference issue: #395

**Comment by HazelColaco19** [comment]
@georgioajency Please review the above discrepancy and comment if the design I followed isn't updated with latest comments

**Comment by georgioajency** [comment]
Approved by client
