### ISSUE TITLE
TASK - When planned expenses is included or excluded forecast template's opening balance, closing balance and net cash should change accordingly

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#551]

**Comment by legred21** [comment]
API changes done. Need front end changes for forecast template to show correct data

**Comment by nutank** [comment]
This issue handles #522

**Comment by robiulpro** [comment]
Fixed. Whenever planned expense flag change, will refresh the table after getting response from edit scenario api.

**Comment by HazelColaco19** [comment]
Fixed.

When planned expenses were not visible on template July CCB was -31, 646,095. With the addition of amount 33333, the CCB = -31,612,762

Before
![image](https://user-images.githubusercontent.com/55691499/82637769-22366500-9c23-11ea-8be3-93d52c4c88c5.png)


After
![image](https://user-images.githubusercontent.com/55691499/82637712-fd41f200-9c22-11ea-9669-1538cc24101d.png)


Also the opening balance changed for August.
