### ISSUE TITLE
UAT - Runway - If the values crosses a certain limit, show the value in Days, Months or Year

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#552]
less than a month - show in days (15 days to go, 30 days to go)
more than a month - show in months(3 months to go, 11.4 months to go)
more than a year - show in years (1 year to go, 14.6 year to go)

**Comment by nutank** [comment]
1 Year = 365 days
1 Month = 31 days

**Comment by legred21** [comment]
API changes done

**Comment by HazelColaco19** [comment]
Net Runway shows 1 Year instead  of 365 days
![image](https://user-images.githubusercontent.com/55691499/81169424-76501100-8fb6-11ea-9df0-d40a93cac4f9.png)

**Comment by HazelColaco19** [comment]
As discussed with @nutank , comment to consider is as posted in ticket. Fixed as per @georgioajency requirement

less than a month - show in days (15 days to go, 30 days to go)

![image](https://user-images.githubusercontent.com/55691499/81257872-fa0b0b80-9051-11ea-870e-033c19d9ce5e.png)


more than a month - show in months(3 months to go, 11.4 months to go)
![image](https://user-images.githubusercontent.com/55691499/81257923-2161d880-9052-11ea-9125-93750147b48c.png)





more than a year - show in years (1 year to go, 14.6 year to go)

![image](https://user-images.githubusercontent.com/55691499/81257997-4c4c2c80-9052-11ea-95e2-ad8503f26058.png)
