### ISSUE TITLE
UAT - The left side of the pane in forecast template should start from the latest month

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#553]
Current logic
Starts from the first month
![image](https://user-images.githubusercontent.com/43877959/80332961-1648c480-886a-11ea-8b65-cb69dd3e23e9.png)

Has to start from the last month
![image](https://user-images.githubusercontent.com/43877959/80332995-37111a00-886a-11ea-8d8c-b237cb962fc2.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/81042623-29910b00-8ece-11ea-8df1-6d30746cbbb1.png)
