### ISSUE TITLE
TASK - Update the Quickbook Data table

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#554]
UI
https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=3100%3A0

![image](https://user-images.githubusercontent.com/43877959/80450293-dc95bd80-893e-11ea-8c4f-e1c7270b3366.png)

The data here will be will be similar to the General Ledger in QB

The table will be sorted be sorted by Category first and then by date. This is fixed and cannot be changed

The list will show all the transactions occured within that date range. 

A column called Balance will calculate the amount of that category
The opening balance of a category is the Sum of all the transactions that have occured prior to the selected date period for that category

There are only 2 filters, selecting category and Date range.
Category filter will be a multi-checkbox

Date picker can be the same as what we used previously. Will have the same list of predefined drop downs.
We should include another predefined option called **All dates** in the drop down. This will consist of all data from the start till the future.
Default select can be set to this year.

There will not be a number of records drop down. All categories that have value will be shown. 
i.e only for categories where opening cash balance is 0 AND there are no transactions for that selected date period, then that category will not be shown.

**The Category will be QB category**
Category drop down filter, should show only categories that have data against them across all dates. 

Reset will only show when the values other than the default are selected

-------------------------------
Addtional transactions
The transactions are two ways. 
Need to show transactions based on the following categories also

- Bank type accounts
- Cash on hand
- Accounts Receivable
- Accounts Payable

**To be confirmed** (Not to be done separately, as discussed with anuj)
- Inventory
- Inventory Asset
- Sales of Product Income
- Cost of goods sold

**Comment by georgioajency** [comment]
@nutank @robiulpro 
Link and image updated based on updated requirements

**Comment by robiulpro** [comment]
@nutank @HazelColaco19 
Server part is done for all categories (Not bank type, receivable/payable).
API doc can be found here:
https://docs.google.com/document/d/1dGKOaCBgbpoI4yawRFFefbhOcR77jIS8O16o5We-s8k/edit#

**Comment by nutank** [comment]
@georgioajency you can test it at [this graphql endpoint](https://ajency-qa.api.toppeq.com/graphiql?query=query%20(%24input%3A%20QuickbookDataInput!)%20%7B%0A%20%20getQuickbookData(input%3A%20%24input)%20%7B%0A%20%20%20%20category%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20inflowTotal%0A%20%20%20%20%20%20outflowTotal%0A%20%20%20%20%20%20openingBalance%0A%20%20%20%20%7D%0A%20%20%20%20rows%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20date%0A%20%20%20%20%20%20cashflowType%0A%20%20%20%20%20%20transactionType%0A%20%20%20%20%20%20amount%0A%20%20%20%20%20%20balance%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%22input%22%3A%20%7B%0A%20%20%20%22companyId%22%3A%208%2C%0A%20%20%20%22categoryIds%22%3A%20%5B30%2C%2045%5D%2C%0A%20%20%20%22startDate%22%3A%20%222020-01-10T00%3A00%3A00Z%22%2C%0A%20%20%20%22endDate%22%3A%20%222020-04-20T23%3A59%3A59Z%22%0A%20%7D%0A%7D%0A)

**Comment by georgioajency** [comment]
@robiulpro checked the data. Need to see if all categories are showing up
**F/b 1**
Based on the General ledger, all transactions that are shown under a category, their Bill Payments and Payments are not shown.

Please hide all transactions of this type.

While working with Bank, Account Payable and Receivable, we will have to show the transactions here accordingly
Bank - All transactions except Bills and Invoices (You can use the same list of transactions as what is used for the cashflow projection table)
A/R = Invoices - Payments
A/P = Bills - Bill Payments

**Comment by robiulpro** [comment]
@georgioajency 
Point 1 and 2 fixed.

**Comment by georgioajency** [comment]
Feedback 4
Even if there is no transaction for that selected time period, we still need to show the opening balance of all other categories if there was some transaction done in the past

**Comment by robiulpro** [comment]
Point 3 fixed

**Comment by nutank** [comment]
**Accounts Receivable:**
Op balance = sum of transactions of type Invoice and customer payments
List = Plus Invoice , Minus Customer payments

**Accounts Payable** 
Op balance = sum of transactions of type Bills and Bill payments
List = Plus Invoice , Minus customer payments

**Cogs**
Op balance = Sum of transactions of all types excluding bill payments and payments whose category is of type cogs
List = <find out if API gives value, else display as per current logic>

**Inventory Assets** - skip as discussed

**Split Column**

**Comment by nutank** [comment]
Bank
Payment - Accounts Receivable
Bill Payment -  Accounts Payable
All other transactions - Category type

Accounts Receivable
Invoice - Category type
Payment - Bank type

Accounts Payable
Bill - Category type
Bill Payment - Bank type

Sales
Invoice - Accounts Receivable
Sales receipt - Category

Shipping
Bill -  Accounts Payable
Expenses - Category

Other categories
Bill - Accounts Payable
Invoices - Accounts Receivable
Expenses - Mode of payment (Bank)
Sales Receipt - Mode of payment  (Bank)   
Journal entry - Category
