### ISSUE TITLE
BUG - For the template created on Friday, the value from QB did not get updated on the forecast template.

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#555]
1. For the template created on Friday, the value from QB did not get updated on the forecast template.

Projection ID: 74428

![image](https://user-images.githubusercontent.com/55691499/80360160-883a0180-889c-11ea-8409-187e42aeab62.png)

2. For a freshly created template, the past values did get updated but there is a mismatch in exact amount

Projection ID: 74606

![image](https://user-images.githubusercontent.com/55691499/80360800-80c72800-889d-11ea-92bb-0e4d9687a545.png)

_Originally posted by @HazelColaco19 in https://github.com/ajency/cashflow-issue-tracker/issues/491#issuecomment-619880476_

**Comment by nutank** [comment]
@HazelColaco19 please check the end date correctly as the current date for current month rather than last date of month. If issue still persists then assign as bug to dev.

**Comment by HazelColaco19** [comment]
The value matches with the end date being the current date of the month. It can be closed.


![image](https://user-images.githubusercontent.com/55691499/80450635-968d2980-893f-11ea-8377-9d7e2c77b61e.png)
