### ISSUE TITLE
TASK - Organization Setup for a new client 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#557]
Tech doc - https://docs.google.com/document/d/1dGKOaCBgbpoI4yawRFFefbhOcR77jIS8O16o5We-s8k/edit#

**Comment by robiulpro** [comment]
Completed.

**Comment by nutank** [comment]
@HazelColaco19 User on-boarding document shared with client - https://docs.google.com/document/d/1ZS6XSaU5o2_WyTc56nShgerRdEsQoAqGcKSzQ_j-_3s/edit

**Comment by HazelColaco19** [comment]
This has been tested and import has been successful during the sanity check on Friday. Can be closed
