### ISSUE TITLE
BUG - Deposit, Sales Receipt: Expenses/ income raised in QB are not getting displayed on the forecast template despite doing a QB sync 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#560]
**Pre-requisites:**

Login to QB account of company 10.

Task reference  #434

**Current behavior:**

Some of the expenses/ income raised in QB are not getting displayed on the forecast template despite doing a **QB sync** in Quickbook data page or _Update with QB_ in forecast template page. And the data is verified to be there in Kibana.

The values in red are not showing up, but the ones highlighted in green have shown up.

See tab in sheet 495, 434 below

https://docs.google.com/spreadsheets/d/1QKR5tXpIsPiasdorrxOZuUbNXBBeWme9M4qZmfplKik/edit?usp=sharing

![image](https://user-images.githubusercontent.com/55691499/80500925-6f107e00-898c-11ea-9a31-509aabd09ef6.png)

Kibana reference: 

![image](https://user-images.githubusercontent.com/55691499/80501083-a2eba380-898c-11ea-9a90-99cc7dfbd932.png)

**Expected Behavior:**

All of the records should reflect post syncing

**Comment by nutank** [comment]
@HazelColaco19 is this valid?
