### ISSUE TITLE
We have two synced status labels on the Forecast Template Screen, should we really show two or remove one?

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#561]
![image](https://user-images.githubusercontent.com/55691499/80503092-0aa2ee00-898f-11ea-9234-237836aa8cba.png)

**Comment by georgioajency** [comment]
Text on the left should be "Last saved: 2 hours ago"

**Comment by HazelColaco19** [comment]
Looks fixed.

![image](https://user-images.githubusercontent.com/55691499/80602935-62a02a00-8a4d-11ea-805d-b50309ba15e3.png)
