### ISSUE TITLE
Async WhatsApp messages are not going out immediately. Most messages remain pending as per sns_tracker table

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#563]
Tried for mine and datta's number.

![Screenshot 2020-04-29 at 5 17 18 PM](https://user-images.githubusercontent.com/7425622/80592568-4d230400-8a3d-11ea-992c-175fc71f6690.png)

![Screenshot 2020-04-29 at 5 18 23 PM](https://user-images.githubusercontent.com/7425622/80592685-76dc2b00-8a3d-11ea-9943-d31c6c2e7e37.png)

**Comment by jessica-cardozo1** [comment]
Issue was because there was no null check for notifyCustomUsers in the code.

**Comment by HazelColaco19** [comment]
Still did not receive the expense record. see the time gap.

![image](https://user-images.githubusercontent.com/55691499/80687725-5a48fd00-8ae8-11ea-9984-6b4148834180.png)

**Comment by jessica-cardozo1** [comment]
@HazelColaco19  I had restarted the server at 1:36 pm because of which you did not receive the summary. Let me know if this occurs again.

**Comment by HazelColaco19** [comment]
That was the only record which didn't show up. Otherwise things are faster now.
