### ISSUE TITLE
Tags/ Category or Users notified not showing in async whatsapp messages 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#564]
![Screenshot 2020-04-29 at 6 21 25 PM](https://user-images.githubusercontent.com/7425622/80598008-52388100-8a46-11ea-88b9-31232e92b9ec.png)

**Comment by HazelColaco19** [comment]
Looks fixed. Checked using different keywords

![image](https://user-images.githubusercontent.com/55691499/80681181-c5410680-8add-11ea-9ec0-a0f6abeccea6.png)

**Comment by jessica-cardozo1** [comment]
Each category has users mapped to it in accounting_head_user_mapping table. Those users would be displayed in Users Notified.

**Comment by nutank** [comment]
@HazelColaco19 the users are as per category + user mapping table as mentioned by jessica. 

@jessica-cardozo1 you can display a hyphen if the users list is empty.

**Comment by HazelColaco19** [comment]
Change applied. Can be closed.

![image](https://user-images.githubusercontent.com/55691499/80688425-61bcd600-8ae9-11ea-905f-f75adc22a4b7.png)
