### ISSUE TITLE
Enahancement - Update the text of the final message

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#566]
![image](https://user-images.githubusercontent.com/43877959/80674840-9bcdae00-8ad0-11ea-9839-b2a7bad674f8.png)

**Great! Your expense was successfully added to Toppeq**

**Comment by HazelColaco19** [comment]
Text Change implemented. Can be closed.

![image](https://user-images.githubusercontent.com/55691499/80684628-929a0c80-8ae3-11ea-9dfa-760cbed8c319.png)
