### ISSUE TITLE
BUG - Async Whatsapp message shows "Due Date" even if expense is paid expense. Should show as "Payment Date" "

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#567]
![2020-04-29](https://user-images.githubusercontent.com/7425622/80675394-f287b780-8ad1-11ea-9827-a163de318eb8.jpg)

**Comment by HazelColaco19** [comment]
Can be closed.
If the Expense has status Paid it shows " Payment Date ".
If the Expense  has status Unpaid it shows " Due Date ". 

![image](https://user-images.githubusercontent.com/55691499/80684350-2ae3c180-8ae3-11ea-8764-3fa54329c5cb.png)
