### ISSUE TITLE
Enhancement - If the values go negative, introduce a shade in the bottom half

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#570]
Current graph
![image](https://user-images.githubusercontent.com/43877959/80722248-cc3b3980-8b1c-11ea-8929-b2149528e55f.png)

This is how it should be
![image](https://user-images.githubusercontent.com/43877959/80722842-75822f80-8b1d-11ea-847d-5454e166c717.png)

**Comment by HazelColaco19** [comment]
The values don't seem to update per values in forecast template

![image](https://user-images.githubusercontent.com/55691499/81046187-6ca2ac80-8ed5-11ea-860b-3a30fe69b4ee.png)


![image](https://user-images.githubusercontent.com/55691499/81046206-7a583200-8ed5-11ea-8705-94d36e23cb9f.png)

**Comment by HazelColaco19** [comment]
If value goes negative. The negative portion of the graph should be highlighted 

> Originally posted by @georgioajency in #532

**Comment by legred21** [comment]
API is sending values correctly. UI is not showing negative value

**Comment by nutank** [comment]
@Vaibhavarolkar please check this on priority

**Comment by HazelColaco19** [comment]
Negative values can now be seen


![image](https://user-images.githubusercontent.com/55691499/81175008-75bc7800-8fc0-11ea-8afc-335caca98766.png)
