### ISSUE TITLE
TASK - Re-order sync QB data to ES flow.

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#572]
The following should be the order in which the sync of QB data should occur in ES:
1. Sync accounts to ES and quickbook_account_categories table
2. After step 1 is complete, trigger syncing of :
   - purchases
   - journal entries
   - sales receipt
   - bills
   - invoices
3. On completion of Bills, trigger syncing of "Bill Payments"
4. On completion of Invoice, trigger syncing of "Payments"

**Comment by HazelColaco19** [comment]
This was tested post receipt of an email to login to QB. The order of the sync isn't tested, but post complete sync it has been checked if all the transaction from QB are shown in Kibana for those Categories.

![image](https://user-images.githubusercontent.com/55691499/81947472-388a6280-961e-11ea-81ff-a745b373f1e0.png)
