### ISSUE TITLE
SUBTASK - Import of CSV data of company

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#574]
Related to task - #557

**Comment by nutank** [comment]
@robiulpro need to handle following additional fields in import:

1. "user_email" - in user's csv  
2. At company level need to take following additional parameters:

- "wcr_min_ideal" - _optional, default = 1.0_
- "wcr_max_ideal" - _optional, default = 1.4_
- "qr_min_ideal" - _optional, default = 1.5_
- "qr_max_ideal" - _optional, default = 2.0_

**Comment by robiulpro** [comment]
Email sending task completed (except changes updated later)

**Comment by robiulpro** [comment]
all completed.

**Comment by HazelColaco19** [comment]
Import has been successful, with the added fields reflecting in " company table " under meta data.
