### ISSUE TITLE
SUBTASK - Send mail with link to connect to Quickbooks

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#575]
Related to task #557

**Comment by nutank** [comment]
@georgioajency please provide email content for this.

**Comment by georgioajency** [comment]
Your company's initial setup is complete. 

Click on the button below to connect Toppeq to Quickbooks Online to see your current cash flow and see how your business will perform by creating various scenarios.

![image](https://user-images.githubusercontent.com/43877959/81034836-078b8e80-8eb6-11ea-9425-7e5accc87260.png)

**Comment by robiulpro** [comment]
Completed.

**Comment by HazelColaco19** [comment]
The button needs to be styled per Georgio's design.

![image](https://user-images.githubusercontent.com/55691499/81667288-b7d23780-9460-11ea-8de4-52d9bbe54efd.png)

**Comment by robiulpro** [comment]
@Vaibhavarolkar could you please give me css for the button, i will add it to email template.

**Comment by Vaibhavarolkar** [comment]
@robiulpro 
Use this 
<a href="#" style="text-decoration: none;display: inline-block;"><img src="images/connect-to-qb-1.png" class=""/></a>
![connect-to-qb-1](https://user-images.githubusercontent.com/52398680/81776723-f1607c80-950c-11ea-8677-fb88c5ec886a.png)

**Comment by Vaibhavarolkar** [comment]
### <a href="#" style="text-decoration: none;display: inline-block;"><img src="images/connect-to-qb-1.png" class=""/></a>

**Comment by HazelColaco19** [comment]
Task completed. Remaining issue tracked in #702
