### ISSUE TITLE
SUBTASK - On connect to Quickbooks link click - Auto trigger syncing of past data

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#576]
Related to task #557

**Comment by robiulpro** [comment]
Completed.

**Comment by HazelColaco19** [comment]
On click of the link and completing the connection to QB, user lands on this screen which is plain and empty.

![image](https://user-images.githubusercontent.com/55691499/81675181-089b5d80-946c-11ea-872d-ee6c6d6dde9b.png)

@georgioajency Can we style it on a success event and have a verbiage like below?

" Your Quickbooks account has been connected successfully. We will let you know once you can start using the app. "

**Comment by georgioajency** [comment]
**Your QuickBooks account has been connected successfully. We will notify you once your data has been synced from QuickBooks.**

You can show an image if you want to show a connection between Toppeq and Quickbooks if you are finding it too empty

![image](https://user-images.githubusercontent.com/43877959/81678741-6bdabf00-946f-11ea-8d2a-6b45a0457010.png)

**Comment by HazelColaco19** [comment]
@Vaibhavarolkar

**Comment by HazelColaco19** [comment]
The above css applied

![image](https://user-images.githubusercontent.com/55691499/81835839-55606080-9560-11ea-9177-da5e9206f598.png)

**Comment by HazelColaco19** [comment]
Fixed
