### ISSUE TITLE
SUBTASK - On completion of syncing of past data send mail with login link

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#577]
Related to #557

**Comment by nutank** [comment]
@georgioajency please provide the email content.

**Comment by georgioajency** [comment]
**Subject**
Toppeq account synced to Quickbooks

Body
Hi,

Your Toppeq account is now synced with Quickbooks Online!

Click the button below to login to Toppeq and see your company's performance and current cash flow situation.
![image](https://user-images.githubusercontent.com/43877959/81035398-63571700-8eb8-11ea-92da-272dc6999f92.png)

**Comment by robiulpro** [comment]
Completed. There is a known issue where all the sns job not completed in sns tracker (actually all are completed), so the email might not send. We'll have to check the sns tracker issue.

**Comment by HazelColaco19** [comment]
1 issue: @robiulpro  the Text on button or Link should have been " Log In "

![image](https://user-images.githubusercontent.com/55691499/81778592-cb3cdb80-9510-11ea-957b-a5653ef6f12e.png)

1 change that needs to be done:

@Vaibhavarolkar can you provide @robiulpro with the button design?

**Comment by Vaibhavarolkar** [comment]
@robiulpro use this

style="text-decoration: none;display: inline-block;background-color:#dd7649; padding: 12px;font-size:20px;color: #fff;min-width: 200px;text-align: center;border-radius: 7px;"

<img width="803" alt="button-styles" src="https://user-images.githubusercontent.com/52398680/81783429-edd2f280-9518-11ea-9d2b-6264620be3cc.png">

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82202063-f82d2c00-991e-11ea-90f1-bbc9e18fa088.png)
