### ISSUE TITLE
TASK - Remove the extra charts from Projection dashboard / Cashflow Analysis page

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#579]
Remove the following from Projection Dashboard:

- [x]  Gross runway
- [x] - Net runway
- [x] - Top 3 upcoming expenses
- [x] - Top 3 upcoming income

Remove the following from Cashflow Analysis:

- [x] - Bank Accounts
- [ ] - Inflow by subcategory
- [ ] - Outflow by subcategory
- [x] - Quick Ratio
- [x] - Working Capital Ratio

**Comment by HazelColaco19** [comment]
These two graphs still visible on cash outflow page
 - Inflow by subcategory
 - Outflow by subcategory


![image](https://user-images.githubusercontent.com/55691499/81168701-1d33ad80-8fb5-11ea-82b1-1cea7090e19f.png)

**Comment by nutank** [comment]
@HazelColaco19 the reference was for pie chart that was in cashflow analysis not for the graphs.

![Screenshot 2020-05-06 at 5 58 07 PM](https://user-images.githubusercontent.com/7425622/81176730-2f1c4d00-8fc3-11ea-9ffe-11236887c6fa.png)

**Comment by HazelColaco19** [comment]
Yeah, got confused with names. Closing it.
