### ISSUE TITLE
TASK - A-36- Reduce column size for Principal Amount

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#581]
2. The column width for Principal Amount is still not reduced. @nutank can this be done or is there a reason why it is kept so large?

_Originally posted by @georgioajency in https://github.com/ajency/cashflow-issue-tracker/issues/475#issuecomment-620390654_

**Comment by HazelColaco19** [comment]
Still looks big to me


![image](https://user-images.githubusercontent.com/55691499/81168032-de512800-8fb3-11ea-9bb6-3c6bdf4f8ef5.png)

**Comment by HazelColaco19** [comment]
_Current problem:_ 
The reduced width of the column leads to broken UI ( columns ) and the text Principal Amount comes on two lines.

_Suggestion:_
Reduce the width of the column till it fits " Principal Amount " on one line.

OR

Reduce the width of the column and change the text to " Principal Amt " but fit the same on one line.

![image](https://user-images.githubusercontent.com/55691499/81256482-42c0c580-904e-11ea-941e-e876b50b3a8a.png)

@Vaibhavarolkar

**Comment by HazelColaco19** [comment]
Ignore. Looks fine on 100% zoom

![image](https://user-images.githubusercontent.com/55691499/81258767-127c2580-9054-11ea-8ef7-17cff3b26477.png)
