### ISSUE TITLE
BUG - A-46 - Closing cash balance for few projections (12 month & 24 month scenario) reflecting as zero

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#585]
**Current behavior:**

Closing cash balance for few projections (12 month & 24 month scenario) reflecting as zero

Projection ID: 18024
Link: https://client-uat.toppeq.com/cashflow/projection/18024/edit

Closing Cash Balance on Forecast template has a value

![image](https://user-images.githubusercontent.com/55691499/81073034-ab039000-8f04-11ea-8f47-23e07cca4fdc.png)

Projection DB: CCB value = 0

![image](https://user-images.githubusercontent.com/55691499/81073085-b9ea4280-8f04-11ea-856c-80975dc123a5.png)

**Expected Behavior:**

values in forecast template should match to the graph

**Comment by nutank** [comment]
@legred21 fixed this on ajency-qa server.

Issue used to occur when closing cash balance in projection dashboard for current month showed zero inspite of it being non-zero when that month had not inflow or outflow data

**Comment by HazelColaco19** [comment]
Tested on ajency-qa server for projections 79297, 79299, 76439 and none of the Closing Cash Value had a mismatch. It was found to be zero only when the forecast template had zero values  ( Feb 2019, March 2019 )
