### ISSUE TITLE
TASK - A-30 - Forecast Template should be highlighted in Orange simlar to Cashflow/Outflow section

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#590]
**Current Behavior:**

Forecast template tab is a part of CASHFLOW header.

Only headers are in orange.

![image](https://user-images.githubusercontent.com/55691499/81076902-df2d7f80-8f09-11ea-8de2-87fe076b1000.png)

**Expected:**

Forecast Template should be highlighted in Orange similar to Cashflow/Outflow section.

**Comment by HazelColaco19** [comment]
@georgioajency In this case, would there be a separate Header for forecast template or would it be kept orange under " Cashflow " itself?

**Comment by nutank** [comment]
Closing this, tracking in #637
