### ISSUE TITLE
BUG - Quickbooks Data table

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#591]
**F/B 1**
Accounts Receivables
Payment values should be negative

Same for Accounts Payable
Bill Payment should be negative

**F/B 2**
![image](https://user-images.githubusercontent.com/43877959/81137916-e68e7080-8f7d-11ea-9299-5d4f1d3fb804.png)

Dividend income - Split value should show Bank of America/Bank name as it is of type deposit

**F/B 3**
Journal entry for Plant & Machinery + Depreciation is missing (Dec 2019)
![image](https://user-images.githubusercontent.com/43877959/81138094-661c3f80-8f7e-11ea-82a8-22d17511139e.png)

**Comment by nutank** [comment]
@legred21 you would need to check "F/B 3 Journal entry for Plant & Machinery + Depreciation is missing (Dec 2019)"

**Comment by robiulpro** [comment]
@georgioajency 
Feedback 1 and 2 resolved. Please check.
Feedback 3 related to indexing, @legred21 will check.

**Comment by georgioajency** [comment]
Date range
Dec 2019 to Apr 2020

Bank
27/04 - Payment of $210 missing

Accounts Receivable 
22/.4 -  Sales of product income $367 (showing only payment of $33)
27/04 - Payment of $210 missing

Accounts Payable
After 12 March no data showing

**Comment by georgioajency** [comment]
@robiulpro 
Do not need to show + sign for amounts
-ve sign is fine

**Comment by legred21** [comment]
Journal Entry syncing is fixed

**Comment by nutank** [comment]
@legred21 for additional journal entries parent level category name, id and type shouldve been empty just like invoice and bills. But that is not the case. Check [kibana link here](http://13.234.21.219:5601/app/kibana#/discover?_g=()&_a=(columns:!(transactionType,qbParentId,qbAccountingCategoryId,qbAccountingCategoryName,parentPaymentCategoryType,amount,qbCategoryId,qbAccountCategory,toppeqCategory,toppeqActivityType,cashflowType),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:cashflowType.keyword,negate:!f,params:(query:Inflow,type:phrase),type:phrase,value:Inflow),query:(match:(cashflowType.keyword:(query:Inflow,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:companyId,negate:!f,params:(query:8,type:phrase),type:phrase,value:'8'),query:(match:(companyId:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Bill%20Payment',Purchase,'Journal%20Entry%20Credit','Journal%20Entry%20Debit',Deposit,Payment,'Sales%20Receipt',Invoice),type:phrases,value:'Bill%20Payment,%20Purchase,%20Journal%20Entry%20Credit,%20Journal%20Entry%20Debit,%20Deposit,%20Payment,%20Sales%20Receipt,%20Invoice'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Bill%20Payment')),(match_phrase:(transactionType.keyword:Purchase)),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Credit')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Debit')),(match_phrase:(transactionType.keyword:Deposit)),(match_phrase:(transactionType.keyword:Payment)),(match_phrase:(transactionType.keyword:'Sales%20Receipt')),(match_phrase:(transactionType.keyword:Invoice)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Journal%20Entry%20CREDIT','Journal%20Entry%20DEBIT'),type:phrases,value:'Journal%20Entry%20CREDIT,%20Journal%20Entry%20DEBIT'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Journal%20Entry%20CREDIT')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20DEBIT'))))))),index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

![Discover_Kibana](https://user-images.githubusercontent.com/7425622/81167670-3b98a980-8fb3-11ea-8cb3-e3b6a9bed72e.png)

**Comment by HazelColaco19** [comment]
F/b 1

..
![image](https://user-images.githubusercontent.com/55691499/81530663-ef68b300-937e-11ea-9aa5-de2a7623eb12.png).


........![image](https://user-images.githubusercontent.com/55691499/81530634-e1b32d80-937e-11ea-920f-2074aa0eea05.png)..
