### ISSUE TITLE
BUG - Some Journal entries dont have cashflowtype present

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#594]
[Kibana link ](http://13.234.21.219:5601/app/kibana#/discover?_g=()&_a=(columns:!(transactionType,qbParentId,qbAccountingCategoryId,qbAccountingCategoryName,parentPaymentCategoryType,amount,qbCategoryId,qbAccountCategory,toppeqCategory,toppeqActivityType,cashflowType),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:cashflowType.keyword,negate:!f,params:(query:Inflow,type:phrase),type:phrase,value:Inflow),query:(match:(cashflowType.keyword:(query:Inflow,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:companyId,negate:!f,params:(query:8,type:phrase),type:phrase,value:'8'),query:(match:(companyId:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Bill%20Payment',Purchase,'Journal%20Entry%20Credit','Journal%20Entry%20Debit',Deposit,Payment,'Sales%20Receipt',Invoice),type:phrases,value:'Bill%20Payment,%20Purchase,%20Journal%20Entry%20Credit,%20Journal%20Entry%20Debit,%20Deposit,%20Payment,%20Sales%20Receipt,%20Invoice'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Bill%20Payment')),(match_phrase:(transactionType.keyword:Purchase)),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Credit')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Debit')),(match_phrase:(transactionType.keyword:Deposit)),(match_phrase:(transactionType.keyword:Payment)),(match_phrase:(transactionType.keyword:'Sales%20Receipt')),(match_phrase:(transactionType.keyword:Invoice)))))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Journal%20Entry%20CREDIT','Journal%20Entry%20DEBIT',Bill),type:phrases,value:'Journal%20Entry%20CREDIT,%20Journal%20Entry%20DEBIT,%20Bill'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Journal%20Entry%20CREDIT')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20DEBIT')),(match_phrase:(transactionType.keyword:Bill)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:cashflowType.keyword,negate:!t,params:!(Outflow,Inflow,BALANCE),type:phrases,value:'Outflow,%20Inflow,%20BALANCE'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(cashflowType.keyword:Outflow)),(match_phrase:(cashflowType.keyword:Inflow)),(match_phrase:(cashflowType.keyword:BALANCE)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!t,params:!(future_expense),type:phrases,value:future_expense),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:future_expense))))))),index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

**Comment by legred21** [comment]
"Allowance For Bad Debts" in elastic is different from "Allowance for Bad Debts". case sensitive. Need to do case insensitive comparison

**Comment by legred21** [comment]
Fixed by changing category in db to "Allowance For Bad Debts"

**Comment by nutank** [comment]
Need a case insensitive check for qb detail type mapping. Keeping in backlog.

**Comment by HazelColaco19** [comment]
There are entries with cashflow Type value as null. 

[Link](http://13.234.21.219:5601/app/kibana#/discover?_g=()&_a=(columns:!(transactionType,qbParentId,qbAccountingCategoryId,qbAccountingCategoryName,parentPaymentCategoryType,amount,qbCategoryId,qbAccountCategory,toppeqCategory,toppeqActivityType,cashflowType),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:cashflowType.keyword,negate:!f,params:(query:Inflow,type:phrase),type:phrase,value:Inflow),query:(match:(cashflowType.keyword:(query:Inflow,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Bill%20Payment',Purchase,'Journal%20Entry%20Credit','Journal%20Entry%20Debit',Deposit,Payment,'Sales%20Receipt',Invoice),type:phrases,value:'Bill%20Payment,%20Purchase,%20Journal%20Entry%20Credit,%20Journal%20Entry%20Debit,%20Deposit,%20Payment,%20Sales%20Receipt,%20Invoice'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Bill%20Payment')),(match_phrase:(transactionType.keyword:Purchase)),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Credit')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20Debit')),(match_phrase:(transactionType.keyword:Deposit)),(match_phrase:(transactionType.keyword:Payment)),(match_phrase:(transactionType.keyword:'Sales%20Receipt')),(match_phrase:(transactionType.keyword:Invoice)))))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!f,params:!('Journal%20Entry%20CREDIT','Journal%20Entry%20DEBIT',Bill),type:phrases,value:'Journal%20Entry%20CREDIT,%20Journal%20Entry%20DEBIT,%20Bill'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:'Journal%20Entry%20CREDIT')),(match_phrase:(transactionType.keyword:'Journal%20Entry%20DEBIT')),(match_phrase:(transactionType.keyword:Bill)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:cashflowType.keyword,negate:!t,params:!(Outflow,Inflow,BALANCE),type:phrases,value:'Outflow,%20Inflow,%20BALANCE'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(cashflowType.keyword:Outflow)),(match_phrase:(cashflowType.keyword:Inflow)),(match_phrase:(cashflowType.keyword:BALANCE)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:transactionType.keyword,negate:!t,params:!(future_expense),type:phrases,value:future_expense),query:(bool:(minimum_should_match:1,should:!((match_phrase:(transactionType.keyword:future_expense)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',key:companyId,negate:!f,params:(query:14,type:phrase),type:phrase,value:'14'),query:(match:(companyId:(query:14,type:phrase))))),index:'5bf98340-726a-11ea-9bff-17296d6cdc0e',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

![image](https://user-images.githubusercontent.com/55691499/81941243-2ad0df00-9616-11ea-998a-dbe4f50166f9.png)

**Comment by HazelColaco19** [comment]
Fixed. Can be closed

![image](https://user-images.githubusercontent.com/55691499/82012309-2f88a800-9695-11ea-83f4-c072a75fa074.png)
