### ISSUE TITLE
BUG - Expenses from QB are not getting synced or reflected to Company 10 even if the mapping exists in PGADMIN for the categories

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#600]
**Current Behavior:**

Login to QB Account: 
Company 10 = AJ Top Target
username: nutan+1@ajency.in
Password: Ajency#123

Expenses were created for the month of May 2020 for one past date and three future dates.

![image](https://user-images.githubusercontent.com/55691499/81268116-25e3bc80-9065-11ea-848c-e47b947a2e5f.png)

Mappings exist for these expenes in PG Admin

![image](https://user-images.githubusercontent.com/55691499/81268307-693e2b00-9065-11ea-955f-6c12c1c8ebd7.png)

I created expenses for the same in company 10 account, upon sync and update of template it didn't show the values. 

Records do not show in **Quick Book Data** post SYNC

![image](https://user-images.githubusercontent.com/55691499/81268582-c3d78700-9065-11ea-826b-e49a89217d6f.png)

Records do not show in **Forecast Template** post UPDATE

![image](https://user-images.githubusercontent.com/55691499/81268727-eff30800-9065-11ea-87c1-b7023cca978b.png)

Checked Kibana, and it shows no data for month of May 2020

![image](https://user-images.githubusercontent.com/55691499/81268797-09944f80-9066-11ea-963c-bf64cd1a0f62.png)

In PG Admin, table sns tracker - there is no record of syncing for Company 10

![image](https://user-images.githubusercontent.com/55691499/81269045-655ed880-9066-11ea-8a36-d1789b2f93e1.png)

**Comment by legred21** [comment]
Refresh token had expired. Connected again and did resync

**Comment by HazelColaco19** [comment]
**Data now appears on Kibana:**

May 6, 2020 ( 1588723200000 ): 

![image](https://user-images.githubusercontent.com/55691499/81274524-0bfaa780-906e-11ea-87e2-97d3be8ea9a6.png)

May 14, 2020 ( 1589414400000 ):

![image](https://user-images.githubusercontent.com/55691499/81274715-4bc18f00-906e-11ea-8082-ecebdaacf1f7.png)


May 19, 2020 ( 1589846400000 )

![image](https://user-images.githubusercontent.com/55691499/81274761-5f6cf580-906e-11ea-8af5-d679689d6b26.png)


Values now appear on QB Data on Toppeq 

![image](https://user-images.githubusercontent.com/55691499/81275173-ecb04a00-906e-11ea-9387-d2d6bbd53453.png)


Also appear and reflect on Forecast template. 

Issue fixed. Closing the ticket

**Comment by nutank** [comment]
This reason for this issue needs to be fixed with https://github.com/ajency/cashflow-issue-tracker/issues/571 @robiulpro
