### ISSUE TITLE
BUG - The end balance for " Bank Of America " , range 1 Feb 2020 to 8 May 2020, is not matching. Also, deleted transaction is seen on Toppeq side

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#602]
**Current Behavior:**

1. QB Account: Flipmo > Reports > General Ledger Report > Date Range: 1 Feb 2020 to 8 May 2020 & Accounting Method = Accrual

2. Toppeq Side: https://ajency-qa.toppeq.com/cashflow/outflow/quickbook-data

Apply same date range

3. **For Category: Bank Of America** -  Compare the final record for the Month.
Two observations here:

a. the end balance does not match. On QB it is 67,286.68 and on toppeq it is 81,877.67
b. The last record on QB is dated to 5 May 2020 but on QB it is 6 May 2020. Not sure if any of the previously deleted records are still being displayed.

![image](https://user-images.githubusercontent.com/55691499/81378960-de713500-9125-11ea-91c7-88f06d2d15da.png)

**Expected Result:**

a. The end balance should match
b. The records should match as well

**Comment by nutank** [comment]
@HazelColaco19 - is the mis-match due to the deleted record or otherwise also there is a mis-match? 
If there is a mis-match otherwise also, then can you please mention the transaction that are present in QB but not present in toppeq's Kibana or vice versa.

**Comment by HazelColaco19** [comment]
@nutank I found there were extra records on Toppeq, so I assumed these are the deleted records. I did not find any record from QB which is not synced on Toppeq side and did not delete any records from QB since they are associated with Account Flipmo

**Comment by robiulpro** [comment]
It seems all these are deleted records. Should get fixed automatically once we start handling delete on elastic.

**Comment by HazelColaco19** [comment]
Closing Issue
