### ISSUE TITLE
TASK - Take the ideal values for WCR and QC from company meta rather than code

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#605]
Default values for it :
WCR min ideal = 1.0
WCR max ideal = 1.4
QR min ideal = 1.5
QR max ideal = 2.0

**Comment by legred21** [comment]
Please append the following json to existing company_meta json column in company table with the required values.
   "quickRatioMaxIdeal": 3,
    "quickRatioMinIdeal": 2.5,
    "workingCapitalRatioMaxIdeal": 2.4,
    "workingCapitalRatioMinIdeal": 2

If values are not configured, then following default values will be shown up in UI.
   "quickRatioMaxIdeal": 2,
    "quickRatioMinIdeal": 1.5,
    "workingCapitalRatioMaxIdeal": 1.4,
    "workingCapitalRatioMinIdeal": 1

**Comment by HazelColaco19** [comment]
Fixed


![image](https://user-images.githubusercontent.com/55691499/81927698-b3915000-9601-11ea-8da8-9d12025982df.png)


![image](https://user-images.githubusercontent.com/55691499/81927838-f4896480-9601-11ea-8e72-ecf2e0a59870.png)

![image](https://user-images.githubusercontent.com/55691499/81927875-00752680-9602-11ea-9bc3-2804a8d719fe.png)

**Comment by HazelColaco19** [comment]
Fixed. Tested on UAT server
