### ISSUE TITLE
BUG - Missing two decimal places in Amount field. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#606]
**Current behavior:**

Missing two decimal places in Amount field. The same has been implemented for Balance field.

![image](https://user-images.githubusercontent.com/55691499/81383193-41b29580-912d-11ea-8a75-aeb05c4670ed.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Can we maybe add some padding or increase the column width of the " Amount " field? Reason being for digits more than 5, the number goes to a second line 

![image](https://user-images.githubusercontent.com/55691499/81569192-94ee4780-93bc-11ea-9cc3-88bf2218da22.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/55691499/81575369-93c11880-93c4-11ea-9392-e85506602d58.png)
