### ISSUE TITLE
BUG - Missing a transaction of Type " Transfer " on 12 March 2020. QB Parent ID = 241

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#607]
**Current Behavior:**

On Toppeq, QB data side: Missing an expense record on 12 March 2020, Amount INR 15,000.

![image](https://user-images.githubusercontent.com/55691499/81385691-6c9ee880-9131-11ea-89ba-92f3189d878c.png)

The transaction QBparentID = 214  is missing on Kibana

![image](https://user-images.githubusercontent.com/55691499/81395666-aaa40880-9141-11ea-84ee-5ecf22308074.png)

**Comment by legred21** [comment]
Transfers are currently not synced to elastic

**Comment by nutank** [comment]
@HazelColaco19 - we aren't supporting "Transfers" in toppeq. You can move this issue to backlog milestone.

This should get handled when #593 is done.
