### ISSUE TITLE
BUG - Category: Accounts Receivable has records that are not present in Quickbook account ( deletd records ). Leads to improper balance

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#608]
**Current Behavior**

Extra entries or deleted entries visible on toppeq side ( tables ), are highlighted in blue below. Even post syncing the QB data, the records do not disappear. This leads to mismatch in  balance amount

![image](https://user-images.githubusercontent.com/55691499/81399799-4dac5080-9149-11ea-853a-f5ab4e2b2853.png)

**Comment by nutank** [comment]
@HazelColaco19 Is this a duplicate of https://github.com/ajency/cashflow-issue-tracker/issues/602 ?

For testing with consistency, best would be to empty ES and reindex the data again, this will not show the deleted records.

**Comment by legred21** [comment]
Syncing of deleted records from quickbook data is not handled yet

**Comment by HazelColaco19** [comment]
@nutank Yes it is a duplicate, later on clubbed all such categories in one issue. Since Syncing of records is not handled, I can close the issue.

**Comment by robiulpro** [comment]
deleting not handle for elastic records.

**Comment by HazelColaco19** [comment]
Closing this issue since delete is itself a different task
