### ISSUE TITLE
BUG - In QB account, the category says " Accounts Payable " but in the table on toppeq side, it says " Account Payable " 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#610]
**Correction:**

The category should match the one in QB account, as is. Should be " Accounts Payable "

QB Account
![image](https://user-images.githubusercontent.com/55691499/81401819-bd243f00-914d-11ea-8b03-67c70d5a31ec.png)

Tables on Toppeq side
![image](https://user-images.githubusercontent.com/55691499/81401881-e5ac3900-914d-11ea-94fe-46d48e9b30f5.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/81568429-658b0b00-93bb-11ea-95ef-45502a2e9d86.png)
