### ISSUE TITLE
BUG -  Bank related categories are not present in the dropdown

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#612]
Bank related categories are not present in the dropdown example " Bank Of America "

![image](https://user-images.githubusercontent.com/55691499/81408005-0da19980-915a-11ea-9433-65ee31158df7.png)

**Comment by robiulpro** [comment]
Bank, payable, receivable category added to category dropdown.

**Comment by HazelColaco19** [comment]
Bank Of America, Bank Charges and fees can also be seen added along with the ones mentioned above.
