### ISSUE TITLE
BUG - When sidebar is collapsed, the forecast template UI is broken

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#613]
![Toppeq (3)](https://user-images.githubusercontent.com/7425622/81408666-4726d480-915b-11ea-928a-2915e84b4631.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/81567949-b1898000-93ba-11ea-93ec-704438a02157.png)
