### ISSUE TITLE
TASK - Update the account receivables / account payables in "Avg days" formula as per data from ES rather than from QB data in company_cash table

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#614]
![Toppeq (4)](https://user-images.githubusercontent.com/7425622/81410641-b4883480-915e-11ea-958e-fd1d5b434fb7.png)

Formulas are as below:

_**Avg days to collect from customers  = (((Accounts receivables at the start + Accounts receivables as of today) / 2) / Sales) * Days (from start date till today)**_

where:
Accounts receivables at the start = Start date passed from UI (by default it will be the first date that we have for that account)
Accounts receivables as of end date = Accounts receivables from company_cash with end data same as the one passed (or current date by default)
Sales = Sum of all amounts for the QB accounting category of "Sale of Product Income" for the start and end date.
Days = End date (current date by default) - Start Date (start date of QB by default)

**_Avg days to collect pay to vendors = (((Accounts payable at the start + Accounts payable as of today) / 2) / COGS) * Days from start date till today_**   

where:
COGS = Sum of all amounts for the QB accounting category of "Cost Of Goods Sold" for the start and end date.
Days = End date (current date by default) - Start Date (start date of QB by default)

![2020-03-30 (2)](https://user-images.githubusercontent.com/7425622/77992514-d4e4f800-7343-11ea-9a9a-6f983ea1532e.png)

**Comment by nutank** [comment]
with this change , the cron for accounts receivable / payable can be disabled.

cc - @robiulpro

**Comment by legred21** [comment]
Accounts receivable / payable is now fetched from elastic and not from company_cash table

**Comment by HazelColaco19** [comment]
The values are not accurate for me. Shows a huge mismatch. Please verify

**Comment by HazelColaco19** [comment]
Issue tracked in #680 . Closing this task
