### ISSUE TITLE
BUG - Main Navigation header on top is sticky (as can be seen in UAT server). But seems to be non-sticky on QA server

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#615]
Header is sticky reference - https://client-uat.toppeq.com/cashflow/metrics

**Comment by HazelColaco19** [comment]
Sticky looks fixed, however the arrow appears on sticky on scroll

![image](https://user-images.githubusercontent.com/55691499/81847275-0242d980-9571-11ea-9709-f7ed74ec177c.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/81953784-b30ab080-9625-11ea-80d1-385cb71c5a81.png)
