### ISSUE TITLE
BUG - Accounting category not visible in tables on toppeq side ( Cash on Hand, salary payable )

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#617]
**Current Behavior:**

Out of the total Accounting Categories specified in QB account for range Jan 2018 till current date, two categories do not show up in the tables in Toppeq side.

![image](https://user-images.githubusercontent.com/55691499/81411225-b3a3d280-915f-11ea-9db0-dd1d42774a13.png)

**List of Categories missing:**

1. Cash on Hand

QBParent ID = 241

2. Salary payable

QBParent ID =  252

Analysis: the transactions for both categories above have transaction Type = " Transfers ".

**Comment by nutank** [comment]
@HazelColaco19 transactions of type "Transfers" has not been handled and is an open task #593.

Closing this as it will get handled only when #593 is completed.
