### ISSUE TITLE
BUG - Category " Travel ", qbparentid= 353:  Description is not displayed on the table in the toppeq website

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#620]
Descriptions are found missing in Kibana. Need to pass descriptions to kibana and display to the table

![image](https://user-images.githubusercontent.com/55691499/81417618-1483d880-9169-11ea-9cef-bbf61ec571a8.png)

**Comment by legred21** [comment]
Description exist in elastic

![image](https://user-images.githubusercontent.com/55079454/81433633-84eb2380-9182-11ea-82ee-eda83d983459.png)

**Comment by nutank** [comment]
Closing this issue - tracking in #627
