### ISSUE TITLE
BUG - Opening Balance of Category " telephone Charges " mismatches from QB entry

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#622]
Date Range: 1 feb 2020 - 8 may 2020

![image](https://user-images.githubusercontent.com/55691499/81419501-f4094d80-916b-11ea-881c-8761423b7fe9.png)

![image](https://user-images.githubusercontent.com/55691499/81419553-10a58580-916c-11ea-8794-a11b821fd779.png)

**Comment by nutank** [comment]
Closing this, tracking the ticket in https://github.com/ajency/cashflow-issue-tracker/issues/629
