### ISSUE TITLE
BUG - Salaries and wages : Opening balance mismatch. Range: 1 feb - 8 may, 2020

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#623]
ON QB account
![image](https://user-images.githubusercontent.com/55691499/81419902-ae00b980-916c-11ea-80f7-f0f0fb662f2c.png)

Toppeq table
![image](https://user-images.githubusercontent.com/55691499/81419811-7e51b180-916c-11ea-8fd8-3f0322e79b89.png)

**Comment by nutank** [comment]
Could be a possible duplicate of #622

**Comment by nutank** [comment]
Closing this, tracking the ticket in #629
