### ISSUE TITLE
BUG - Descriptions not being pulled in Kibana for Category Salaries and Wages

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#624]
QB

![image](https://user-images.githubusercontent.com/55691499/81420127-194a8b80-916d-11ea-9380-bbf50d7004d5.png)

Website

![image](https://user-images.githubusercontent.com/55691499/81420070-ffa94400-916c-11ea-87a2-182e69334d44.png)

**Comment by nutank** [comment]
Could be a possible duplicate of #620

**Comment by nutank** [comment]
Closing this issue - tracking in #627
