### ISSUE TITLE
BUG - Opening Balance not matching for Rent & Lease

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#625]
QB
![image](https://user-images.githubusercontent.com/55691499/81420268-5f075400-916d-11ea-9d11-a109845b9eac.png)

Website
![image](https://user-images.githubusercontent.com/55691499/81420305-6c244300-916d-11ea-908a-9f25c9a971b6.png)

**Comment by nutank** [comment]
Could be a possible duplicate of #622

**Comment by nutank** [comment]
Closing this, tracking the ticket in #629
