### ISSUE TITLE
BUG - A-02 - Category showed list where there was no information (Planned Outflow)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#631]
@legred21 

**Expected:** Categories that dont have data shouldnt show up in the dropdown of planned outflow list page

**Current Behaviour :** All categories are shown in the dropdown even if not part of "Planned Outflow"

**Comment by legred21** [comment]
Filters are fetched by company id and ouflow type

**Comment by HazelColaco19** [comment]
Currently can view categories taxes, travel, Others for company 14 and proj id = 91940


![image](https://user-images.githubusercontent.com/55691499/82297920-fcb21d00-99d0-11ea-8a02-c68c03144132.png)


It seems to miss out on " Operating Outflow Others " + " Purchase of Asset / Plant and Machinary " as it has data in the template

@legred21

**Comment by HazelColaco19** [comment]
Fixed


![image](https://user-images.githubusercontent.com/55691499/82308604-a13b5b80-99df-11ea-9db4-176199aca718.png)

![image](https://user-images.githubusercontent.com/55691499/82308624-ab5d5a00-99df-11ea-8c25-117fb70dd357.png)
