### ISSUE TITLE
BUG - A03 - Custom Amount should give from and till option. Currently it's two text boxes and even I can add from 5000 till 4000. Till should not take value lower than from

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#632]
**Issue:**

![image](https://user-images.githubusercontent.com/55691499/82874853-3ac0bb00-9f54-11ea-972c-598746c0da21.png)

**Expected:**

It should validate the range of values entered between " From and To " fields before making the search.

**Comment by robiulpro** [comment]
Added validation.

**Comment by HazelColaco19** [comment]
Even upon entry of a higer amount I get this validation

![image](https://user-images.githubusercontent.com/55691499/82998813-cc4c2d80-a025-11ea-8858-ff1c3d03e038.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/83008171-6a45f500-a032-11ea-90f2-871daf411c17.png)
