### ISSUE TITLE
TASK - A-05 - Classification list - should be in alphabatical order (Planned Outflow)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#634]
- The dropdown for "Accounting Category" should be listed in alphabetical order

**Comment by legred21** [comment]
API send Accounting Category filter values in alphabetical order

**Comment by HazelColaco19** [comment]
@legred21 Not fixed. The dropdown is not sorted in alphabetical order

![image](https://user-images.githubusercontent.com/55691499/82204847-3f1d2080-9923-11ea-94e9-7b4aeff1b675.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82298808-49e2be80-99d2-11ea-9002-71cf51407676.png)

**Comment by HazelColaco19** [comment]
Awaiting for clients comment on the ticket

**Comment by HazelColaco19** [comment]
The above sorting to be applied to toppeq headers as well as QB category screen

![image](https://user-images.githubusercontent.com/55691499/83226567-e6aa1680-a19f-11ea-88a4-43e5faff471b.png)

**Comment by HazelColaco19** [comment]
The above sorting has been applied to toppeq headers as well as QB category screen
