### ISSUE TITLE
TASK - A-06 - List should have save/ok button to update data and not back button

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#635]
- For recurring yes/no - give a tick button to set it rather than back action

- For dropdwon closing of it after selection to be retained"

**Comment by nutank** [comment]
This is hidden for now, till the react functionality is picked up.

**Comment by HazelColaco19** [comment]
Create Planned Expenses > Recurring Outflow > 

Have a Back button which does not save data. 

The  " Save " button will save the data. 

Logic of back button needs to be changed"

**Comment by robiulpro** [comment]
Done

**Comment by HazelColaco19** [comment]
Done

![image](https://user-images.githubusercontent.com/55691499/83515872-ae823b00-a4f3-11ea-8007-226f66a966d5.png)
