### ISSUE TITLE
BUG - A-08 - Everytime planned expense is added, it system throws issue message but outflow gets added

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#636]
- edit of due date gives error - #539 
- error when no QB category is passed - #538 
- added with one date, but got displayed against another error - @HazelColaco19 please test the add planned outflow flow and see if this can be replicated
- sometimes error message is shown but outflow gets added -  @HazelColaco19 please test the add planned outflow flow and see if this can be replicated
- Added few entries in Planned outflow( Mumbai Office rent for 10th may, Mumbai office rent for 11th May, Stationary expense) however none of these showed up in planned outflow (A-52) @HazelColaco19 please test the add planned outflow flow and see if this can be replicated

@HazelColaco19 please report any other issues you see with add of planned expense flow in this ticket.

**Comment by legred21** [comment]
One of the check was notify array was blank

**Comment by HazelColaco19** [comment]
- [ ] edit of due date gives error - #539
- [ ] error when no QB category is passed - #538
- [ ] added with one date, but got displayed against another error - @HazelColaco19 please test the add planned outflow flow and see if this can be replicated
- [ ] sometimes error message is shown but outflow gets added - @HazelColaco19 please test the add planned outflow flow and see if this can be replicated
- [ ] Added few entries in Planned outflow( Mumbai Office rent for 10th may, Mumbai office rent for 11th May, Stationary expense) however none of these showed up in planned outflow (A-52)
