### ISSUE TITLE
TASK - A-18 / A- 30 - Rename Quickbook Data to QuickBooks Data / Forecast Template should be highlighted in Orange simlar to Cashflow/Outflow section

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#637]
![image (14)](https://user-images.githubusercontent.com/7425622/81510760-de458500-9331-11ea-8b80-e966fdfa1ae6.png)

**Comment by georgioajency** [comment]
@nutank there will be a follow-up task to this. 

He wants graphs from the current cashflow metrics to be moved into Key Metrics

And Projection dashboard name will change to Cashflow Analysis.

Variance charts page will be empty

**Comment by HazelColaco19** [comment]
1. Rename Quickbook Data to QuickBooks Data -----> Rename to " QuickBooks Data ". I can still see the word " Transactions "

2. Forecast Template should be highlighted in Orange simlar to Cashflow/Outflow section ----> Done


![image](https://user-images.githubusercontent.com/55691499/82212290-edc75e00-992f-11ea-86cb-a30dcecbc08e.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82319302-ed41cc80-99ee-11ea-9953-2da351b170cb.png)
