### ISSUE TITLE
TASK - A-13 - Can we have a consistent text & Date format irrespective of inputs from messaging app

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#638]
"Enhancement

All dates in filters(dd-mm-yyyy if not in string form) and otherwise should be in - ""07 May 2020"""

**Comment by HazelColaco19** [comment]
In Planned Transactions: Date filter should be like QuickBooks Transactions

OR

Change the date dropdown format to "" DD-MM-YY"" format"

**Comment by robiulpro** [comment]
Changed the date dropdown format to "" DD-MM-YY"" on planned expense page.

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/83517318-526ce600-a4f6-11ea-84d0-ff3e493f77aa.png)
