### ISSUE TITLE
TASK - A-32 - Average & Last month not on header level

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#641]
Refer - TASK - Forecast template - We need to show the values at the total levels. Not being handled currently. #580

**Comment by HazelColaco19** [comment]
The values should be on header level for both mentioned above

![image](https://user-images.githubusercontent.com/55691499/83227857-be6fe700-a1a2-11ea-97ee-fc2c214e4930.png)

**Comment by robiulpro** [comment]
Done.

**Comment by HazelColaco19** [comment]
Screen reset to 100%, when the menu is open ---> The " Principal Amount " column breaks upon selection of " Avg " value in the header 

@Vaibhavarolkar Increase the column size to fit the largest of the number as shown in the image

![image](https://user-images.githubusercontent.com/55691499/83516371-8e9f4700-a4f4-11ea-9254-a75232554a71.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/83634554-5cf3b200-a5c0-11ea-8988-0104de1e45ca.png)
