### ISSUE TITLE
BUG - A-38 -Top upcoming inflows - can see accounts receivable $80000 for worst case scenario however there is no a/c receivables in projection template

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#643]
Refer to UAT server for details.

**Comment by nutank** [comment]
@legred21 what was the issue here?

**Comment by legred21** [comment]
category from past cashflow was not considered while fetching data

**Comment by HazelColaco19** [comment]
This needs to be tested on UAT server as the template and projection belongs to the one on UAT server. Cannot be tested on Ajency server and fix has not be pushed yet to UAT server per label

**Comment by HazelColaco19** [comment]
@legred21 @nutank 

![image](https://user-images.githubusercontent.com/55691499/82343485-8b925a00-9a10-11ea-98e8-3fded500a9f2.png)


![image](https://user-images.githubusercontent.com/55691499/82343924-0c515600-9a11-11ea-88b4-ce813c5647f0.png)

Company - Quant

For June 2020, can see accounts receivable $80000 for worst case scenario however there is no a/c receivables in projection template

**Comment by legred21** [comment]
"Accounts Receivable" can be seen in past_cashflow for projection id 4077
![image](https://user-images.githubusercontent.com/55079454/82403029-83233900-9a7b-11ea-8aac-49e80c8b7794.png)

"Accounts Receivable" also can be seen in future_cashflow for projection id 4077
![image](https://user-images.githubusercontent.com/55079454/82403046-8c140a80-9a7b-11ea-8ec0-7e31f37ea1cf.png)

"Accounts Receivable" is not populated in forecast template 
![image](https://user-images.githubusercontent.com/55079454/82403392-5b80a080-9a7c-11ea-9e6d-8bce31124394.png)

**Comment by nutank** [comment]
@legred21 does "Accounts Receivable" have a mapping in toppeq detail type and quickbook detail type mapping table?

**Comment by HazelColaco19** [comment]
Doesn't look fixed to me.

![image](https://user-images.githubusercontent.com/55691499/82526066-a0760700-9b50-11ea-9f6a-4a6fafff91b6.png)

**Comment by HazelColaco19** [comment]
@robiulpro  The mapping seems to be present. Can you please look.

![image](https://user-images.githubusercontent.com/55691499/82530131-37938c80-9b5a-11ea-8bf0-e7c1881869d1.png)

**Comment by robiulpro** [comment]
@HazelColaco19 
Fixed by changing the 'quickbook_accounting_category_id' in past and future cashflow table with the actual id (44). Not sure why the wrong id was generated in past cashflow and future cashflow table.

**Comment by HazelColaco19** [comment]
Fixed, can see the value populating for that scenario 

![image](https://user-images.githubusercontent.com/55691499/82989054-b46dad00-a017-11ea-8411-bce340b9d569.png)
