### ISSUE TITLE
BUG - A-39 - Unable to create projection with name already deleted from system

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#644]

**Comment by legred21** [comment]
Removed unique constraint from db by migration and entity level

**Comment by HazelColaco19** [comment]
Marked the status of the scenario ' delete ' = true.
It disappeared from UI but the entry does remain in the DB table. Can still be closed. 


![image](https://user-images.githubusercontent.com/55691499/82291317-637e0900-99c6-11ea-861f-c25c82dc44d9.png)


![image](https://user-images.githubusercontent.com/55691499/82291290-5a8d3780-99c6-11ea-9b9a-ef3e06a0780c.png)
