### ISSUE TITLE
BUG - A-16 - There is a substantial time lag in the syncing function, Syncing of QB with Toppeq

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#647]
- there will be lag for closing cash as it is report API

- Nutan to give how long it takes to update.

- Aditya/Omkar to let us know if it can be replicated when updating aggregated data for forecast template

**Comment by nutank** [comment]
Omkar reported:

"Sync is working fine at our end, almost real time, except the closing balance of QB still remains un-updated"

**Comment by HazelColaco19** [comment]
Can be closed. Aditya closed the ticket on the sheet post updating him about the behavior.
