### ISSUE TITLE
TASK - Notifications for Runway (both), WCR and QR

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#649]
- [x] - Can configure both the values for all the graphs. There will be a setting cog which allows you to set the ideal range value
- [x] - Notify via Email and Whatsapp
- For now, all users in the company will be notified
- For now, the graph setting values will not be user-specific
- Need to come up with an email id suggestion for sending out these notification email (Hazel can check what is the commonly used email id)

- [ ] - For a company level, it can configure the repeat functionality. 

This will be 

- [ ] - Daily - If values are out of range, the user will be notified on a daily basis until there are no issues.
- [ ] - Weekly - Same as above. However, if all was good and mid of the week, a value falls below a limit then a notification should be triggered the next day and weekly will follow
- [ ] - Monthly - Same as above
-  Only once - Happens once if a value goes negative. Resets if any of the value returns to normal

- [x] - This setting can be kept under settings on the side panel. Simple screen with a single dropdown.
- [ ] - Since there are multiple projections, the message will be consolidated. i,e all projections whose values are out of bounds will show in a single mail.

**Comment by nutank** [comment]
@georgioajency / @HazelColaco19 please provide with the email template and subject for each of the mail types.

**Comment by georgioajency** [comment]
Your weekly updates for the Toppeq cashflow projections are below (cash emoji)

**Gross Runway** _(All values less than 8 months)_
Projection 1: **6 months**
Projection 1: **6 months**
Projection 1: **6 months**

**NetRunway** _(All values less than 8 months)_
Projection 1: **6 months**
Projection 1: **6 months**
Projection 1: **6 months**

**Working Capital Ratio** _(Ideal range: 1.5 to 2.0)_
Projection 1: **3.5**
Projection 1: **1.2**
Projection 1: **2.1**

**Quick Ratio** _(Ideal range: 1.0 to 1.5)_
Projection 1: **0.8**
Projection 1: **1.6**
Projection 1: **2.1**

**Comment by georgioajency** [comment]
Currently being discussed with Aditya

**Comment by georgioajency** [comment]
![](https://files.slack.com/files-pri/TNYV6V97Z-F013ERPPL93/image.png)

https://www.figma.com/file/4yIWjQbjEC9hj4CPGwj8pm/Toppeq?node-id=3207%3A145

Email template

**Comment by nutank** [comment]
@legred21 - WCR and QR are not projection based so lets show a direct value in whatsapp and email template

**Comment by Vaibhavarolkar** [comment]
@legred21 @nutank Email template HTML
[toppeq-email.zip](https://github.com/ajency/cashflow-issue-tracker/files/4656398/toppeq-email.zip)

**Comment by nutank** [comment]
@legred21 - mention which columns store the setting info.

**Comment by nutank** [comment]
@legred21 please write the logic for the cron endpoint.

**Comment by nutank** [comment]
@legred21 / @robiulpro - as confirmed from Urmi on call, we dont need to handle "only once" option. We would only have 3 options - daily, weekly and monthly.

**Comment by robiulpro** [comment]
UI Implementation Done.

**Comment by HazelColaco19** [comment]
Bugs raised in 
#771 
#772

**Comment by HazelColaco19** [comment]
Fixed
