### ISSUE TITLE
TASK - Major expenses not projected for | Key Metrics

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#650]
- [x] - Ability to add an item inline
- [x] - A line item will have Qty, Item name, and Total price
- [x] - Delete a line item
- [x] - Cannot add a negative price
- [x] - Max of 5 line items to be shown. Pagination if there are more than 5
- [x] - Sorted by last updated first.
- [x] - Need to save create time and last update time

![image (15)](https://user-images.githubusercontent.com/7425622/81511730-143a3780-9339-11ea-9898-b84ce077cb3d.png)

**Comment by nutank** [comment]
@georgioajency / @HazelColaco19 will need the following:
- How will the paginated UI look like?
- Should the user be allowed to change the sorting?

**Comment by georgioajency** [comment]
![image](https://user-images.githubusercontent.com/43877959/81530417-75d0c500-937e-11ea-8d10-ac2a7bebc838.png)

Follow this UI and its application

**Comment by robiulpro** [comment]
Table:
====
id
company_id
description/name
qty
amount
created
updated

CRUD API (graphql):
===============
 - Create new expense
- Edit
- Delete
- Fetch (with pagination)

Validation:
=========
 - Cannot add a negative price
 - All are mandatory field

**Comment by nutank** [comment]
@robiulpro / @legred21 we will need this against a projection id. Since this data is projection based. Got a confirmation from Aditya.

**Comment by robiulpro** [comment]
UI Implementation done.

**Comment by robiulpro** [comment]
@Vaibhavarolkar 
Please check the edit modal input boxes, currently sizes are not proper, please fix.
Branch: ajency-feature/robiul/major-expenses

**Comment by HazelColaco19** [comment]
Feedback from Aditya

- [ ] change " Amount " to " Total Amount 
- [ ] and add the same in edit pop up

- [ ] Also make the Quantity field not mandatory ( there can be land purchase, and we cannot add quantity as 1 or any for such an expense. so better is if its not mandated )

**Comment by HazelColaco19** [comment]
@robiulpro  if we enter 0 amount there is no validation? clicking on " Add " button shows nothing

![image](https://user-images.githubusercontent.com/55691499/83486741-6d743180-a4c7-11ea-85b6-d66e5725e7a6.png)

**Comment by robiulpro** [comment]
Done.

**Comment by HazelColaco19** [comment]
All the marked issues done. closing the ticket assuming " Dollar " or currency sign cannot be added while typing in the Total amount value. So it will not be displayed as well.
