### ISSUE TITLE
BUG - Company Setup - qb_app_url and qb_start_date is not being updated in company_quickbook_accounts table

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#653]
Company ID : 1

![image](https://user-images.githubusercontent.com/55691499/81777141-db06f080-950d-11ea-8c93-3d99fc741d30.png)

**Comment by robiulpro** [comment]
fixed.

**Comment by HazelColaco19** [comment]
It now populates in the table
