### ISSUE TITLE
BUG - A-55 - Average days to collect from Customers/vendors shows blank (image send on group)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#656]
Refer UAT server - 
![image (16)](https://user-images.githubusercontent.com/7425622/81648185-e560b600-944b-11ea-89ec-962ee3f4a340.png)

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/81652442-61a9c800-9451-11ea-866d-d92ac24d74c3.png)
COGS and SOPI showing zero amount in db

**Comment by nutank** [comment]
@robiulpro please check if pnl_cogs cron is failing or not.

**Comment by robiulpro** [comment]
IT was due to authentication error. I can see data now. 
to be fixed in #571

**Comment by HazelColaco19** [comment]
Can see data now for the same date range ( 1 Jan 2020 - 11 May 2020 ), company = Flipmo.

![image](https://user-images.githubusercontent.com/55691499/82212121-a9d45900-992f-11ea-9e4c-2939108f09f7.png)
