### ISSUE TITLE
TASK - A-56 , A-57 Side bar and graph page changes

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#657]
@nutank there will be a follow-up task to this. 

A-56  - He wants graphs from the current cashflow metrics to be moved into Key Metrics
- Average Days to Collect From Customers
- Average Days to Pay Vendors

And Projection dashboard name will change to Cashflow Analysis.

_Originally posted by @georgioajency in https://github.com/ajency/cashflow-issue-tracker/issues/637#issuecomment-626460201_

**Comment by nutank** [comment]
He mentioned once we do the drop down to select between operating, investing, and financing for the Cash In vs Cash out (Projection dashboard), the Cash Inflow by Category, and Cash Outflow by Category which is currently on Cashflow Analysis page will be useless and can be removed.

Variance charts page will be empty

**Comment by HazelColaco19** [comment]
Task completed.

![image](https://user-images.githubusercontent.com/55691499/82210877-7e506f00-992d-11ea-9138-3d42498a7b60.png)
