### ISSUE TITLE
The Company should be dynamically reflected in the Company drop down

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#660]
**Current Problem:**

When a company is added and synced to QB account - it shows a success status in tables ( db ) but does not reflect the added company in the UI 
Currently looks hardcoded.

![image](https://user-images.githubusercontent.com/55691499/81670251-f7028780-9464-11ea-8d06-2172623f7ce3.png)

**Expected:**

Pull the values of Company names from Company table and display it in the format as shown currently:

< Company name > - < id >

**Comment by robiulpro** [comment]
Completed.

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/81928060-4d58fd00-9602-11ea-90ed-b67f3134ea9a.png)
