### ISSUE TITLE
BUG - The records on Kibana do not match with the records in QB

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#662]
**Current Behavior:**

The records on Kibana do not match with the records in QB

_Missing transaction IDs on Kibana with the type:_

**Type - TxnId**
1. Expense - 1018

**Comment by robiulpro** [comment]
@legred21 please check this.

**Comment by HazelColaco19** [comment]
Closing the ticket. Entry is seen on Kibana.
