### ISSUE TITLE
BUG - A-59/A-60/A-61 - QB closing balance not reflected in forecast template correctly

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#663]
- Quickbooks closing balance not reflected in the forecast template for eg: in forecast template TEST050520 III QB Closing bal. is zero across | A-59
 
- Opening balance for the past data in the forecast is negative, even though it is positive in the QB data (refer Test050520 III) | A-60
 
- New forecast created on the basis of QB past data is unable to pull the opening balance from QB (Refer Template 13 May 20) | A-61

Refer to UAT server.

**Comment by nutank** [comment]
- Syncing from QB was failing due to auth token error - https://github.com/ajency/cashflow-issue-tracker/issues/571

**Comment by HazelColaco19** [comment]
Closed by client
