### ISSUE TITLE
BUG - Error while creating a new projection template in Forecast Template

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#665]
**Note:**

There are no projections created for this company and still it gives the error as shown in the image.

![image](https://user-images.githubusercontent.com/55691499/81791912-f9c4b180-9524-11ea-8035-058499a77d54.png)

**Comment by HazelColaco19** [comment]
Forecast template can now be created but the screen goes blank after creation.

company 1 - id 87736

![image](https://user-images.githubusercontent.com/55691499/81841131-960fa800-9567-11ea-9dd1-0437f4f33a66.png)



On click of " Cashflow Analysis " , you can see the created projection here.

![image](https://user-images.githubusercontent.com/55691499/81841175-aa53a500-9567-11ea-9a6c-21e177f7ac2c.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Can be created now. Closing the ticket

**Comment by HazelColaco19** [comment]
Company Id= 32. 


![image](https://user-images.githubusercontent.com/55691499/82533312-9fe56c80-9b60-11ea-97ee-744bc2c46e7a.png)


response in network

{"data":null,"errors":[{"message":"Internal Server Error(s) while executing query","path":null,"extensions":null}]}


![image](https://user-images.githubusercontent.com/55691499/82533344-b25fa600-9b60-11ea-856d-24de8a3cd9d2.png)

**Comment by legred21** [comment]
I was connecting to server db from my local machine without removing unique constraint in projection class. Due to which unique constraint is to get applied on projection table. removed unique constraint from Projection class

**Comment by HazelColaco19** [comment]
Able to create a template now. Closing the ticket.
