### ISSUE TITLE
BUG - The mappings in " Quickbook_category_mapping_config " table are incorrect

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#666]
**Current Behavior:**

In Pg admin, the table, " Quickbook_category_mapping_config " we can see that the toppeq category detail type is incorrectly mapped to qb category detail type. 

Pg admin screenshot:
![image](https://user-images.githubusercontent.com/55691499/81795219-82dde780-9529-11ea-9ebc-d05ab9c12acf.png)

CSV screenshot:
![image](https://user-images.githubusercontent.com/55691499/81795487-ccc6cd80-9529-11ea-81c8-00202e838e14.png)

Toppeq Detail File:
https://drive.google.com/open?id=1X3ubapWBq5FjTd_f3vosLSGRfuqDo7qe

Quickbook Mapping file:
https://drive.google.com/open?id=1X3ubapWBq5FjTd_f3vosLSGRfuqDo7qe

**Expected:**

Since that mapping did not exist in Toppeq category file, it should have been either empty or mapped as is on csv

**Comment by robiulpro** [comment]
Could not replicate.
