### ISSUE TITLE
BUG - UI issues in release branch - may 4-8 release

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#671]
- [ ] UI for forecast template is broken after latest UI changes

![Screenshot 2020-05-14 at 1 23 28 AM](https://user-images.githubusercontent.com/7425622/81858557-90bf5700-9581-11ea-9288-bbe4068d647c.png)

- [x] The side bar order of menu items is not as per requirement. Additional "Analytics" should not be there. 3rd menu is "Variance Charts" which is empty - #637
 Please see image below:
![image (14)](https://user-images.githubusercontent.com/7425622/81510760-de458500-9331-11ea-8b80-e966fdfa1ae6.png)

- [x] A-56 - "Average Days to Collect From Customers" and "Average Days to Pay Vendors" needs to be moved into Key Metrics **below WCR and quick ratio**. It is built based on date logic not based on projection. #657

- [x] Account receivable/ and Payables in  "Average Days to Collect From Customers" and "Average Days to Pay Vendors" is overlapping with the sticky header
![Screenshot 2020-05-14 at 6 43 32 AM](https://user-images.githubusercontent.com/7425622/81881683-6fc12b00-95ae-11ea-809f-215ec05fe980.png)

- [x] Working Capital Ratio & Quick ratio is overlapping with the sticky header
![Screenshot 2020-05-14 at 6 45 54 AM](https://user-images.githubusercontent.com/7425622/81881823-c9c1f080-95ae-11ea-80fa-a22a16ebab30.png) - #586

- [x] The Side bar is going under the sticky header.

![Screenshot 2020-05-14 at 6 19 29 AM](https://user-images.githubusercontent.com/7425622/81880403-11467d80-95ab-11ea-8834-dc95c4dbf6c3.png)

**Comment by Vaibhavarolkar** [comment]
Unable to replicate the forecast UI issue @nutank 
<img width="946" alt="forecstUi" src="https://user-images.githubusercontent.com/52398680/81892718-7315e000-95c9-11ea-98f1-b0a6dc4b9cdb.png">
<img width="946" alt="forecstUi-1" src="https://user-images.githubusercontent.com/52398680/81892724-7610d080-95c9-11ea-92be-361fe4c70505.png">

**Comment by HazelColaco19** [comment]
Looks proper to me. Closing the ticket

![image](https://user-images.githubusercontent.com/55691499/81941663-c2363200-9616-11ea-84cf-4052a2de9385.png)
