### ISSUE TITLE
TASK - Do not allow connect to QB account, if that realm id is already mapped to some other company

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#673]

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Edit the error message to " Error connecting to Quickbooks as the same Quickbook account is already in use. " @robiulpro 

![image](https://user-images.githubusercontent.com/55691499/82220709-9da2c880-993c-11ea-9781-a43214b9d2d6.png)

**Comment by HazelColaco19** [comment]
Fixed
