### ISSUE TITLE
BUG - Bank accounts not changing when company dropdown is changed

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#675]

**Comment by robiulpro** [comment]
fixed

**Comment by HazelColaco19** [comment]
Banks changed and reflected post switch between companies

AJ top target:

![image](https://user-images.githubusercontent.com/55691499/81928719-59918a00-9603-11ea-94a5-b84c70140a5c.png)

Flipmo:

![image](https://user-images.githubusercontent.com/55691499/81928753-6c0bc380-9603-11ea-839a-0c7b0236e37b.png)
