### ISSUE TITLE
BUG - Closing cash balance graph not visible on "Cashflow Analysis" page (Projection dashboard page)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#679]
![Toppeq (5)](https://user-images.githubusercontent.com/7425622/81930212-e89fa180-9605-11ea-8198-e37b1b61b6e1.png)

**Comment by HazelColaco19** [comment]
Fixed
![image](https://user-images.githubusercontent.com/55691499/81950599-c287fa80-9621-11ea-8368-40c45e63eedf.png)
