### ISSUE TITLE
BUG - The values are not accurate for me. Shows a huge mismatch. Please verify.

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#680]
The values are not accurate for me. Shows a huge mismatch. Please verify.

Range: May 1, 2020 - May 14, 2020

Accounts receivables at the start = 386161
Accounts payable at the start = 92494

Accounts receivables at the end = 375911
Accounts payable at the end = 92494

Days = 13

COGS = 32600

SOPI = 62100

Average days to collect from customers = (((386161+375911)/2)62100)*13 = 79.76

Average days to pay vendors = (((92494+92494)/2)32600)*13 = 36.8841104294

![image](https://user-images.githubusercontent.com/55691499/81933220-a7f65700-960a-11ea-898b-d5ad5c651c27.png)

_Originally posted by @HazelColaco19 in https://github.com/ajency/cashflow-issue-tracker/issues/614#issuecomment-628563247_

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/81941042-efceab80-9615-11ea-8e50-2928e88de790.png)

![image](https://user-images.githubusercontent.com/55079454/81941142-0bd24d00-9616-11ea-9499-6a75368b37a9.png)

Values sent by API are not reflected in UI

**Comment by HazelColaco19** [comment]
@robiulpro

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
This was found fixed when tested 6 days ago during sanity check.
