### ISSUE TITLE
TASK - Cash In and Cash Out graph color changes 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#683]
![Cash In  3](https://user-images.githubusercontent.com/7425622/81940924-c31a9400-9615-11ea-890d-382efbab7658.png)

**Comment by HazelColaco19** [comment]
Graph in design are curved on the edges, but whats developed is sharp edged. @Vaibhavarolkar 

![image](https://user-images.githubusercontent.com/55691499/81954138-1d235580-9626-11ea-8775-b202f7cdc2d4.png)

**Comment by HazelColaco19** [comment]
As discussed with the Georgio, the graph doesnt need curved edges. Can be closed
![image](https://user-images.githubusercontent.com/55691499/82202914-35de8480-9920-11ea-9091-f26eaf9e6351.png)
