### ISSUE TITLE
BUG - Forecast template values dont match

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#685]
Jan 2019 - closing cash difference = 0

Feb 2019 - 

- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB = 

March 2019 - 
- Inflow - QB = $35,650.00  , Kibana = 0 entries => Missing Transaction id = [284](https://c43.qbo.intuit.com/app/recvpayment?txnId=284)
- Outflow - QB = 

Apr 2019 -  
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB = 

May 2019 - 
- Inflow - QB = 3 records , Kibana = 1 records |  Missing Transaction id = [213](https://c43.qbo.intuit.com/app/recvpayment?txnId=213) , [286](https://c43.qbo.intuit.com/app/recvpayment?txnId=286)
- Outflow - QB = 

June 2019 - 
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB =  

July 2019 - 
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB = 

August 2019 - 
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB =

Sep 2019 - 
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB =  

Oct 2019 - 
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB =  

Nov 2019 - 
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB = 

Dec 2019 -  
- Inflow - QB = 0 records , Kibana = 0 records
- Outflow - QB =

**Comment by nutank** [comment]
There are multiple records giving mismatch. 

Fixed currently by emptying and re-indexing but can be closed only once tested with import flow.

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/82023958-a7ae9800-96ac-11ea-9123-25120277ca5e.png)


![image](https://user-images.githubusercontent.com/55079454/82024007-bac16800-96ac-11ea-95fd-671917f8e541.png)

**Comment by HazelColaco19** [comment]
Closing this ticket. Will be handled in #715
