### ISSUE TITLE
BUG - Cannot Create a forecast template for a newly imported QB company

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#688]
![Screenshot 2020-05-15 at 3 05 05 AM](https://user-images.githubusercontent.com/7425622/81988624-680a9080-9659-11ea-87b5-3aba4f8ebbab.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by nutank** [comment]
Issue was due to duplicate entry of "Utilities" in quickbook detail type mapping.

**Comment by HazelColaco19** [comment]
Fixed for a new company

![image](https://user-images.githubusercontent.com/55691499/82224489-84504b00-9941-11ea-8c6a-3df1e74d9333.png)
