### ISSUE TITLE
BUG - Add planned expense opens a blank detailed view page instead of creating the expense for company 22

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#689]
- A planned expense added for company id 22, takes to a blank page having url of the following kind

https://ajency-qa.toppeq.com/cashflow/outflow/planned#/details/1266333a-b252-440d-ba17-0256f3ca9745

**Comment by nutank** [comment]
Cannot add planned expense for any company

**Comment by nutank** [comment]
This happened since user_meta was missing for a user in user's table.

**Comment by nutank** [comment]
- handled in company setup import by importing usermeta in user's table

**Comment by HazelColaco19** [comment]
Can create Planned expense for the following:

1. Company 21:

![image](https://user-images.githubusercontent.com/55691499/82215497-21f14d80-9935-11ea-8a40-cff7adf8c4b3.png)



2. Company 45:

![image](https://user-images.githubusercontent.com/55691499/82215594-4c430b00-9935-11ea-8a83-74562b3b82be.png)


Closing the ticket.
