### ISSUE TITLE
TASK - A-62, A-63, A-64 - Display name change for QB accounting categories in Forecast template

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#690]
A-62 - Rename "Sale of Product Income" / "Sale of Service" to "Collection from Debtors" 

A-63 - Rename "Cost of Good sold" to "Payment to Creditors" 

A-64 -  Rename "Sales" to "Cash Sales" 

@robiulpro - can we have this mapping in the DB somewhere so we can change if the client asks us to change it again.

**Comment by robiulpro** [comment]
Completed.
Update the corresponding display value in 'quickbook_account_categories' table under 'display_name' column.

**Comment by HazelColaco19** [comment]
CoGS does seem to have been changed

![image](https://user-images.githubusercontent.com/55691499/82629552-b1d11900-9c0d-11ea-850a-c8c99620e632.png)

**Comment by nutank** [comment]
@HazelColaco19 , yes only for QB categories and not toppeq categories
> @nutank should this change reflect just to QB categories or even Toppeq categories? If you note the

@HazelColaco19 , for now they only needed these 2, we have made it flexible for later change if needed. If these values are being shown anywhere else other than template please make sure that is also tested
> @nutank also, if in future the clients want a name change, who will do the name change in DB? At the moment, I feel this is a feature but the client will be dependant on us to use the same unless they know to dig in DB. The future aspect..

**Comment by HazelColaco19** [comment]
@nutank For your second point above, the main Toppeq category is shown in graphs ( Key metrics page  ) and not the sub categories where name change has been applied.

@robiulpro Additionally,  for **planned expense** tested to check if the mapping shows updated, but it shows the previous text " Sales " and not " Cash Sales ":

![image](https://user-images.githubusercontent.com/55691499/82634384-324a4680-9c1b-11ea-896a-a00228cec742.png)

**Comment by robiulpro** [comment]
@nutank 
as discussed the changes was only for forecast template, do i need to handle all other places as well (planned expense, quickbook data)?

**Comment by nutank** [comment]
@robiulpro , yes the requirement is only for forecast template but since planned shows up in forecast we would need to handle this side effect otherwise it would be inconsistent

**Comment by HazelColaco19** [comment]
Found the linkage in CSV import during Projection creation in forecast template

**Comment by HazelColaco19** [comment]
Can be closed as main task was tested. The other tasks associated to this one will be handled in #720
