### ISSUE TITLE
BUG - A-59, A-60,  A-61 - Closing cash balance from QB not getting synced

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#691]
- A-59 - Quickbooks closing balance not reflected in the forecast template for eg: in forecast template TEST050520 III QB Closing bal. is zero across 
 
- Opening balance for the past data in the forecast is negative, even though it is positive in the QB data (refer Test050520 III) | A-60
 
- New forecast created on the basis of QB past data is unable to pull the opening balance from QB (Refer Template 13 May 20) | A-61

**Comment by nutank** [comment]
This happened due to auth token failure error for QB. Should be fixed when #571 is fixed.

To be Closed after verifying token error fix

**Comment by HazelColaco19** [comment]
Tested on staging server and found all values " non zero " for QB closing cash balance.

**Comment by robiulpro** [comment]
Please check.

**Comment by HazelColaco19** [comment]
Fixed.  Tickets have been closed on the sheet by the client and confirmed.
