### ISSUE TITLE
TASK - Move the variance graphs - "Planned vs Actual" and "Planned vs Actual Accuracy" to Variance charts page

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#692]

**Comment by nutank** [comment]
- Also @Vaibhavarolkar please remove the net chart in both cases. We only need to have "Inflow" and "Outflow" in both cases

**Comment by nutank** [comment]
@HazelColaco19 once verified , we would need to remove these from the "Cashflow analysis" page

**Comment by HazelColaco19** [comment]
Any projection chose, for any Company in the dropdown it shows me " No Data " UI even if there is data

![image](https://user-images.githubusercontent.com/55691499/82299949-cb871c00-99d3-11ea-98f9-05ac7e2397b8.png)

**Comment by HazelColaco19** [comment]
@Vaibhavarolkar 
When there is no data, remove these legends from graph

![image](https://user-images.githubusercontent.com/55691499/82313784-799bc180-99e6-11ea-9e9a-dac009f0f6b7.png)


When there are no forecast templates, change the text to 

" There are no forecast template to display the variance charts. Create forecast templates to view the same "

**Comment by HazelColaco19** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/55691499/82318301-414bb180-99ed-11ea-964b-1ca472f0d83a.png)

However in the case of no data we will need to change the screen, currently above screen is used.

It should be something like this but without the legend

![image](https://user-images.githubusercontent.com/55691499/82318506-9c7da400-99ed-11ea-8263-51ac91faf883.png)

**Comment by HazelColaco19** [comment]
A turn around was changing the text so that both scenarios are handled for this release
![image](https://user-images.githubusercontent.com/55691499/82320489-0186c900-99f1-11ea-8835-e5122b3d71f6.png)
