### ISSUE TITLE
UAT BUG - Issues after deploying company setup to UAT

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#694]
Imported Company id = 21
Quickbook Login details as below:

nutan+1@ajency.in / Ajency#123

- [x] The forecast templates for existing "Flipmo" company giving error. Forecast template page gives "Add new template"
- [x] Mails go in spam with no links - @robiulpro change sender to yours so if this cannot be figured out
- [x] Templates for newly imported company are giving blank page - Forecast template link - https://client-uat.toppeq.com/cashflow/projection/25536/edit
- [x] Last synced date of "company_quickbook_accounts" table did not change. Still remain even after competion of step 2. Did a re-sync from UI. Still the value is null.

**Comment by HazelColaco19** [comment]
Tested point 2 above for qb account nutan+3@ajency.in and Company id =57
Mails go in spam with no links - @robiulpro change sender to yours so if this cannot be figured out.

Cannot verify 4 at the moment, might have to do a sync some other day and verify the date change
