### ISSUE TITLE
UAT BUG - Issues after deploying company setup to UAT 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#695]
Company_id= 45

- [ ] Transactions of type " Payments from Customer " or " Payments " not synced to Toppeq and are missing from Kibana. @legred21 QBParentID = 19, company = 45

[Kibana Link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:45,type:phrase),type:phrase,value:'45'),query:(match:(companyId:(query:45,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:transactionType.keyword,negate:!f,params:(query:Payment,type:phrase),type:phrase,value:Payment),query:(match:(transactionType.keyword:(query:Payment,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:qbParentId,negate:!f,params:(query:19,type:phrase),type:phrase,value:'19'),query:(match:(qbParentId:(query:19,type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

- [ ] Transactions of type " Bill payment "  not synced to Toppeq and are missing from Kibana. @legred21 company = 45, qbparentid = 27, Transaction type = Bill Payment

[Kibana Link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:45,type:phrase),type:phrase,value:'45'),query:(match:(companyId:(query:45,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:transactionType.keyword,negate:!f,params:(query:'Bill%20Payment',type:phrase),type:phrase,value:'Bill%20Payment'),query:(match:(transactionType.keyword:(query:'Bill%20Payment',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:qbParentId,negate:!f,params:(query:27,type:phrase),type:phrase,value:'27'),query:(match:(qbParentId:(query:27,type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

- [ ] Forecast Template: Closing Cash balance does not come to zero for Jan 2020 - May 2020. Can be the missing transactions above @legred21 

- [ ] Cashflow Analysis screen does not show any graphs when a template is chosen which  has a shifted projection

**Comment by legred21** [comment]
Indexing Issue exist.  bill payment and Payment from customer are fetched after the successful fetch of bills and invoices. Irrespective is bills or payments are fetched we need to fetch bill payments and payments from  customer. 
Also the bill payment made id 27 has split between bill and journal entry. 
Payment made against journal entry is not handled during syncing

**Comment by legred21** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Can be tested once pushed to UAT

**Comment by HazelColaco19** [comment]
Company id = 57, same QB account as above ( nutan+3@ajency.in )

![image](https://user-images.githubusercontent.com/55691499/82350233-b5e81580-9a18-11ea-897b-1c02de5ee4e0.png)


- [ ] Transactions of type " Bill payment " not synced to Toppeq and are missing from Kibana. @legred21 company = 45, qbparentid = 27, Transaction type = Bill Payment


[Kibana Link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:txnDate,negate:!f,params:(gte:1588291200000,lt:1590883200000),type:range,value:'1,588,291,200,000%20to%201,590,883,200,000'),range:(txnDate:(gte:1588291200000,lt:1590883200000))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:57,type:phrase),type:phrase,value:'57'),query:(match:(companyId:(query:57,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:transactionType.keyword,negate:!f,params:(query:'Bill%20Payment',type:phrase),type:phrase,value:'Bill%20Payment'),query:(match:(transactionType.keyword:(query:'Bill%20Payment',type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))
 

- [ ] Transactions of type " Payments from Customer " or " Payments " not synced to Toppeq and are missing from Kibana. @legred21 QBParentID = 19, company = 45

[Kibana Link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:txnDate,negate:!f,params:(gte:1588291200000,lt:1590883200000),type:range,value:'1,588,291,200,000%20to%201,590,883,200,000'),range:(txnDate:(gte:1588291200000,lt:1590883200000))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:57,type:phrase),type:phrase,value:'57'),query:(match:(companyId:(query:57,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:transactionType.keyword,negate:!f,params:(query:Payment,type:phrase),type:phrase,value:Payment),query:(match:(transactionType.keyword:(query:Payment,type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))


@legred21 @nutank

**Comment by legred21** [comment]
Bill payment and payment from customer last updated date was 2020-05-15. syncing after 2020-05-15 date was not fetching previous bills. Changed the last synced date and synced again showed up the entry in elastic

**Comment by nutank** [comment]
@HazelColaco19 - try this for new company linked to flipmo on ajency qa server and then let legred have a look

**Comment by HazelColaco19** [comment]
Closing the ticket, will be looked at in #715
