### ISSUE TITLE
UI Issues On UAT post release

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#696]
- [x] Principal amount column is not aligned on resolution - 1366*768
- [x] Highlighting of graphs is missing
- [x] Quickbook data table padding seems off on UAT?. On Ajency QA server it seems fine.

**Comment by HazelColaco19** [comment]
@Vaibhavarolkar Please look at the Third point. The table is cut off on UAT server.


![image](https://user-images.githubusercontent.com/55691499/82203317-c4eb9c80-9920-11ea-8cf9-2f7e4ad001d2.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82342964-dbbcec80-9a0f-11ea-88ae-801d374c91ce.png)
