### ISSUE TITLE
TASK - Move Amazon SES to production

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#698]

**Comment by nutank** [comment]
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

**Comment by nutank** [comment]
Reason for moving out of sandbox: (as provided by Aditya)

_TOPPEQ is building a platform for assisting Private Equity firms manage and record their share capital, track funding rounds and forecast cashflow requirements,
Through Amazon SES, we will be sending all our client users a link to connect with their QuickBooks account with our platform along with links and updates of financial metrics_

**Comment by robiulpro** [comment]
Completed.
Removed nutan@ajency.in, hazel@ajency.in from whitelisted email, you can now try sending mail to these sender to verify.

**Comment by HazelColaco19** [comment]
Tested this by adding " non ajency " email ( basically those not mentioned above ) and it worked. Closing the ticket.

![image](https://user-images.githubusercontent.com/55691499/82638252-244cf380-9c24-11ea-9fa5-ce12db24af22.png)
