### ISSUE TITLE
BUG - If sync API fails, all values get updated as zero. 

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#700]
Expected behaviour - If API fails at least older values should be retained for pnl_cogs, pnl_sales etc.

**Comment by robiulpro** [comment]
Fixed.

**Comment by robiulpro** [comment]
Going forward if api fails, the value should not get updated to zero in company cash table. Currently if api fails during syncing, the code blindly update the value to zero.

**Comment by HazelColaco19** [comment]
Tested this by changing re-sync date to 2018 Jan.

Then random checks for pnl_cogs, pnl_sales values which were zero and compared to the report in QB for respective company. The values were zero in QB upon random check.

Closing ticket
