### ISSUE TITLE
BUG - Principal Amount alignment broken on UAT - Screen res = 1366*768

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#705]
![Screenshot 2020-05-19 at 8 25 52 AM](https://user-images.githubusercontent.com/7425622/82279555-74b91c80-99aa-11ea-904f-0b5ddd455016.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82318652-d484e700-99ed-11ea-8e05-8e57a47fa637.png)

**Comment by HazelColaco19** [comment]
Tested this on a system with same resolution. 
It works fine when scaling of the pc is set to 100% but when scaling is increased to 125% it breaks.

**Comment by HazelColaco19** [comment]
Can be closed
