### ISSUE TITLE
TASK - When user with whatsapp number is mapped to a company at the time of import, a greeting whatsapp message needs to be sent to the respective user

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#707]
Code reference for this can be seen in this [graphql end point of creating users](https://ajency-qa.api.toppeq.com/graphiql?query=%0Amutation%20createUsers(%24input%3A%20%5BUserInput%5D!)%20%7B%0A%20%20createUsers(input%3A%20%24input)%20%7B%0A%20%20%20%20id%0A%20%20%20%20whatsappNo%0A%20%20%20%20name%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22input%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22company%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22id%22%3A%202%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22externalUserId%22%3A%2012%2C%0A%20%20%20%20%20%20%22userMeta%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22Legred%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22whatsappNo%22%3A%20%229823588464%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22Legred%22%2C%0A%20%20%20%20%20%20%22countryCode%22%3A%2091%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D&operationName=createUsers).

**Comment by nutank** [comment]
Graphql endpoint that creates users and sends WA greeting message can be seen [here](https://ajency-qa.api.toppeq.com/graphiql?query=%0Amutation%20createUsers(%24input%3A%20%5BUserInput%5D!)%20%7B%0A%20%20createUsers(input%3A%20%24input)%20%7B%0A%20%20%20%20id%0A%20%20%20%20whatsappNo%0A%20%20%20%20name%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22input%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22company%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22id%22%3A%202%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22externalUserId%22%3A%2012%2C%0A%20%20%20%20%20%20%22userMeta%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22Legred%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22whatsappNo%22%3A%20%229823588464%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22Legred%22%2C%0A%20%20%20%20%20%20%22countryCode%22%3A%2091%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D&operationName=createUsers)

**Comment by robiulpro** [comment]
Done.

**Comment by HazelColaco19** [comment]
Fixed
