### ISSUE TITLE
TASK - Update styling of company dropdown

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#708]
![image (4)](https://user-images.githubusercontent.com/7425622/82412385-2df22200-9a91-11ea-82d4-a971a0d99b26.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/82636746-f1edc700-9c20-11ea-98f6-3b8d3809fc36.png)
