### ISSUE TITLE
BUG - On UAT server when planned expenses is disabled it gives error while applying the change

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#709]
Projection - Graphs only scenario

![image (6)](https://user-images.githubusercontent.com/7425622/82412556-78739e80-9a91-11ea-9827-c9ed2c109a03.png)

**Comment by robiulpro** [comment]
Fixed. This issue was only when the past data source is csv. I have handled that scenario now.

**Comment by HazelColaco19** [comment]
Cannot upload the CSV file while creation of a projection. It validates or sends a message saying " Not a CSV " when a CSV is being uploaded.

File in Question: [Link](https://drive.google.com/open?id=1Fu0W1CEOJ19YhNPWs_DMat4DB2veQL0Z)

![image](https://user-images.githubusercontent.com/55691499/82640450-3d57a380-9c28-11ea-90ef-e0912af0b9e0.png)

**Comment by HazelColaco19** [comment]
In Db changed the Source = CSV for the projection and tested for that projection for company 32. Seems fixed, so closing this ticket.

![image](https://user-images.githubusercontent.com/55691499/82641739-78f36d00-9c2a-11ea-82c6-4e4739b7a1c2.png)
 

The above bug I reported will be tracked under ticket #717
