### ISSUE TITLE
TASK - Variance Graphs new UI

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#710]
![image (7)](https://user-images.githubusercontent.com/7425622/82412922-1ebfa400-9a92-11ea-9bca-c44409e1cd4b.png)

**Comment by nutank** [comment]
@Vaibhavarolkar would need to do the color changes for "Planned vs Actual" and "Planned vs Actual Accuracy" as follows:

![image](https://user-images.githubusercontent.com/7425622/82553109-0da19080-9b81-11ea-9aa0-a17e60041162.png)

**Comment by robiulpro** [comment]
Completed.

**Comment by HazelColaco19** [comment]
The colors don't match the design @Vaibhavarolkar  Please check

@robiulpro 
Can see this at first

![image](https://user-images.githubusercontent.com/55691499/82665104-b965e180-9c50-11ea-81a8-d9b716bb0249.png)


Then i switch between drop downs and the graph breaks

![image](https://user-images.githubusercontent.com/55691499/82664842-3f355d00-9c50-11ea-9ab6-d491f7e80e1d.png)

**Comment by robiulpro** [comment]
@nutank @HazelColaco19 
None of the color mismatch, the thing is in real scenario the difference of planned and real is huge, so it looks like the color is different.

**Comment by robiulpro** [comment]
Breaking graph on dropdown changes: Fixed.

**Comment by HazelColaco19** [comment]
@robiulpro 

1. I added more data and tested the colors, I guess the one marked by me still appear different


![image](https://user-images.githubusercontent.com/55691499/82983518-deba6d00-a00d-11ea-93ae-ee729bc3eb4a.png)


2. It doesn't break the graph anymore on drop down shift ---> Fixed

**Comment by robiulpro** [comment]
@Vaibhavarolkar 
Could you please give me the correct color code for left side graph as mentioned by @HazelColaco19

**Comment by robiulpro** [comment]
@HazelColaco19 
Color corrected.

**Comment by HazelColaco19** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/55691499/83014313-1b04c200-a03c-11ea-8e8e-57bd44823257.png)
