### ISSUE TITLE
BUG - Syncing Fails for all linked companies

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#714]
this is response in network

{"timestamp":"2020-05-21T08:55:36.652+0000","status":500,"error":"Internal Server Error","message":"could not execute statement; SQL [n/a]; constraint [company_quickbook_accounts_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement","path":"/rest/api/syncQuickBook"}

![image](https://user-images.githubusercontent.com/55691499/82543828-c3fd7980-9b71-11ea-9953-f7e759be3de7.png)

**Comment by legred21** [comment]
DB issue. Duplicated company Id existed in table
