### ISSUE TITLE
TASK - A-70 - Dropdown size to select projection should be increased in Cashflow Analysis & Variance Charts

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#716]
![image (1)](https://user-images.githubusercontent.com/7425622/82553319-6c670a00-9b81-11ea-8138-b41e283e822c.png)

**Comment by HazelColaco19** [comment]
Looks fixed:

Cashflow analysis
![image](https://user-images.githubusercontent.com/55691499/82674119-77dd3280-9c60-11ea-839e-0a4e27912ca8.png)

Variance charts

![image](https://user-images.githubusercontent.com/55691499/82674195-92171080-9c60-11ea-9e26-aff4566e0a18.png)
