### ISSUE TITLE
BUG - Can see " + " sign under Bank of America for all the positive values. There should be no " + " sign

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#719]
![image](https://user-images.githubusercontent.com/55691499/82660412-f1b4f200-9c47-11ea-986f-7843853ff60c.png)

**Comment by robiulpro** [comment]
Completed.

**Comment by HazelColaco19** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/55691499/82662425-75241280-9c4b-11ea-8d26-43090f77e393.png)
