### ISSUE TITLE
TASK : Display name change should be handled at various other places linked

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#720]
@robiulpro 

- [x] Additionally,  for **planned expense** tested to check if the mapping shows updated, but it shows the previous text " Sales " and not " Cash Sales ". Even the text " Sale of Product Income below shouldv have changed:

![image](https://user-images.githubusercontent.com/55691499/82634384-324a4680-9c1b-11ea-896a-a00228cec742.png)

- [x] And for COGS, I cannot see the previous mapping to even view the current mapping

![image](https://user-images.githubusercontent.com/55691499/82634668-fbc0fb80-9c1b-11ea-8134-dcec2a327ff1.png)

- [ ] Also found the linkage in CSV import during Projection creation in forecast template.

- [x] To handle in QB data tables

- [x] To handle in QB data dropdown

**_Originally posted by_** @HazelColaco19 **_in_** #690

**Comment by robiulpro** [comment]
@nutank 
Regarding the point "Also found the linkage in CSV import during Projection creation in forecast template." ---- i don't think we should do name changes in csv, as this will lead to data inconsistency and we have to check each category in many places whether it is  display name or actual name before inserting to db. Also this will increate the processing time. Please let me know.

**Comment by HazelColaco19** [comment]
Point 1, 2 - fixed:

![image](https://user-images.githubusercontent.com/55691499/83738259-b2d46280-a671-11ea-896e-ba8bf857128c.png)

![image](https://user-images.githubusercontent.com/55691499/83738111-802a6a00-a671-11ea-8722-6889e74daf3a.png)


Point 3 fixed:
![image](https://user-images.githubusercontent.com/55691499/83738419-ed3dff80-a671-11ea-88ad-a46c5bea8c8f.png)

Point 4 fixed:
![image](https://user-images.githubusercontent.com/55691499/83738531-0cd52800-a672-11ea-860e-4f39a0bfdb50.png)
