### ISSUE TITLE
BUG - On UAT link planned expenses for a template created from CSV , the values don't show up on forecast template. where as they did on staging server

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#721]
On UAT link planned expenses for a template created from CSV , the values don't show up on forecast template. where as they did on staging server
UAT SERVER server: Company 57, pctn id = 34239

There should've been values in June, july , august ( 10k, 20k, 30k respectively )

Compare with QA Staging : Company 32, pction  = 105163
See values reflected in july month onwards

![image](https://user-images.githubusercontent.com/55691499/82787119-6889ff00-9e83-11ea-947c-ba8432862fa1.png)

**Comment by robiulpro** [comment]
@HazelColaco19 
Please verify below scenario:
1. If planned expense was created earlier (before projection creation), then once you create the projection and its falling in that future date range, planned expense data should appear in template.
2. If planned expense was created after creating the projection, then you have to click on 'Update Data' button from projection template to reflect the planned expense in template. 

Now for a projection where source is 'CSV', 'Upload Data' button is not there. You have to confirm with Aditya whether we can put that button just to sync planned expense data in case the projection source is 'CSV'.

**Comment by HazelColaco19** [comment]
Works for both scenarios mentioned above. Closing the ticket

![image](https://user-images.githubusercontent.com/55691499/82987943-06adce80-a016-11ea-83dc-69682174474b.png)
