### ISSUE TITLE
BUG - The entries can be seen in Kibana but not on Forecast template

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#724]
**DETAILS OF EXPENSE:**

**qbAccountCategory | toppeqCategory | toppeqActivityType**

qb id = 42, 2000, 25 May 2020  
Purchases    Cost of Goods Sold    Operating

qb id = 42, 600, 25 May 2020
Cost of Goods Sold	Cost of Goods Sold	Operating
 

**Current behavior:**

The entries can be seen in Kibana but not on Forecast template

**Comment by legred21** [comment]
cashflow aggregation error. cashflow aggregation by transaction Date and category id

**Comment by HazelColaco19** [comment]
Is not valid anymore, the entry was deleted from QB while testing Delete feature
