### ISSUE TITLE
BUG - All the deleted entries from QB ( and kibana post sync ) are seen on Forecast template even post  " update "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#726]
Deleted entries in " Deposit " can be seen in Forecast template

company = 65, Projection id = 109465

Entries deleted from QB and from Kibana are seen in forecast template

- [ ]  Example1: 

"qb id = 39, amount = 222, 11 feb 2020

**qbAccountCategory | toppeqCategory | toppeqActivityType**
Sales of Product Income           Sales of Goods        Operating"

![image](https://user-images.githubusercontent.com/55691499/82823265-df93b780-9ec4-11ea-8379-6660d1ff43ed.png)

- [ ] Example 2: 

"qb id = 41, 1100, 26 May 2020

Sales	Sales of Goods	Operating"

![image](https://user-images.githubusercontent.com/55691499/82823688-a60f7c00-9ec5-11ea-96b3-0521637e6fde.png)

**Comment by legred21** [comment]
Deleted from elastic was successful but delete from cashflow table was unsuccessful. Date passed to query was not start of the month

**Comment by HazelColaco19** [comment]
1. Fixed

![image](https://user-images.githubusercontent.com/55691499/83745727-9dfccc80-a67b-11ea-9e35-8ff79f487c13.png)

2. Fixed

![image](https://user-images.githubusercontent.com/55691499/83745778-b2d96000-a67b-11ea-9057-84d6a17bdd60.png)
