### ISSUE TITLE
A-78-Forecast Template: Admin expense of $1000 was added in planned expense for June-20 however it's not reflecting under forecast template planned template 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#734]
Can be due to the missed mapping. Related #735 

Added an expense, it showed up in planned outflow but did not show up in forecast template. 

Mappings can be seen in db table. See comment in #735

**Comment by nutank** [comment]
#760, #735 - possible duplicates

**Comment by HazelColaco19** [comment]
Created an admin expense for September 2020. It reflected in Outflow and forecast template both.

![image](https://user-images.githubusercontent.com/55691499/83778241-0cf01a80-a6a8-11ea-8efa-639ba6c63985.png)



![image](https://user-images.githubusercontent.com/55691499/83778375-4163d680-a6a8-11ea-80b9-ff1c1aae8c60.png)
