### ISSUE TITLE
A-73-QB Data: Deposit of 40000 was added for 15th March however it shows double negative sign

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#739]
**Details for this as on CAshflow table**

"OUTFLOW"	"OPERATING" 	"Accounts Receivable (A/R)"	44	-40000.00	"MONTHLY"  "Accounts Receivable"

**Comment by robiulpro** [comment]
@HazelColaco19 
As discussed, the transaction was added against a category has type Outflow, hence the - amount. I have removed additional - prefex in UI as well.

**Comment by HazelColaco19** [comment]
On staging, the value now appears  to be a positive since this Flipmo company was uploaded using Company setup which has " Account receivable mapped against Inflow and not Outflow.

![image](https://user-images.githubusercontent.com/55691499/82982004-e2002980-a00a-11ea-8684-5cd17c43f9be.png)

The Client has deleted this record. To be tested on live uat
