### ISSUE TITLE
BUG - A-69	QB Data: "Following A/c Categories are not pulled : • Bad Debts  • Op. Bal Equity • Salary Payable • Depreciation •COGS"

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#743]
Tested On Client UAT, Company id = 8;

General Ledger Report [link](https://c43.qbo.intuit.com/app/reportv2?token=GEN_LEDGER&show_logo=false&date_macro=custom&low_date=01/01/2019&high_date=05/26/2020&cash_basis=no&customized=yes&columns=~date%3ATxDate%2C~txn_type_label%3ATxTypeID%2C~doc_num%3ATxHeader%2FDocNum%2C~name_label%3ATxHeader%2FNameID%2C~memo_desc_label%3AMemoText%2C~split_label%3AOtherAccountID%2C-~amount_label%3ANaturalAmount%2C%3D~balance_label%3ANaturalAmount%2C&edited_sections=false&divideby1000=false&hidecents=false&negativenums=1&negativered=false&show_header_title=true&show_header_range=true&show_footer_custom_message=true&show_footer_date=true&show_footer_time=true&header_alignment=Center&footer_alignment=Center&show_header_company=true&company_name=QUANT&cumulative=yes&title=General%20Ledger&footer_custom_message=)

The transactions under the following account categories are not pulled:

**1. Bad Debts**

- [x] qbParent ID = 216. @legred21 
Entry is present is QB but not in KIBANA 
Entry looks to be of type " Journal Entry " 

Kibana [link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:8,type:phrase),type:phrase,value:'8'),query:(match:(companyId:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:qbParentId,negate:!f,params:(query:216,type:phrase),type:phrase,value:'216'),query:(match:(qbParentId:(query:216,type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

**2.  Op. Bal Equity**

1. Txn ID - 3 is a zero value record

Below are non zero records, but cannot be seen on kibana @legred21 

- [ ] 2. Txn ID - 406. Kibana [Link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:8,type:phrase),type:phrase,value:'8'),query:(match:(companyId:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:qbParentId,negate:!f,params:(query:406,type:phrase),type:phrase,value:'406'),query:(match:(qbParentId:(query:406,type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

- [ ] 3. Txn ID - 415. Kibana [Link](http://15.206.44.131:5601/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:companyId,negate:!f,params:(query:8,type:phrase),type:phrase,value:'8'),query:(match:(companyId:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',key:qbParentId,negate:!f,params:(query:415,type:phrase),type:phrase,value:'415'),query:(match:(qbParentId:(query:415,type:phrase))))),index:'63259a50-6ff9-11ea-a03e-39eef02dc6df',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc)))

**3. Salary Payable**

has a transaction of type " Transfer ". Txn Id = 252. We are not handling. 

**4. Depreciation**

Missing Journal entries from KIBANa @legred21 

_QB Parent ID:_ 

- [x] 139, 

- [x] 140, 

- [x] 141, 

- [x] 142 uptil 151

**5. COGS**

We are not handling.

**Comment by HazelColaco19** [comment]
BUG - Journal Entries are not getting synced to UAT server. Qb Parent ID: 43, 14, 8

**Comment by HazelColaco19** [comment]
To be tested on UAT server

**Comment by HazelColaco19** [comment]
Missing enteries on Staging 

 2. Txn ID - 406. Kibana Link

 3. Txn ID - 415. Kibana Link

**Comment by legred21** [comment]
Journal Entry 406 and 415 are not fetched from quickbook by api

**Comment by HazelColaco19** [comment]
Closing this ticket
