### ISSUE TITLE
BUG - A-67	QB Data:"Data in Bank of America is shown till September only if we select the period full period (Jan 19 to Today) data displayed under a particular a/c category is limited to certain rows?"

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#745]

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Fixed

DAta in QB

![image](https://user-images.githubusercontent.com/55691499/83637826-d4781000-a5c5-11ea-9605-44acaf81f61a.png)

Data in toppeq

![image](https://user-images.githubusercontent.com/55691499/83637863-e22d9580-a5c5-11ea-9a10-0f5a1c182275.png)
