### ISSUE TITLE
BUG - Closing cash balance difference is not coming to zero for Company ID = 32, 65 on staging

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#755]
**Company ID = 32**

![image](https://user-images.githubusercontent.com/55691499/83140840-58d11b80-a10c-11ea-9cc7-eeefee658e69.png)

![image](https://user-images.githubusercontent.com/55691499/83140870-5ff82980-a10c-11ea-9440-bac7f47a89c2.png)

![image](https://user-images.githubusercontent.com/55691499/83140907-6e464580-a10c-11ea-80a1-9d8b39120c8c.png)

![image](https://user-images.githubusercontent.com/55691499/83140936-7900da80-a10c-11ea-892c-a96e482e3aee.png)

![image](https://user-images.githubusercontent.com/55691499/83140963-84ec9c80-a10c-11ea-8a83-f03df909503a.png)

![image](https://user-images.githubusercontent.com/55691499/83141008-9766d600-a10c-11ea-8a10-a6c3560d3e8c.png)

**Company ID = 65**

![image](https://user-images.githubusercontent.com/55691499/83140754-3212e500-a10c-11ea-8e2d-dccd3fcbbf1b.png)

![image](https://user-images.githubusercontent.com/55691499/83140784-3f2fd400-a10c-11ea-9925-8f0c5d89600d.png)

**Comment by legred21** [comment]
For company 32 (Flipmo) : 

- Jan 2019 550 record missing in FT, present in kibanan:https://c43.qbo.intuit.com/app/billpayment?txnId=310

-Feb 2019

**Comment by legred21** [comment]
For company 32 (Flipmo) :

- For the month of April 2020 closing cash balance difference is 210:
      This is because the following payment of 210 has no line items
      https://c43.qbo.intuit.com/app/recvpayment?txnId=418

- For the month of May 2020 closing cash balance difference is 6710:
     This is due to amount of 210 from April 2020 and amount of 6500 (31st may) 
     https://c43.qbo.intuit.com/app/expense?txnId=449

**Comment by legred21** [comment]
For company 65 (HZ enterprises) :

For the month of Jan 2020 closing cash balance difference is 19000:
This is because the following recieve payment of 19000 has no line items
https://c42.qbo.intuit.com/app/recvpayment?txnId=26

**Comment by HazelColaco19** [comment]
Flipmo shows 0

![image](https://user-images.githubusercontent.com/55691499/83730452-b9a9a800-a666-11ea-8e0a-a271bb58a3af.png)


And HZ enterprises shows 19000, the record without line items. 

Ticket can be closed
