### ISSUE TITLE
BUG - A-09	QB Data : Rename Incurred Outflow to QuickBooks Data

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#761]

**Comment by HazelColaco19** [comment]
**"On the side panel:**

QuickBooks Transaction to QuickBooks Data 

**Inside the page:**

QuickBook Transaction to QuickBooks Data 
Planned Outflow to Planned Transactions"

**Comment by robiulpro** [comment]
Done.

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/83621402-417eac00-a5ac-11ea-86ea-711286ac67e3.png)

![image](https://user-images.githubusercontent.com/55691499/83621426-46dbf680-a5ac-11ea-806a-a4f6c7606f57.png)
