### ISSUE TITLE
BUG - A-87	Cashflow Analysis: After adding Outflows in Investment Categories we are not able to see it on the cash inflow outflow graph

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#764]
The Investing toppeq headers do not have associated QB categories in the dropdown, hence even if an expense is added it will not be associated to a category hence won't be displayed. Need to check if the Mapping exist in QB table. PG admin is not opening at the moment.

![image](https://user-images.githubusercontent.com/55691499/83437630-b4c5d800-a45d-11ea-8a64-44fcf52bfc1f.png)

![image](https://user-images.githubusercontent.com/55691499/83437659-be4f4000-a45d-11ea-9d11-2f8083c47197.png)

![image](https://user-images.githubusercontent.com/55691499/83437684-cc9d5c00-a45d-11ea-93e4-22443f239882.png)

**Comment by legred21** [comment]
Categories list were overwritten by  other categories. There was one such toppeq detail type in list which had zero records therefore all previous categories disappeared from the list. Fixed by appending  categories to list

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/83639669-a34d0f00-a5c8-11ea-90a5-e297066905c2.png)
