### ISSUE TITLE
BUG - A-89 - https://client-uat.toppeq.com/cashflow/outflow/planned#/db_22878 - screen going blank

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#766]

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
To be tested on UAT

**Comment by HazelColaco19** [comment]
Fixed. Does not go blank.

https://client-uat.toppeq.com/cashflow/outflow/planned#/db_22878

![image](https://user-images.githubusercontent.com/55691499/83771514-fe056a00-a69f-11ea-8475-002a56d28542.png)
