### ISSUE TITLE
TASK - A-90 -Variance charts - planned and actual should always have consistent space in between

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#767]
Initial UI:

![image](https://user-images.githubusercontent.com/55691499/83402287-11a49c80-a424-11ea-937e-8d89b1d3aa07.png)

Expected UI: 

The space between the bars have been reduced now. 

![image](https://user-images.githubusercontent.com/55691499/83402353-39940000-a424-11ea-9dc6-527e8f940e7b.png)

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/83845258-23d55200-a726-11ea-80ab-3d23bba2a7be.png)
