### ISSUE TITLE
TASK - A-91 - Variance charts - till 6 month graph should sit side by side

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#768]
"Fit in 5 on one graph and fit both the graphs side by side. 
Take a call fitting in 6 bars on one graph depending on space requirements"

**Comment by HazelColaco19** [comment]
Currently four months bar sits side by side with two graphs inline. But that was the initial requirement when three graphs were inline only four months could fit in.

So now that there are just two graphs inline - we can maybe fit in 5-6 months. @nutan will decide if it has to be taken up

**Comment by HazelColaco19** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/55691499/83751486-8d9d1f80-a684-11ea-9c08-466dfa34da29.png)
