### ISSUE TITLE
BUG - A-87 - Runway completion circle only considers number i.e. 8 month show more circle covered than 5 years

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#769]

**Comment by HazelColaco19** [comment]
The graphs look full since its more than the configuration ( 8 ).


![image](https://user-images.githubusercontent.com/55691499/83425091-f8631680-a44a-11ea-9d7d-934b1e842baf.png)


![image](https://user-images.githubusercontent.com/55691499/83425071-f1d49f00-a44a-11ea-8feb-12bf91441122.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Looks fixed.

May 29 : 1 month is 

![image](https://user-images.githubusercontent.com/55691499/83633631-e4d8bc80-a5be-11ea-8088-4ed0e8fe809f.png)

June 3 : 22 days to go


![image](https://user-images.githubusercontent.com/55691499/83633689-fd48d700-a5be-11ea-8469-97d064ab3524.png)

Variance test : 2 months to go

![image](https://user-images.githubusercontent.com/55691499/83633741-0f2a7a00-a5bf-11ea-9ce4-90a02a4a4c5e.png)

May 28.1 : 1 year to go

![image](https://user-images.githubusercontent.com/55691499/83633828-2ec1a280-a5bf-11ea-8524-db61891b7e6a.png)
