### ISSUE TITLE
BUG - Whatsapp message format Issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#774]
**Design Format:**

![image](https://user-images.githubusercontent.com/55691499/83508882-306c6700-a4e8-11ea-8ec0-5bb365b2dc6b.png)

- [x] 1. The headers should come in bold

![image](https://user-images.githubusercontent.com/55691499/83508942-45e19100-a4e8-11ea-8cfb-03b0050bb154.png)

- [x] 2. The months should be displayed in Bold

- [x] 3. The months are running endlessly. Need to cap them at 2 decimal places.

- [x] 4. Text in bracket should be in italic, currently its not

- [x] 5. Cash emoji is missing

- [ ] 6. The text should dynamically update " Weekly/ Monthly/ Daily ". Currently says " monthly " for all the event triggers.

**Comment by nutank** [comment]
@legred21 please give me the updated template that would need to be whitelisted from Twilio.

Current template sent is not having the emoji etc.
