### ISSUE TITLE
BUG - The UI has a pattern of light green and white lines beneath every block, in actual email we have just white plain background

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#776]
_Originally posted in_ #773 

4. The UI has a pattern of light green and white lines beneath every block, in actual email we have just white plain background @Vaibhavarolkar

**Design:**

![image](https://user-images.githubusercontent.com/55691499/83503992-90134400-a4e1-11ea-9472-30c42f57475e.png)

**Actual:**
![image](https://user-images.githubusercontent.com/55691499/83504993-d2895080-a4e2-11ea-9592-befe240c5c98.png)

**Comment by Vaibhavarolkar** [comment]
@legred21 please update the code with this.
[email_template_toppeq.zip](https://github.com/ajency/cashflow-issue-tracker/files/4729321/email_template_toppeq.zip)

**Comment by HazelColaco19** [comment]
Shadow could not be applied as mentioned by Legred and Vaibhav. Replaced with border.

![image](https://user-images.githubusercontent.com/55691499/84107307-eaa92480-aa3a-11ea-9990-f47b97345f7b.png)
