### ISSUE TITLE
BUG - Forecast template does not update the planned expense if the date has been changed. It shows up in older month as well as month of the changed date upon updation.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#777]
**Scenario:** 

Company 32

1. Created a planned expense for the month of August. db_120802
1.1 Updated the Forecast template to show it under " Loans Given " - Investing Type.
![image](https://user-images.githubusercontent.com/55691499/83719645-287e0580-a655-11ea-8334-469e868c13cb.png)

2. Then edited the date to set the planned expense to July instead of August. 
2.1 The planned expense has disappeared from August under Planned transaction but is still visible in the forecast template upon update. So now we have the value repeating twice on the forecast template

![image](https://user-images.githubusercontent.com/55691499/83719440-b4dbf880-a654-11ea-8a23-43cca99f3122.png)

Example 2: db_121338

![image](https://user-images.githubusercontent.com/55691499/83721137-18b3f080-a658-11ea-9ddd-ed04f41969d6.png)

Post updation:

![image](https://user-images.githubusercontent.com/55691499/83721249-54e75100-a658-11ea-9589-eb5a5efc8b71.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Fixed
