### ISSUE TITLE
BUG - The amount of " Accounts payable " and " Accounts receivable " does not change even if the date range changes

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#781]
**Date range:** Last quarter

![image](https://user-images.githubusercontent.com/55691499/84029501-1e8b3800-a9b0-11ea-8949-11cb7f0371f7.png)

**Date range:** 1 Jan 2019 - 31 May 2019

![image](https://user-images.githubusercontent.com/55691499/84029660-6316d380-a9b0-11ea-8e05-676541d3867d.png)

**Comment by nutank** [comment]
@robiulpro this has been reported by the client as well.

Issue N-12, and N-23 in the sheet - https://docs.google.com/spreadsheets/d/1rZx9m9KOEvLSXIr0OJl8WMkDYTcMaNg0NZECtIiB2Os/edit?ts=5eb01b20#gid=18948490

**Comment by robiulpro** [comment]
Fixed.

**Comment by legred21** [comment]
Tested. Works Fine
