### ISSUE TITLE
TASK - Handle Delete of Bill payment and customer payment line items

### ISSUE THREAD

**Issue by legred21** [ajency/cashflow-issue-tracker#790]

**Comment by nutank** [comment]
@legred21 can you provide use case that this ticket handles? Provide an example so I can test it.

Also provide branch name

**Comment by legred21** [comment]
1. Do a bill payment towards more than one bill in a single bill payment and sync
2. In elastic all bill payments will appear
3. Now uncheck payment of one bill from the bill payment and resync
4. only payments towards one bill should appear in elastic and payments made earlier towards second bill should get deleted

**Comment by HazelColaco19** [comment]
Fixed
