### ISSUE TITLE
BUG - A-106 - In the forecast template, for the future period when we enter any value on the income side it shows as planned expenses and forcast expenses ( For Income it should be planned income and forecast income)	A-106

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#793]

**Comment by HazelColaco19** [comment]
Area 1: Logic will need to be changed
![image](https://user-images.githubusercontent.com/55691499/86122070-c8b03880-baf4-11ea-8bd4-be697834185c.png)

Area 2: Text Change
![image](https://user-images.githubusercontent.com/55691499/86122080-cd74ec80-baf4-11ea-93d6-455a38f6d4af.png)

**Comment by robiulpro** [comment]
Done

**Comment by legred21** [comment]
Tested 

![image](https://user-images.githubusercontent.com/55079454/87511197-8b21e280-c692-11ea-8d70-a3837f4fa2fb.png)
