### ISSUE TITLE
BUG - Header of accounting head list shows static message

### ISSUE THREAD

**Issue by legred21** [ajency/cashflow-issue-tracker#797]
Header of accounting head list shows static text as "TRAVEL TO MUMBAI FOR TOPPEQ" for all planned expenses( new and edit expense)

![image](https://user-images.githubusercontent.com/55079454/84985695-dd86e680-b15a-11ea-9a18-1ba94ce2c2df.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by legred21** [comment]
Tested
![image](https://user-images.githubusercontent.com/55079454/87511355-cae8ca00-c692-11ea-80b4-7559116f7531.png)
