### ISSUE TITLE
COGS of Aug 2019 & Oct 2019 is not pulled correctly in Forecast Template for Quant - UAT - https://demo.toppeq.com/cashflow/projection/45708/edit

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#798]
COGS of Aug 2019 & Oct 2019 is not pulled correctly in Forecast Template for Quant - UAT

"Cost of goods sold" for month of Aug shows 4801 instead of 3381
"Cost of goods sold" for month of Oct shows 35220 instead of 52996

**Comment by legred21** [comment]
For the month august of two transactions amount got indexed wrongly 
![image](https://user-images.githubusercontent.com/55079454/85133377-2ec8d000-b258-11ea-94d3-1dddaae5325b.png)

**Comment by HazelColaco19** [comment]
Fixed. Even the QB closing cash difference balance now shows 0 for all months

![image](https://user-images.githubusercontent.com/55691499/85396582-a146f200-b56f-11ea-9c9d-8c296e5bcc4a.png)
