### ISSUE TITLE
BUG - N-4 - Some popup green and some orange on Projection template -  all should be green (Delete cell/row popup, Add projection)

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#799]
Add pop up:

![image](https://user-images.githubusercontent.com/55691499/85365054-2f0be880-b542-11ea-9761-477693213e95.png)

Row pop up:

![image](https://user-images.githubusercontent.com/55691499/85365110-4cd94d80-b542-11ea-962d-25bfca7e896a.png)

Delete cell:

**Comment by HazelColaco19** [comment]
- [ ] Add Pop up
- [ ] Row pop up
- [ ] Delete cell

**Comment by HazelColaco19** [comment]
Follow the video to check the orange remnants

https://www.awesomescreenshot.com/video/289259?key=ceeea2451190f7c02ad9202ea1a6262c

![image](https://user-images.githubusercontent.com/55691499/85980077-51e54380-b9ff-11ea-8c1a-b62e66c14850.png)

**Comment by Vaibhavarolkar** [comment]
@HazelColaco19 i have used blue arrow color from one of the drop downs on the site.

**Comment by HazelColaco19** [comment]
Fixed. 

![image](https://user-images.githubusercontent.com/55691499/85987774-b9a18b80-ba0b-11ea-8e84-b3b29d7fbd8f.png)

![image](https://user-images.githubusercontent.com/55691499/85987792-c32af380-ba0b-11ea-9804-ab6f3ba41b98.png)
