### ISSUE TITLE
BUG - Post hitting the cron, the " flat sync tracker " table shows "Pending status ". Value of current assets doesn't get updated per QB in " Company Cash " table

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#802]
**Current value :** Table - company cash
![image](https://user-images.githubusercontent.com/55691499/85386016-a9e3fc00-b560-11ea-96a6-be3476dbafe4.png)

**To be updated to :** Table - flat data sync tracker

![image](https://user-images.githubusercontent.com/55691499/85386194-e9124d00-b560-11ea-9d37-282ac09687c4.png)

**Comment by legred21** [comment]
Fixed and deployed

**Comment by legred21** [comment]
values were not converted to double before setting to db

**Comment by HazelColaco19** [comment]
fixed
