### ISSUE TITLE
BUG - On creating a projection template with duration jan 2019 - Dec 2020, post creation it shows the projection range as " Dec 2018 - Nov 2020 "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#804]
This can be an issue since we consider Current month in the future and not in the past.. Need to check

![image](https://user-images.githubusercontent.com/55691499/85701941-8b663800-b6fb-11ea-9e27-a09364c96c6a.png)

**Comment by HazelColaco19** [comment]
Not fixed. On creation of a projection " Jan 2019 - Dec 2020", this is the result:

![image](https://user-images.githubusercontent.com/55691499/85830832-e0ad5280-b7aa-11ea-9666-c0c175c9839d.png)

**Comment by legred21** [comment]
Fixed from front end. Reverted fix from server side

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/85832765-49e29500-b7ae-11ea-83e4-3de63799de34.png)
