### ISSUE TITLE
BUG - N-14 - In IDBI CC Account some deposit transaction type are reflected as negative ( Eg Date 1-10-2019 Amount 1140925) (Atlantis)	

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#805]

**Comment by HazelColaco19** [comment]
Qb accounting category =  Claims Receivable -Exports - whose QB category detail type = Loan to Others which is mapped to " Toppeq category detail type = Loans given " and loans given is an " Outflow "

**Comment by HazelColaco19** [comment]
Closed
