### ISSUE TITLE
N-15 - Email Notification format not proper. Mail sent - Not proper on Outlook

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#806]

**Comment by nutank** [comment]
@HazelColaco19 can you provide a screenshot?

**Comment by HazelColaco19** [comment]
This is how it appears on Outlook.

![image](https://user-images.githubusercontent.com/55691499/86120393-dd3f0180-baf1-11ea-95fa-dd41f810a982.png)

**Comment by legred21** [comment]
@Vaibhavarolkar changes have been pushed to UAT

**Comment by HazelColaco19** [comment]
Fixed
