### ISSUE TITLE
N-22 : Avg. days to Collect from Customers/Vendors: Post April Month are not matching and are inconsistent with manually calculated figure. It is fine before April. Omkar has provided correct data 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#815]
File link provided by Omkar

https://toppeq.slack.com/files/UTTSAP2R0/F016LBWHN8J/dso_calculations.xlsx

![image](https://user-images.githubusercontent.com/55691499/87020630-be2b2880-c1f1-11ea-93e6-d4d9ca67c1f0.png)
![image](https://user-images.githubusercontent.com/55691499/87020670-cc794480-c1f1-11ea-8c63-09e1cdc7e2a3.png)

**Comment by legred21** [comment]
Tested
