### ISSUE TITLE
N-23: The figure for Accounts Receivable/Payable is being displayed for as on today, irrespective of period selected. It should be as on the last date of period selected

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#817]
**Bug** 

The value(s) does not change irrespective of the period of selection

Month of June 2020, see highlighted figure:

![image](https://user-images.githubusercontent.com/55691499/87011643-d432ec00-c1e5-11ea-9e85-97185e5a6629.png)

June to July 2019, see highlighted figure:

![image](https://user-images.githubusercontent.com/55691499/87011805-05132100-c1e6-11ea-8e9e-51a393327185.png)

**Expected:**

It should be as on the last date of period selected

**Comment by legred21** [comment]
Similar to #781
