### ISSUE TITLE
N-24: Avg. days to collect customers/vendors & Quick ration/wc ratio blank for the current month even though have data

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#818]
**Problem Statement By Aditya with regards to WCR and QR:**

1. We should never see a blank even if end date is a future date
2. The WCR/ QR values are improper
3. Avg days values is improper

**Comment by HazelColaco19** [comment]
For point number 1, need to confirm on requirement and check how it is built. According to what is known, we do not consider future dates for this calculation or pulling data from future dates is not done. We only pull data as on " End date ". Now since we run the cron at the end of the day at 11:30 PM, the data of the reports will be synced only at that time and not on the fly.

**Suggestion:** 

Change the default filter for Key Metrics date range to " Start of the month to(  Current date - 1 ) )

![image](https://user-images.githubusercontent.com/55691499/87040277-1839e700-c20e-11ea-97c0-804d9290dcf6.png)

**Comment by legred21** [comment]
Tested
