### ISSUE TITLE
N-25: Avg. days to collect from customers/vendors blank for last month

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#819]
**Bug description:**

company ID = 101

The Avg days to collect from customers = 54.67 but on the website it shows null.  

[Link to my calculation.](https://docs.google.com/spreadsheets/d/16OCL-tx4QU4MUXqH0rHhRbpc0bkNnMpcbd0AUOHRovE/edit?usp=sharing) 

In UAT DB, the values of SOPI/ COGS have not populated for  the month of June in Cashflow Table. The table does not have these values hence it shows null in the UI. 

The Avg days to Pay to vendors will show null since the COGS is not populated in the cashflow table.

**Comment by legred21** [comment]
Company cash data is now populated using api call. Still need to test on UAT once fix goes live

**Comment by legred21** [comment]
Tested on UAT
