### ISSUE TITLE
N-26: Demo server don't show current month data ( July 2020 ) under QB Data screen

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#820]
**For the month of July 2020:**
Demo Server 
![image](https://user-images.githubusercontent.com/55691499/87004681-73061b00-c1db-11ea-9919-b6df559453cd.png)

The same range on UAT server 
![image](https://user-images.githubusercontent.com/55691499/87004707-7dc0b000-c1db-11ea-8f2c-8fab0d77d710.png)

Notice the sync status is shown on UI.  

Need to check if the data is present on Kibana on demo server. Found a blocker to test this, Kibana link not working.

![image](https://user-images.githubusercontent.com/55691499/87006900-05f48480-c1df-11ea-97f9-ab556823932d.png)

**Comment by legred21** [comment]
Tested 
![image](https://user-images.githubusercontent.com/55079454/87514057-49476b00-c697-11ea-83b8-2cccfd07edd0.png)
