### ISSUE TITLE
BUG - Changed subaccount: False, but kept parent ID value. Account is created as a sub account under Parent ID 58.  child account shud be decided if they have parent ID value and subaccount as true

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#825]
**Describe the bug with expected result:**

Changed subaccount: False, but kept parent ID value. Account is created as a sub account under Parent ID 58.  child account shud be decided if they have parent ID value and sub account as true.

**Data Used:**

{
"source": "tally",
 "data": [
{
"id": 77,
"name": "Cost of Labor-2",
"balance": 0,
"type": "Expense",
"active": true,
"subAccount": false,
"classification": "Expense",
"accountSubType": "Other Miscellaneous Service Cost",
"currentBalanceWithSubAccounts": 0,
"parentId": 58,
"fullyQualifiedName": "Job Expenses:Cost of Labor"
   }
]}

**Comment by legred21** [comment]
Fixed by validating for subAccount and parentId field

**Comment by HazelColaco19** [comment]
fixed

![image](https://user-images.githubusercontent.com/55691499/90402251-d0379b00-e0bc-11ea-9830-f5b5957e4169.png)
