### ISSUE TITLE
BUG - Support different date formats for the api. Reports/ transactional. Also reflect the supported formats in the response message

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#826]
**Describe the bug**
Currently only yyyy-MM-dd date format is supported. It also supports DD-MM-YYYY

**Expected:**

1.Need to include the following formats:

- DD/MM/YYYY

- yyyy/MM/dd

2. Add the above format in message in Api error response: 

Current message:
  "message": "Date format is invalid. kindly use yyyy-MM-dd date format",

**Change To message:**
"message": "Date format is invalid. kindly use yyyy-MM-dd OR dd-mm-yyyy OR dd/mm/yyyy OR yyyy/mm/dd date format",

**Comment by legred21** [comment]
The above said formats are now supported and error message is also updated

**Comment by HazelColaco19** [comment]
Fixed
format
![image](https://user-images.githubusercontent.com/55691499/90371030-f8f36c80-e08b-11ea-99ab-e01e91aa2625.png)

Message
![image](https://user-images.githubusercontent.com/55691499/90371251-4f60ab00-e08c-11ea-96d0-1aefd53447de.png)
