### ISSUE TITLE
BUG - The "balance" field in " Bill " request seems inappropriate for end user to fill in. If "amount" and "balance" are a mismatch, kibana shows "amount" value in balance field

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#827]
**Describe the bug**

The "balance" field in " Bill " request seems inappropriate for end user to fill in. If "amount" and "balance" are a mismatch, kibana shows "amount" value in balance field

Request passed:
![image](https://user-images.githubusercontent.com/55691499/90127637-1d490380-dd83-11ea-9636-b3788ed0c5d3.png)

kibana:
![image](https://user-images.githubusercontent.com/55691499/90127916-9f392c80-dd83-11ea-8963-c40f580617a2.png)

**Expected:**

Do not allow the end user to add the balance. This should be calculated or assumed by the system. 
If its a bill, assume the initial bill creation amount as balance. Handle this for Update too.

If its a bill payment, deduct the balance accordingly.

**Comment by legred21** [comment]
balance field removed from bill request. Balance is updated while processing bill payments

**Comment by HazelColaco19** [comment]
Fixed in request
