### ISSUE TITLE
BUG - Due date is mandatory in request but the data push is successful

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#828]
**Describe the bug**

Insomnia Screenshot
![image](https://user-images.githubusercontent.com/55691499/90132808-1246a100-dd8c-11ea-93b0-0284d35b87d9.png)

Data is pushed to kibana
![image](https://user-images.githubusercontent.com/55691499/90133048-6f425700-dd8c-11ea-9b39-bca635cde311.png)

API REQUEST IN DOCUMENT
![image](https://user-images.githubusercontent.com/55691499/90132904-37d3aa80-dd8c-11ea-9ca4-50b5abd03d92.png)

**Expected:**

If the mandatory field is missing, data should not be pushed or an error should be displayed

**Comment by legred21** [comment]
Due date validation empty check fixed

**Comment by HazelColaco19** [comment]
Fixed during create and update
![image](https://user-images.githubusercontent.com/55691499/90370497-1ecc4180-e08b-11ea-8f8f-ee771937eb55.png)
