### ISSUE TITLE
Due date for a bill is not displayed as per the due date in quickbooks 

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#83]
Quickbooks link- https://c50.sandbox.qbo.intuit.com/app/bill?txnId=400

![image](https://user-images.githubusercontent.com/45193277/74624664-62db9980-516f-11ea-9c6e-a2c1b71d3d56.png)

![image](https://user-images.githubusercontent.com/45193277/74624694-7dae0e00-516f-11ea-9e55-c252e12499dc.png)

**Comment by nutank** [comment]
@TejalBandekar the date in the date column would be the transaction date of the bill which is the bill date.

The date column in both list views (planned or incurred) should show "transaction date" in date column. This is as per my discussion with georgio.

**Comment by TejalBandekar** [comment]
Bill captured the bill date from quickbooks.
