### ISSUE TITLE
BUG - Journal entry credit is mapped to " Outflow". It should be Inflow. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#834]
**Describe the bug with expectations**

Journal entry credit is mapped to " Outflow". It should be Inflow. 

![image](https://user-images.githubusercontent.com/55691499/90239092-9eb49a80-de44-11ea-988f-af8d9d708678.png)

**Comment by legred21** [comment]
AccountCategory: Telephone with accountSubType: Utilities is mapped to cashflow type outflow. please use proper accounting that maps to inflow

**Comment by HazelColaco19** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/55691499/90403041-fad62380-e0bd-11ea-9250-51c9c7b187e2.png)
