### ISSUE TITLE
BUG - The "balance" field in Invoice request does not make sense. It should not be left to the user to update the balance but should be a calculation done on our end when the invoice is paid. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#835]
**Describe the bug with Expectations**
The "balance" field in Invoice request does not make sense. It should not be left to the user to update the balance but should be a calculation done on our end when the invoice is paid. 

Request: 

 ty_invoice_5545_66_1

{
  "transactionType": "Invoice",
  "source": "tally",
  "data": [
    {
      "id": 1,
      "parentId": 66,
      "description": "invoice of 222", 
      "lineItemAccountChildCategory": null,
      "lineItemAccountCategory": "Telephone",
      "lineItemAccountSubType": "Utilities",
      "lineItemCategoryId": 79,
      "amount": 222.2222,
      "balance": 222,
      "currency": "USD",
      "createDate": "2020-06-12",
      "txnDate": "2020-06-12",
      "lastModifiedDate": "2020-06-12",
      "dueDate": "2020-06-12",
      "paymentStatus": "Pending",
      "customer": "Latesh"
          }
  ]
}

Kibana data:

![image](https://user-images.githubusercontent.com/55691499/90241015-df61e300-de47-11ea-9a27-12cfb899b0dc.png)

**Comment by legred21** [comment]
Removed balance field from invoice request. Balance is updated when invoice payment is received

**Comment by HazelColaco19** [comment]
fixed

![image](https://user-images.githubusercontent.com/55691499/90401755-09bbd680-e0bc-11ea-8953-0ad76decaa5e.png)
