### ISSUE TITLE
BUG - Request for " payment " is a success even though the invoice "parentId": 431 does not exist. 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#836]
**Describe the bug**
Request for " payment " is a success even though the invoice "parentId": 458 does not exist. 

The payment id= ty_payment_5545_458_1_431_1

URL: [Link](http://ajency-qa.kibana.toppeq.com/app/kibana#/discover?_g=()&_a=(columns:!(accountSubType,_id),filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%27971c7830-77db-11ea-9bff-17296d6cdc0e%27,key:companyId,negate:!f,params:(query:5545,type:phrase),type:phrase,value:%275,545%27),query:(match:(companyId:(query:5545,type:phrase)))),(%27$state%27:(store:appState),meta:(alias:!n,disabled:!t,index:%27971c7830-77db-11ea-9bff-17296d6cdc0e%27,key:accountSubType.keyword,negate:!f,params:(query:OtherMiscellaneousServiceCost,type:phrase),type:phrase,value:OtherMiscellaneousServiceCost),query:(match:(accountSubType.keyword:(query:OtherMiscellaneousServiceCost,type:phrase))))),index:%275bf98340-726a-11ea-9bff-17296d6cdc0e%27,interval:auto,query:(language:lucene,query:%27%27),sort:!(_score,desc)))

![image](https://user-images.githubusercontent.com/55691499/90242178-27820500-de4a-11ea-8105-0f739a75ac09.png)

**Comment by legred21** [comment]
same as #829

**Comment by HazelColaco19** [comment]
Fixed
