### ISSUE TITLE
BUG - On payment of the invoice, the balance did not get updated.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#837]
**Describe the bug**
On payment of the invoice, the balance did not get updated

Payment and invoice ID's

Parent Invoice JSOn:

{
  "transactionType": "Invoice",
  "source": "tally",
  "data": [
    {
      "id": 1,
      "parentId": 66,
      "description": "invoice of 222", 
      "lineItemAccountChildCategory": null,
      "lineItemAccountCategory": "Telephone",
      "lineItemAccountSubType": "Utilities",
      "lineItemCategoryId": 79,
      "amount": 222.2222,
      "balance": 222,
      "currency": "USD",
      "createDate": "2020-06-12",
      "txnDate": "2020-06-12",
      "lastModifiedDate": "2020-06-12",
      "dueDate": "2020-06-12",
      "paymentStatus": "Pending",
      "customer": "Latesh"
          }
  ]
}

PAYMENT Request:

 {
	 "transactionType": "Payment",
  "source": "tally",
  "data": [
    {
      "id": 1,
      "parentId": 66,
    "parentAccountingCategoryName": "Telephone",
    "parentAccountingCategoryId": 34,
    "parentPaymentCategoryType": "Utilities",
    "lineItemAccountChildCategory": null,
    "lineItemAccountCategory": "Telephone",
    "lineItemAccountSubType": "Utilities",
    "lineItemCategoryId": 79,
    "amount": 222,
    "currency": "USD",
    "createDate": "2020-06-12",
    "txnDate": "2020-06-12",
    "lastModifiedDate": "2020-06-12",
    "customer": "Nutan",
    "invoiceId": "66",
    "invoiceLineItemId": 1
    }
  ]
}

The Amount in Invoice does not get updated.

![image](https://user-images.githubusercontent.com/55691499/90243298-44b7d300-de4c-11ea-8d91-d2cda3f4958e.png)

**Comment by legred21** [comment]
issue existed in generating id of invoice. id generated string was having bill id and bill line item id. Fixed by replacing bill id by invoice id and bill line item id by invoice line item id

**Comment by HazelColaco19** [comment]
fixed

![image](https://user-images.githubusercontent.com/55691499/90402132-a1b9c000-e0bc-11ea-8848-c208612ddf92.png)
