### ISSUE TITLE
BUG - Delete API request does not work. Shows 404 error. Could not test it for any payment types

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#840]
**Describe the bug**
Delete API request does not work. Shows 404 

![Screenshot_20200814-212024](https://user-images.githubusercontent.com/55691499/90268283-6a58d280-de74-11ea-88b2-077d0117d9bd.jpg)

**Comment by legred21** [comment]
was having merge conflicts in code and was not deployed in combo branch.

**Comment by HazelColaco19** [comment]
fixed
