### ISSUE TITLE
BUG - Quickbooks data > Telephone + Checking associated with each other in account category dropdown. On click of Checking, telephone gets selected and vice versa

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#841]
![image](https://user-images.githubusercontent.com/55691499/90364732-394ded00-e082-11ea-93d3-daf09aac2799.png)

**Comment by legred21** [comment]
Issue existed in old transaction got created without checking accounting category in db. Accounting category id check is being done in validation process and therefore no two accounting categories can have same id.

**Comment by HazelColaco19** [comment]
fixed

![image](https://user-images.githubusercontent.com/55691499/90398317-d6c31400-e0b6-11ea-927c-e722ae0d663e.png)
