### ISSUE TITLE
BUG - Bank transactions are not showing up in the UI. can see it in kibana and db tables

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#842]
Bank: Checking

![image](https://user-images.githubusercontent.com/55691499/90364812-61d5e700-e082-11ea-87c7-40571d1c0629.png)

**Comment by legred21** [comment]
transactions are showing up

**Comment by HazelColaco19** [comment]
Fixed

![image](https://user-images.githubusercontent.com/55691499/90398409-fb1ef080-e0b6-11ea-8406-586f1db1498d.png)
