### ISSUE TITLE
BUG - Deleted Transaction type: Journal Entry Credit, transactions of type " Journal Entry Debit " also got deleted.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#844]
There were 5 transactions in " Credit " and 3 in " Debit ".

In screenshot you can see " 8 " transactions being deleted when delete result shouldv been 5

![image](https://user-images.githubusercontent.com/55691499/90383038-3c0a0b80-e09d-11ea-8b72-b15f42fa6ef5.png)

Json:

{
  "source": "tally",
  "transactionType" : "Journal Entry CREDIT",
  "startDate": "2019-01-01",
  "endDate": "2021-01-01"
}

Message:

{
  "message": "Deleted 8 transactions"
}

Expected:

Debit and credit type delete should be handled separately? Please confirm @nutank

**Comment by legred21** [comment]
Both will get deleted. they cannot exist alone

**Comment by HazelColaco19** [comment]
Ok. Closing the ticket.
