### ISSUE TITLE
BUG - Server throwing error code 500 internal server error instead of unauthorised access code 

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#845]
![image](https://user-images.githubusercontent.com/55691499/90505932-177f6380-e171-11ea-8bea-b860e5cda3bd.png)

**Comment by legred21** [comment]
Fixed. added try catch block

**Comment by HazelColaco19** [comment]
fixed
![image](https://user-images.githubusercontent.com/55691499/90522075-e9a61900-e188-11ea-9a63-c84492bbfd6e.png)
