### ISSUE TITLE
Search bar should handle the search even when it is not the exact match of the word

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#87]
- should be able to display search result basis the single alphabet. 

Actual Result- On search of single letter or partial word, no data is displayed in the search result.

![image](https://user-images.githubusercontent.com/45193277/74643765-43f2fc80-519b-11ea-9cdb-fef34848a7b8.png)

**Comment by legred21** [comment]
Issue fixed

**Comment by TejalBandekar** [comment]
Search handles spent on, tags and category column as per the initial requirements. 

I think it should also handle Accounting Category. 

@Nutan should we take this up?

**Comment by nutank** [comment]
@georgioajency this will need clarity.  please confirm.

**Comment by TejalBandekar** [comment]
@Legred Please pick this up.

**Comment by georgioajency** [comment]
@nutank @TejalBandekar as discussed the other day, please go ahead and handle the accounting categories in the search bar also.

**Comment by legred21** [comment]
search filter is fixed by tokenizing input search text. Each token is then supplied to wildcard query to filter rows from elastic

**Comment by TejalBandekar** [comment]
Fixed.
