### ISSUE TITLE
User needs to be taken to the 1st page when any filter or reset is applied on any other page

### ISSUE THREAD

**Issue by TejalBandekar** [ajency/cashflow-issue-tracker#90]
**Filter** 
Steps: 
1. Go to incurred outflow => list view 
2. Go to 3rd page 
3. Select the payment status as 'Paid' 

Expected: User should be taken to the 1st page and payment status should be paid 

Actual-  User is on the 3rd page and payment status is paid 

**Reset** 
Steps: 
1. Go to incurred outflow => list view 
2. Go to 3rd page 
3. Click on reset 

Expected: User should be taken to the 1st page and payment status should be paid 

Actual-  User is on the 3rd page and payment status is paid

**Comment by TejalBandekar** [comment]
Same for Planned Expense list view

**Comment by verlekar-viraj** [comment]
will be handled during server side pagination

**Comment by TejalBandekar** [comment]
Fixed.
